Repository cms-sw/cmsdist, pull requests merged in 2018-10, with the labels that each got.

#4396 Updated root to tip of branch v6-12-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4397 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4395 Updated root to tip of branch v6-14-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4391 Update CUDA_FLAGS used by CMSSW (10.3.x backport)
  cuda-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4390 Update CUDA_FLAGS used by CMSSW (10.3.x devel)
  cuda-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4376 [10.3.X] Update ibjpeg-turbo version to 1.5.3
  libjpeg-turbo.spec
  pyqt.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4384 [10.2.X] updated Sherpa 2.2.5 and OpenLoops 2.0.b
  openloops.spec
  scons.spec
  sherpa.spec
Labels: backport-ok, externals-approved, fully-signed, orp-approved, tests-approved

#4402 Update root-614 with latest fixes
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4401 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4406 New dasgoclient version
  dasgoclient-binary.spec
  dasgoclient.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4385 [9.3.X] updated Sherpa 2.2.5 and OpenLoops 2.0.b
  openloops.spec
  scons.spec
  sherpa.spec
Labels: backport-ok, externals-approved, fully-signed, orp-approved, tests-approved

#4359 Update llvm/clang to version 7.0.0 (release)
  gcc-toolfile.spec
  icc-gcc-toolfile.spec
  llvm-gcc-toolfile.spec
  llvm.spec
  py2-dxr-clang700.patch
  py2-dxr.spec
  python_tools.spec
Labels: backport-ok, externals-approved, fully-signed, orp-pending, tests-approved

#4414 [7.1.X] updated Sherpa 2.2.5 and OpenLoops 2.0.b
  openloops.spec
  scons.spec
  sherpa.spec
Labels: backport-ok, externals-approved, fully-signed, orp-approved, tests-approved

#4418 Updated root to tip of branch v6-14-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4416 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4417 Updated root to tip of branch v6-12-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4415 update TBB to 2019_U1
  tbb.spec
Labels: externals-approved, fully-signed, orp-approved, tests-rejected

#4422 [10.4.X] patch llvm to avoid AARCH64 build errors
  llvm.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4428 update scram tag
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#4429 generate python_tools toolfile
  python_tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4430 Revert "Updated root to tip of branch v6-12-00-patches"
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4425 Updated root to tip of branch v6-14-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4433 Remove tinyxml external, tinyxml2 used instead in cmssw
  cmssw-tool-conf.spec
  fwlite-tool-conf.spec
  tinyxml-toolfile.spec
  tinyxml.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#4435 [10.4.X] BuildRules: Do not check the CUDA library version
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4436 Add dablooms spec and dablooms-toolfile spec so dablooms library can be linked by StaticAnalyzers library
  py2-dablooms-toolfile.spec
  py2-dablooms.spec
  python_tools.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#4438 add ofast-flag tool and updated SCRAM
  SCRAMV1.spec
  gcc-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4441 Updated root to tip of branch v6-14-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4440 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4447 Added py2-lxml and py2-beautifulsoup4 tools
  libxslt.spec
  py2-beautifulsoup4.spec
  py2-lxml.spec
  python_tools.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#4449 generate cuda-gcc-support toolfile if cuda supports the existing gcc version
  SCRAMV1.spec
  cuda-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4448 use default to openloops docs optimization, pick up factorial calc improvement
  openloops.spec
Labels: externals-pending, orp-approved, pending-signatures, tests-rejected

#4456 [10.4.X] updated to git version 2.19.0
  git-2.16.2-runtime.patch
  git-2.19.0-runtime.patch
  git.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4453 Updated root to tip of branch v6-14-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4454 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4457 set lizard PYTHON27 and PYTHON3 paths
  py2-lizard.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4463 update requests package to 2.20.0
  py2-requests.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4464 [10.4.X] enabled llvmlite and numba as these now support llvm 7
  py2-llvmlite.spec
  python_tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4419 backport cuda from 104X devel
  cuda-toolfile.spec
  cuda.spec
Labels: backport-ok, externals-pending, orp-pending, pending-signatures, tests-approved

#4465 [10.4.X] updated to git version 2.19.0
  git-2.16.2-runtime.patch
  git-2.19.0-runtime.patch
  git.spec
Labels: backport-ok, externals-pending, orp-pending, pending-signatures, tests-approved
