Repository cms-sw/cmsdist, pull requests merged in 2018-03, with the labels that each got.

#3783 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3784 Update CUDA 9.1.85 with patches to cuBLAS and ptxas
  cuda.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3763 Move the RecoEgamma-PhotonIdentification tag from 04 to 05
  data-RecoEgamma-PhotonIdentification.spec
Labels: backport-ok, externals-approved, fully-signed, orp-approved, tests-approved

#3774 Update RecoEgamma-ElectronIdentification to new tag
  data-RecoEgamma-ElectronIdentification.spec
Labels: backport-ok, externals-pending, orp-approved, pending-signatures, tests-approved

#3781 Updated root to tip of branch v6-12-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#3786 Update CUDA compilation flags
  cuda-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3785 Update L1Trigger-L1THGCal to tag 05
  data-L1Trigger-L1THGCal.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3771 added cmsssw data package EgammaAnalysis-ElectronTools
  cmsswdata.spec
  data-EgammaAnalysis-ElectronTools.spec
Labels: externals-pending, orp-approved, pending-signatures, tests-approved

#3788 Python3 spec file
  cmssw-tool-conf.spec
  python.spec
  python3-toolfile.spec
  python3.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#3790 use oracle 12.1.0.2.0 for gcc700
  oracle.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#3792 added cms_oracleocci_abi_hack-fake for aarch64
  cms_oracleocci_abi_hack-fake-toolfile.spec
  cms_oracleocci_abi_hack-fake.spec
  cmssw-tool-conf.spec
  oracle-fake-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#3793 Added flawfinder
  py2-flawfinder.spec
  py2-pippkgs.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3773 new EgammaAnalysis-ElectronTools data package for 94X
  cmsswdata.spec
  data-EgammaAnalysis-ElectronTools.spec
Labels: externals-pending, orp-approved, pending-signatures, tests-started

#3747 updated bazel 0.10.0; tensorflow 1.5.0
  bazel-0.4.5-java-vm.patch
  bazel.spec
  eigen-034b6c3e1017.patch
  eigen.spec
  py2-tensorflow.spec
  tensorflow-c.spec
  tensorflow-cc-toolfile.spec
  tensorflow-cc.spec
  tensorflow-sources.spec
  tensorflow-workspace.patch
Labels: externals-pending, orp-approved, pending-signatures, tests-rejected

#3801 tensorflow:use eigen and protobuf souces from cmsdist
  eigen.spec
  protobuf.spec
  tensorflow-sources.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3795 Update CUDA 9.1.85 with Patch 3 to cuBLAS
  cuda.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3811 fix up python27paths that showed problems in devel IB
  py2-numpy-toolfile.spec
  py2-sqlalchemy-toolfile.spec
  py2-sqlalchemy.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#3814 Bring tensorflow to aarch64
  cmssw-tool-conf.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#3809 use cms-external/eigen and move to latest commit
  eigen.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3799 Updated root to tip of branch v6-12-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#3816 Provide dummy implementation for occi on aarch64
  oracle-fake.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#3812 Fireworks-Geometry tag update
  data-Fireworks-Geometry.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#3817 Update data-Fireworks-Geometry.spec
  data-Fireworks-Geometry.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#3810 Tracker daq 4.2 gcc700
  cmssw.spec
  fwlite.spec
  tkonlinesw.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3798 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#3819 Tracker daq 4.2 gcc700
  cmssw.spec
  fwlite.spec
  tkonlinesw.spec
  trackerDAQ-4.2-cleanup-gcc7.patch
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3822 Improve method for using PYTHON27PATH
  python.spec
  python3.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#3823 Auto deps setup 101x
  rpm-preamble.file
  scram-project-build.file
  scram-tools-post.file
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#3818 Update data-Fireworks-Geometry.spec
  data-Fireworks-Geometry.spec
Labels: backport-ok, externals-pending, orp-pending, pending-signatures, tests-approved

#3821 Bump fastHadd version
  fasthadd.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3825 GCC ABI changes for 10.0.X
  SCRAMV1.spec
  cms-git-tools.spec
  cms_oracleocci_abi_hack-fake-toolfile.spec
  cms_oracleocci_abi_hack-fake.spec
  cms_oracleocci_abi_hack-toolfile.spec
  cms_oracleocci_abi_hack.spec
  cmssw-tool-conf.spec
  dasgoclient-binary.spec
  dasgoclient.spec
  gcc-toolfile.spec
  gcc.spec
  oracle-fake-toolfile.spec
  oracle-toolfile.spec
  scram-project-build.file
  scram-tools-post.file
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#3831 updated to use patched pythia8 from cms-external/pythia8
  pythia8.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3837 generate the man pages at build time
  cms-git-tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3838 dd4hep: clean up dependency (remove py2-rootpy)
  dd4hep.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3830 update fastjet-contrib to 1.033
  fastjet-contrib.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3842 updated build rules tag
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3844 Updated root to tip of branch v6-12-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3843 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3846 New dasgoclient version
  dasgoclient-binary.spec
  dasgoclient.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3847 Dd4hep update master 20180316
  dd4hep.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#3839 updated to use patched pythia8 from cms-external/pythia8 (93X)
  pythia8.spec
Labels: backport-ok, externals-approved, fully-signed, orp-pending, tests-approved

#3815 Update L1Trigger-L1THGCal to tag 05 (93X)
  data-L1Trigger-L1THGCal.spec
Labels: backport-ok, externals-pending, orp-pending, pending-signatures, tests-approved

#3850 Updated root to tip of branch v6-12-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#3851 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#3857 updated xrootd to 4.8.1 for devel IBs
  xrootd.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3858 remove use of pythonpath in cmssw
  beautifulsoup.spec
  cmssw-tool.file
  coral-tool.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3852 Updaetd git to 2.16.2
  curl.spec
  git-2.16.2-runtime.patch
  git.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#3860 update pythia8
  pythia8.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3863 update to cmssw-config for PYTHONPATH
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3864 Addition python package cleanups
  cmssw-tool-conf.spec
  cython-toolfile.spec
  cython.spec
  frontier_client.spec
  gosam.spec
  lhapdf.spec
  py2-numpy.spec
  py2-pippkgs.spec
  py2-sqlalchemy.spec
  python-ldap-toolfile.spec
  python-ldap.spec
  rivet.spec
  scram-project-build.file
  sip.spec
Labels: externals-pending, orp-approved, pending-signatures, tests-approved

#3870 add openldap dependency
  py2-pippkgs.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3874 Python migration towards pth instead of PATHs
  py2-numpy.spec
  py2-sqlalchemy.spec
  py2-tensorflow.spec
  python3.spec
  scramv1-tool-conf.file
  tensorflow-sources.spec
Labels: externals-pending, orp-approved, pending-signatures, tests-approved

#3873 Update PhysicsTools-NanoAOD to tag V01-00-01
  data-PhysicsTools-NanoAOD.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3867 Bring python support for fastjet
  fastjet-toolfile.spec
  fastjet.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#3876 relocate pth in cmssw-tool-conf
  scramv1-tool-conf.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3866 Update llvm to 6
  llvm.spec
  py2-pippkgs_depscipy.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#3879 Use pth file instead of most python path
  cvs2git-toolfile.spec
  das_client-toolfile.spec
  frontier_client-toolfile.spec
  gosam-toolfile.spec
  lhapdf-toolfile.spec
  llvm-gcc-toolfile.spec
  photospline-toolfile.spec
  professor-toolfile.spec
  professor2-toolfile.spec
  py2-PyYAML-toolfile.spec
  py2-cx-oracle-toolfile.spec
  py2-dablooms-toolfile.spec
  py2-dxr-toolfile.spec
  py2-lint-toolfile.spec
  py2-matplotlib-toolfile.spec
  py2-numpy-toolfile.spec
  py2-pip-toolfile.spec
  py2-pippkgs-toolfile.spec
  py2-pippkgs_depscipy-toolfile.spec
  py2-pygithub-toolfile.spec
  py2-setuptools-toolfile.spec
  py2-six-toolfile.spec
  py2-sqlalchemy-toolfile.spec
  pyminuit2-toolfile.spec
  pyqt-toolfile.spec
  rivet-toolfile.spec
  root-toolfile.spec
  scram-project-build.file
  sherpa-toolfile.spec
  sip-toolfile.spec
  xrootd-toolfile.spec
  yoda-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#3862 update pythia8 (93X)
  pythia8.spec
Labels: backport-ok, externals-pending, orp-pending, pending-signatures, tests-approved

#3871 Update pip to 903
  py2-pip.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#3875 Update PhysicsTools-NanoAOD to tag V01-00-01
  data-PhysicsTools-NanoAOD.spec
Labels: backport-ok, externals-pending, orp-pending, pending-signatures, tests-approved

#3883 Add Google common python package
  py2-googlecommon.spec
  py2-pippkgs_depscipy.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#3880 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3869 Make a switch from das_client to dasgoclient (DO NOT MERGE)
  dasgoclient.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3884 Updated root to tip of branch v6-12-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#3887 Update PhysicsTools-NanoAOD to tag V01-00-02
  data-PhysicsTools-NanoAOD.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved
