Repository cms-sw/cmsdist, pull requests merged in 2018-02, with the labels that each got.

#3728 Fix for tkonlinesw gcc7 cleanup
  tkonlinesw.spec
  trackerDAQ-4.2-cleanup-gcc7.patch
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#3724 Cherry-pick upstream changeset 10711:034b6c3e1017
  eigen-034b6c3e1017.patch
  eigen.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3723 Cherry-pick upstream changeset 10711:034b6c3e1017
  eigen-034b6c3e1017.patch
  eigen.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3730 added new tool cms_oracleocci_abi_hack
  cms_oracleocci_abi_hack-toolfile.spec
  cms_oracleocci_abi_hack.spec
  cmssw-tool-conf.spec
  oracle-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3733 include cms_oracleocci_abi_hack/include directory
  cms_oracleocci_abi_hack-toolfile.spec
  cms_oracleocci_abi_hack.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#3732 updated fastjet to 3.3.3 and fastjet-contrib to 1.032
  fastjet-contrib.spec
  fastjet.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3711 Dire 2.001
  cmssw-tool-conf.spec
  dire-toolfile.spec
  dire.spec
Labels: externals-pending, orp-approved, pending-signatures, tests-approved

#3735 Updated root to tip of branch v6-12-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#3737 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#3739 remove gcc4-compatible flag i.e. move back to new ABI
  gcc.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#3743 New dasgoclient version, added dasmaps option
  dasgoclient-binary.spec
  dasgoclient.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3744 define CMS_ORACLEOCCI_LIB env for tools to preload it if needed
  cms_oracleocci_abi_hack-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3740 Fix nvcc.profile and update CUDA compiler flags (10.1.x)
  cuda-toolfile.spec
  cuda.spec
Labels: bug-fix, externals-pending, orp-pending, pending-signatures, tests-approved

#3741 Fix nvcc.profile and update CUDA compiler flags (10.0.x)
  cuda-toolfile.spec
  cuda.spec
Labels: backport, bug-fix, externals-pending, orp-pending, pending-signatures, tests-approved

#3745 Try to make the changes to nvcc.profile more future-proof
  cuda.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3746 Update fastjet to v 3.3.0, based on IB/10_1_X/gcc630next PR 3732
  fastjet-contrib.spec
  fastjet.spec
Labels: externals-pending, orp-approved, pending-signatures, tests-approved

#3748 update vdt to 0.4.0
  vdt.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3750 updated cms-git-tools: allow branches to start with number
  cms-git-tools.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#3753 updated scram and cmssw-config tag
  SCRAMV1.spec
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3754 Update root master (cms rootgcc6)
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#3759 LHADPF cleanup and set PYTHONPATH
  lhapdf-toolfile.spec
  lhapdf.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#3752 Update root spec on CMS master branch - v6-10 patches to latest commit
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3761 cleanup boost dependency, added PYTHONPATH and PATH for lhapdf
  lhapdf-toolfile.spec
  lhapdf.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3768 Update davix to 0.6.7
  davix.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3769 Update llvmlite to 0.22 and numpy to 1.14
  py2-llvmlite.spec
  py2-numpy.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3770 updated scram and config tags
  SCRAMV1.spec
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3776 new scram which allows to add new filters via projects configuration
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3766 Updating RecoMuon-MuonIdentification to tag V01-12-03
  data-RecoMuon-MuonIdentification.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#3780 enable new CXX11 ABI for 10.1.X; drop -fno-crossjumping flag
  gcc-toolfile.spec
  gcc.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#3779 New dasgoclient version: fix look-up of invalid datasets
  dasgoclient-binary.spec
  dasgoclient.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected
