Repository cms-sw/cmsdist, pull requests merged in 2018-07, with the labels that each got.

#4161 [10.2.X] Ele MVA V2 weight files and gzipped all Run 2 weight files
  data-RecoEgamma-ElectronIdentification.spec
Labels: externals-pending, orp-approved, pending-signatures, tests-approved

#4152 [9.4.X][Geant4]: Fixed muon stopping + G4 bug in indexes
  geant4.spec
Labels: backport-ok, externals-pending, orp-approved, pending-signatures, tests-approved

#4169 bug fix: make sure that share/data has correct content after local deprecate local and re-install
  cmsswdata.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4170 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4168 Improve CUDA build rules to support linking device code across different libraries
  cuda-toolfile.spec
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4163 New dasgoclient version
  dasgoclient-binary.spec
  dasgoclient.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4180 updated build rules to V05-07-31
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#4181 Update data-GeneratorInterface-EvtGenInterface.spec
  data-GeneratorInterface-EvtGenInterface.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#4182 Update dd4hep to tag 01-08
  dd4hep.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#4145 Update L1Trigger-L1THGCal to tag 01-00-07
  data-L1Trigger-L1THGCal.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#4167 Add MXNet prediction tool
  cmssw-tool-conf.spec
  mxnet-predict-toolfile.spec
  mxnet-predict.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#4176 Update data-RecoBTag-Combined.spec
  data-RecoBTag-Combined.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#4188 Add dependencies for jupiter
  py2-jupyter.spec
  py2-send2trash.spec
  python_tools.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#4173 Update Eigen to leverage the latest updates to CUDA and AVX support
  eigen.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#4194 suppress usage of AVX instructions in mxnet
  mxnet-predict.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4193 Bump fastHadd version to 2.3
  fasthadd.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4199 updated config tag to V05-07-32
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#4201 Fix ROOT-9173: add per object flag for the statsoverflow
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#4200 updated config tag to V05-07-32
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#4203 root: sync in changes from gcc700 branch; drop castor and use ninja
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#4202 [10.2.X] Fix ROOT-9173: add per object flag for the statsoverflow
  root.spec
Labels: backport-ok, externals-pending, orp-pending, pending-signatures, tests-approved

#4198 suppress usage of AVX instructions in mxnet (102X version of #4194)
  mxnet-predict.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4206 add flake8 and autopep8 python file checkers
  py2-autopep8-toolfile.spec
  py2-autopep8.spec
  py2-flake8-toolfile.spec
  py2-flake8.spec
  python_tools.spec
Labels: externals-pending, orp-approved, pending-signatures, tests-approved

#4211 add pycodestyle as dependency of autopep8
  py2-pycodestyle.spec
  python_tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4210 Updated root to tip of branch v6-12-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4208 Updating root master.
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4219 Update h5py from 2.8.0rc1 to 2.8.0
  py2-h5py.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#4223 Add hdf5 python cache
  py2-h5py-cache.spec
  python_tools.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#4217 upgrade lhapdf pdf sets to 6.2.1b
  lhapdf.spec
  lhapdf_makeLinks.file
  lhapdf_pdfsetsindex.file
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#4215 Bump xrootd to 4.8.4
  xrootd.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#4183 Update data-GeneratorInterface-EvtGenInterface
  data-GeneratorInterface-EvtGenInterface.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved
