Repository cms-sw/cmsdist, pull requests merged in 2018-05, with the labels that each got.

#3960 Update geant4 commit hash
  geant4.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#3971 Update data-EgammaAnalysis-ElectronTools.spec
  data-EgammaAnalysis-ElectronTools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3975 Update cuda-api-wrappers with upstream (#47)
  cuda-api-wrappers-toolfile.spec
  cuda-api-wrappers.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3974 Add an external for nvidia cub (version 1.8.0)
  cmssw-tool-conf.spec
  cub-toolfile.spec
  cub.spec
Labels: externals-approved, fully-signed, orp-pending, tests-started

#3967 Update jemalloc to version 5.0.1
  jemalloc.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3945 Update data-L1Trigger-L1THGCal.spec
  data-L1Trigger-L1THGCal.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3961 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3983 Updated root to tip of branch v6-12-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3979 pythia8: initialize bools
  pythia8.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#3969 [94X] Updated fastjet-contrib: Inculded EnergyCorrelator in v1.026
  fastjet-contrib.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#3977 added data-DQM-DTMonitorClient
  cmsswdata.spec
  data-DQM-DTMonitorClient.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#3980 added data-DQM-DTMonitorClient
  cmsswdata.spec
  data-DQM-DTMonitorClient.spec
Labels: backport, externals-pending, orp-pending, pending-signatures, tests-approved

#3986 updated jemalloc to 5.0.1 and llvm 6.0.0
  jemalloc.spec
  llvm.spec
  py2-llvmlite.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#3988 Added catch2
  catch2-toolfile.spec
  catch2.spec
  cmssw-tool-conf.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#3984 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#3989 updated git 2.17.0 and build git-gui
  git.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3992 jemalloc: use configure option for setting the page size for arm64 and PowerPC
  jemalloc-toolfile.spec
  jemalloc.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#3995 Add virtual desctructor for Particle class
  pythia8.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3993 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#3972 Update data-EgammaAnalysis-ElectronTools.spec
  data-EgammaAnalysis-ElectronTools.spec
Labels: backport-ok, externals-pending, orp-approved, pending-signatures, tests-approved

#3999 update xrootd to 4.8.3
  xrootd.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4003 fix madgraph5amcatnlo: set dependencies root dirs
  madgraph5amcatnlo-config.patch
  madgraph5amcatnlo.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#3994 Updated root to tip of branch v6-12-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4008 Update CUDA to version 9.2.88 with Patch 1 to cuBLAS
  cuda.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4009 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#4012 backported xrootd and git from DEVEL IBs
  git.spec
  xrootd.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#4018 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4004 Update boost to 1.67
  boost.spec
  yaml-cpp.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4019 Updated root to tip of branch v6-14-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4020 Update yaml-cpp to 0.6.2
  yaml-cpp.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#4026 updated scram tag
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#4024 New dasgoclient version
  dasgoclient-binary.spec
  dasgoclient.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4028 added py2-numpy dependency
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#4039 llvm: only add cuda dependency for ARM64
  llvm.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#3944 Update data-RecoBTag-Combined.spec
  data-RecoBTag-Combined.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4044 cms-git-tools: updated to include checkdeps and cms-rmpkg
  cms-git-tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#4042 updated scram and config tag
  SCRAMV1.spec
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#4046 Update DD4Hep to tip of branch master
  dd4hep.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#4060 Improve Eigen compatibility with CUDA
  eigen.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#4061 Update dd4hep.spec
  dd4hep.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#4054 Update pythia8.spec
  pythia8.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved
