Repository cms-sw/cmsdist, pull requests merged in 2018-12, with the labels that each got.

#4515 [10.4.X] data SimTransport PPSProtonTransport and TotemRPProtonTransportParametrization
  cmsswdata.spec
  data/data-build-github-new.txt
Labels: externals-pending, orp-approved, pending-signatures, tests-approved

#4551 Update RecoBTag-Combined=V01-01-01
  data/data-build-github-new.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4554 Added RecoTauTag-TrainingFiles V00-01-00
  data/data-build-github-new.txt
Labels: externals-pending, orp-approved, pending-signatures, tests-approved

#4558 Update dd4hep to latest on master
  dd4hep.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#4518 [10.2.X] Update RecoEgamma-PhotonIdentification to 01-00-06
  data-RecoEgamma-PhotonIdentification.spec
Labels: backport-ok, externals-pending, orp-approved, pending-signatures, tests-approved

#4579 Backport #4554 to 10_2 gcc7
  data-RecoTauTag-TrainingFiles.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#4570 Add pycuda pip package to cmsdist
  pip/py2-Mako.file
  pip/py2-pycuda.file
  pip/py2-pytools.file
  pip/requirements.txt
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#4566 Add build dependency on tensorflow-sources to avoid build conflicts
  tensorflow-python3-sources.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4550 [10_2_X] Update data-RecoBTag-Combined.spec
  data-RecoBTag-Combined.spec
Labels: backport, externals-approved, fully-signed, orp-pending, tests-approved

#4549 [9_4_X] Update data-RecoBTag-Combined.spec
  data-RecoBTag-Combined.spec
Labels: backport, externals-approved, fully-signed, orp-pending, tests-approved

#4532 [10.4.X] Updat TBB to 2019_U2
  tbb.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#4583 added sm_60 cuda support for P100 GPU
  cuda-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4555 Update libjpeg-turbo to 2.0.1
  graphviz.spec
  libjpeg-turbo-toolfile.spec
  libjpeg-turbo.spec
  libtiff.spec
  pip/py2-pillow.file
  qt.spec
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4585 [10.4.X] Update TBB to 2019_U3
  tbb.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4586 [10.4.X] updated llvmlite to 0.27.0dev0
  pip/py2-llvmlite.file
  pip/requirements.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4588 [10.4.X] drop sm_35 from cuda toolfile
  cuda-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4577 Update geant4 to release 10.5
  geant4-G4PARTICLEXS.spec
  geant4-G4PhotonEvaporation.spec
  geant4-G4RadioactiveDecay.spec
  geant4-G4SAIDDATA.spec
  geant4.spec
  geant4data.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4589 [10.4.X] Added missing dependency on data-RecoTauTag-TrainingFiles
  cmsswdata.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#4590 [10.2.X] Added missing dependency on data-RecoTauTag-TrainingFiles
  cmsswdata.spec
  data-RecoTauTag-TrainingFiles.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#4595 [10.4.X] Added PhysicsTools-PatUtils data tool
  cmsswdata.spec
  data/data-build-github-new.txt
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#4596 [10.4.X] root tolefile: do not fail if /usr/local/include is missing e.g. in singularity
  root-toolfile.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#4597 Root update master 20181219
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4598 Root update v6.14 20181219
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4599 [Do not merge] Testing genreflex to generate pcms
  root-toolfile.spec
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#4604 [cxxmodule] Hopefully fix the build directory issue
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#4605 [root] delete root build directory to make sure that root do not have access to it
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4609 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved
