Repository cms-sw/cmsdist, pull requests merged in 2018-08, with the labels that each got.

#4151 [9.3.X] [Geant4]: Fixed muon stopping
  geant4.spec
Labels: backport-ok, externals-pending, orp-approved, pending-signatures, tests-approved

#4235 Update h5py from 2.8.0rc1 to 2.8.0
  py2-h5py.spec
Labels: backport-ok, externals-pending, orp-approved, pending-signatures, tests-approved

#4241 Update dd4hep to match ROOT TGeoMatrix interface
  dd4hep.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#4244 Updated root to tip of branch v6-12-00-patches
  root.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#4242 Updated root to tip of branch master
  root.spec
Labels: externals-approved, fully-signed, orp-approved, tests-rejected

#4249 Update data-L1Trigger-L1TMuon.spec
  data-L1Trigger-L1TMuon.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#4196 FastSimulation-TrackingRecHitProducer: New pixel resolution files
  data-FastSimulation-TrackingRecHitProducer.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#4230 Update RecoEgamma-PhotonIdentification to 01-00-06
  data-RecoEgamma-PhotonIdentification.spec
Labels: externals-pending, orp-approved, pending-signatures, tests-approved

#4254 Update dd4hep.spec
  dd4hep.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#4252 Update data-L1Trigger-L1THGCal.spec
  data-L1Trigger-L1THGCal.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#4257 Update CUDA to version 9.2.148, patch 1
  cuda.spec
Labels: externals-pending, orp-approved, pending-signatures, tests-approved

#4225 Numerous python tool updates to latest production version available
  py2-backports_lzma.spec
  py2-cherrypy.spec
  py2-cython.spec
  py2-decorator.spec
  py2-histbook.spec
  py2-idna.spec
  py2-ipywidgets.spec
  py2-lizard.spec
  py2-llvmlite.spec
  py2-lz4.spec
  py2-matplotlib.spec
  py2-notebook.spec
  py2-numba.spec
  py2-numpy.spec
  py2-oamap.spec
  py2-pandas.spec
  py2-parsimonious.spec
  py2-pathlib2.spec
  py2-pbr.spec
  py2-ptyprocess.spec
  py2-pytest.spec
  py2-pytz.spec
  py2-pyzmq.spec
  py2-requests.spec
  py2-root_pandas.spec
  py2-schema.spec
  py2-seaborn.spec
  py2-sympy.spec
  py2-tables.spec
  py2-tornado.spec
  py2-uproot.spec
  py2-urllib3.spec
  py2-virtualenv.spec
  py2-wheel.spec
  py2-xgboost.spec
Labels: externals-pending, orp-approved, pending-signatures, tests-approved

#4207 Patch MXNet to use a thread-local engine
  mxnet-predict-toolfile.spec
  mxnet-predict.spec
Labels: externals-pending, orp-approved, pending-signatures, tests-approved

#4264 Update xgboost patch file name
  py2-xgboost.spec
  xgboost-0.72-sse2.patch
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#4263 backport of py2-h5py from 10_3_X
  py2-h5py.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#4271 New dasgoclient version
  dasgoclient-binary.spec
  dasgoclient.spec
Labels: externals-pending, orp-approved, pending-signatures, tests-approved

#4262 Update CUDA to version 9.2.148, patch 1 (10.2.x backport)
  cuda.spec
Labels: backport-ok, externals-approved, fully-signed, orp-approved, tests-approved

#4265 Updated root to tip of branch v6-12-00-patches
  root.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#4250 Update data-L1Trigger-L1TMuon.spec
  data-L1Trigger-L1TMuon.spec
Labels: backport-ok, externals-pending, orp-pending, pending-signatures, tests-approved

#4255 Include Boost.MPI
  boost-toolfile.spec
  boost.spec
  openmpi-2.1.1-disable-lsf-support.patch
  openmpi.spec
Labels: externals-pending, orp-approved, pending-signatures, tests-approved

#4280 updating herwig to version 7.1.4 and ThePeG to 2.1.4
  herwigpp.spec
  thepeg.spec
Labels: externals-pending, orp-approved, pending-signatures, tests-approved

#4278 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-approved, pending-signatures, tests-rejected

#4277 Updated root to tip of branch v6-14-00-patches
  root.spec
Labels: externals-approved, fully-signed, orp-pending, tests-rejected

#4294 Update SCRAMV1.spec
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4290 cms-common: fix scram infinite loop
  cms-common.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4293 cms-git-tools: Minor updates to git-cms-init
  cms-git-tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4292 Updated root to tip of branch v6-14-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4295 New dasgoclient version for gcc700 architecture
  dasgoclient-binary.spec
  dasgoclient.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#4288 Update OpenMPI to version 2.1.5 (critical bugfix release)
  openmpi.spec
Labels: bug-fix, externals-approved, fully-signed, orp-approved, tests-approved

#4306 Update cms-git-tools.spec
  cms-git-tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#4261 Update OpenMPI to version 2.1.5 (critical bugfix release) (10.2.x backport)
  boost-toolfile.spec
  boost.spec
  openmpi-2.1.1-disable-lsf-support.patch
  openmpi.spec
Labels: backport-ok, bug-fix, externals-approved, fully-signed, orp-approved, tests-approved

#4304 Updated root to tip of branch v6-14-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#4303 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected
