Repository cms-sw/cmsdist, pull requests merged in 2019-11, with the labels that each got.

#5322 Updates SCRAM to version SCRAMV1 V2_2_9_pre05
  SCRAMV1.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#5323 make sure that py3/bin do not override py2/bin tools
  pip/ipython.file
  pip/jupyter_console.file
  pip/notebook.file
  pip/numpy.file
  pip/py2-tensorflow.file
  pip/py3-tensorflow.file
  pip/pylint.file
  pip/pytest.file
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5325 Update tag for SimTracker-SiStripDigitizer to V01-01-00
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5315 Rename py2-dablooms to dablooms. Remove dablooms python binding.
  cmssw-tool-conf.spec
  dablooms-toolfile.spec
  dablooms.spec
  py2-dablooms-toolfile.spec
  py2-dablooms.spec
  python_tools.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#5310 add lzma and xz dependencies as their python interface is now in python3 itself
  python3.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5326 Updates SCRAM to version SCRAMV1 V2_2_9_pre05
  SCRAMV1.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5328 Updated python packages
  pip/hyperopt.file
  pip/ipykernel.file
  pip/jsonschema.file
  pip/py3-jupyter_console.file
  pip/py3-tables.file
  pip/requirements.txt
  pip/tables.file
  py2-llvmlite-fpic-flag.patch
  python_tools.spec
  scramv1-tool-conf.file
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5327 [OpenLoops-2.1.0]Topping up Vtt+jets and Htt+jets libraries processes
  openloops.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5331 Update Bottleneck to version 1.3.0rc1
  pip/requirements.txt
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#5334 patch sqlalchemy 1.3.10 for python3
  pip/sqlalchemy.file
  py2-sqlalchemy-1.3.10-server_version_info.patch
  py2-sqlalchemy-1.3.4-server_version_info.patch
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5291 Backport OpenBLAS fixes [10_6_X]
  OpenBLAS.spec
  geneva.spec
  gsl-toolfile.spec
  gsl.spec
  herwigpp.spec
  thepeg.spec
Labels: comparison-available, externals-pending, orp-approved, pending-signatures, tests-rejected

#5342 [DD4Hep] Updated to get conversion for Polyhedra and Polycone fix
  dd4hep-build-static.patch
  dd4hep.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5344 [G4] Updated to version 10.06cand00 and its required datasets
  geant4-G4EMLOW.spec
  geant4-G4NDL.spec
  geant4-G4PhotonEvaporation.spec
  geant4-G4RadioactiveDecay.spec
  geant4.spec
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#5345 [71X] Updated cms git tools
  cms-git-tools.spec
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5339 [71X][Pythia8] Fix all uninitialized member variables
  pythia8.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5289 Backport OpenBLAS fixes [10_2_X]
  OpenBLAS.spec
  gsl-toolfile.spec
  gsl.spec
  herwigpp.spec
  rivet.spec
  thepeg.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-rejected

#5348 [94X] backport cms-git-tools changes
  cms-git-tools.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5349 [10.6.X] backport cms-git-tools changes
  cms-git-tools.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5352 [8.0.X] backport cms-git-tools changes
  cms-git-tools.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5351 [10.2.X] backport cms-git-tools changes
  cms-git-tools.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5350 [10.3.X] backport cms-git-tools changes
  cms-git-tools.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5347 [93X] backport cms-git-tools changes
  cms-git-tools.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5354 [PY] updated various python packages
  pip/requirements.txt
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5346 Update ONNX Runtime to v1.0.0
  onnxruntime-toolfile.spec
  onnxruntime.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, requires-external, tests-approved

#5361 [BuildRules] Copy only executables scripts in to cmssw/bin directory
  scram-project-build.file
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#5360 [ROOT618] Update root to 6.18.04 for 11.0.X
  root.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-rejected

#5365 Updates singularity scripts and cms-common for cc8
  cms-common.spec
  cmssw-osenv.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5367 [BuildRules] Fix SimDataFormatsValidationFormats_xr_rdict issue
  scram-project-build.file
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-rejected

#5364 [TBB] Include 2019 Update 9
  tbb.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5368 [ROOT CXXModule] Update config tag
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5370 update cms-common and cmssw-osenv
  cms-common.spec
  cmssw-osenv.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5371 [BuildRules] Fix SimDataFormatsValidationFormats_xr_rdict issue
  scram-project-build.file
Labels: backport-ok, comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5374 Update tag for L1Trigger-L1THGCal to V01-00-15
  data/cmsswdata.txt
Labels: comparison-pending, externals-approved, fully-signed, orp-approved, tests-approved

#5373 backport sherpa 2.2.8 to 71X
  sherpa.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5311 upgrade pythia8 to 243, vincia to 2.3.01, dire to 2.004
  dire.spec
  pythia8.spec
  vincia.spec
Labels: comparison-available, externals-pending, orp-approved, pending-signatures, requires-external, tests-approved

#5378 Updated root master on cmdist/root-master
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#5380 [Vincia] remove VinciaMG4 and VinciaMG5 libs
  vincia-toolfile.spec
Labels: comparison-pending, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#5383 [BuildRules] New rules to avoid picking externals libs for release/external/lib path
  scram-project-build.file
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, requires-external, tests-rejected

#5381 Update root on cmsdist/rootmodule
  root.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#5385 [CXXMODULE] Build rules updated
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5377 Updated root on cmsdist/master
  root.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-rejected

#5389 [MODULES][BuildRules] Make sure to set CLING_MODULEMAP_PATH during scram b
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5393 [CXXMODULE] Updated root to tip of branch master
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected
