Repository cms-sw/cmsdist, pull requests merged in 2019-04, with the labels that each got.

#4820 enable geant4 and example/ddcms for dd4hep
  dd4hep-build-static.patch
  dd4hep-toolfile.spec
  dd4hep.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#4835 [BuildRules][DD4Hep] look for listcomponent under DD4HEP_CORE_BASE
  dd4hep-toolfile.spec
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#4836 [CVE-2019-10255] Update py2-notebook to 5.7.8
  pip/requirements.txt
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#4790 Pyquen reintegration as external
  cmssw-tool-conf.spec
  pyquen-toolfile.spec
  pyquen.spec
Labels: comparison-available, externals-pending, generators-approved, orp-approved, pending-signatures, tests-approved

#4829 [10.6.X] Update RecoBTag-Combined to V01-01-03
  data/cmsswdata.txt
Labels: comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#4831 [BuildRules][CXXMODULES] New build rules to generate PCM for packages with multiple classes.h
  scram-project-build.file
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#4841 Update CUDA to version 10.1.105, on x86_64
  cuda.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#4855 Add DDG4 headers to dd4hep include
  dd4hep.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#4857 fwlite:drop FWCore/PyDevParameterSet and FWCore/Framework/bin
  fwlite.spec
  fwlite_build_set.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#4838 Update externals for ppc64 build
  dd4hep-add-ppc64-macro-check.patch
  dd4hep.spec
  geneva.spec
  herwigpp.spec
  pip/py2-pillow.file
  professor2-ppc64-flag-change.patch
  professor2.spec
  py2-tensorflow.spec
  tensorflow-sources.spec
  vecgeom-add-ppc64-cmake-fix.patch
  vecgeom.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#4865 Ignore .pyc and .pyo temporary files
  .gitignore
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#4861 Update Geant4 branch 4.10.5 -> 4.10.5ref03
  geant4.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#4860 [BuildRule][10.6.X] Fix build rule code-format
  scram-project-build.file
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#4859 Update dd4hep with latest changes on master and remove ppc64 patch
  dd4hep-add-ppc64-macro-check.patch
  dd4hep.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#4864 Include missing NVIDIA drivers (gcc820 build)
  cuda-toolfile.spec
  cuda.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#4863 Include missing NVIDIA drivers (gcc700 build)
  cuda-toolfile.spec
  cuda.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#4869 Condition for ppc64 for tfcompile
  tensorflow-toolfile.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#4846 Update gcc version to 7.4.1
  gcc.spec
Labels: comparison-available, compilation-warnings, externals-approved, fully-signed, orp-approved, tests-approved

#4872 Add ppc64 flags for gcc and llvm
  gcc-toolfile.spec
  llvm-gcc-toolfile.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#4870 update many python package versions
  pip/py2-beautifulsoup4.file
  pip/py2-flake8.file
  pip/py2-hyperopt.file
  pip/py2-schema.file
  pip/py2-soupsieve.file
  pip/requirements.txt
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#4850 Update Configuration-Generator tag to 01-00-03
  data/cmsswdata.txt
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#4873 Update gcc version 8.2.0 -> 8.3.0 on gcc8 branch
  gcc.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-rejected

#4871 Put condition for openloops in toolfiles - herwig and geneva
  cmssw-tool-conf.spec
  geneva-toolfile.spec
  herwigpp-toolfile.spec
  herwigpp.spec
  sherpa-toolfile.spec
  sherpa.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#4851 Update Configuration-Generator tag to 01-00-03 on 7_1
  data-Configuration-Generator.spec
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#4879 Fix pip xgboost 0.82 for arm and ppc
  pip/py2-xgboost.file
  py2-xgboost-arm-and-ppc.patch
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#4887 update python packages and xtensor
  pip/requirements.txt
  py2-matplotlib.spec
  py2-numpy.spec
  python_tools.spec
  xtensor.spec
  xtl.spec
Labels: comparison-available, externals-pending, orp-approved, pending-signatures, tests-rejected

#4886 Update CUDA to version 10.1.105, on x86_64
  cuda.spec
Labels: comparison-available, externals-pending, orp-approved, pending-signatures, tests-approved

#4881 initalizing theQuickParticles with nullptr
  thepeg.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#4893 Fix numpy on arm until patch is provided
  py2-numpy.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#4897 update openblas and a few more python tools
  OpenBLAS.spec
  pip/py2-deepdish.file
  pip/requirements.txt
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#4906 Add override option and python dependency
  cuda.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#4914 [10.6.X][BuildRules] keep extra new line for readability-braces-around-statements
  scram-project-build.file
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#4915 [BuildRules] For clang format find all sources files (lower+upper case externsions)
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#4898 Move RecoMuon-MuonIdentification to tag V01-12-05
  data/cmsswdata.txt
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#4916 [BuildRules] By default run code-format only for changed files
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending
