Repository cms-sw/cmsdist, pull requests merged in 2019-08, with the labels that each got.

#5121 Update tag for Configuration-Generator to V01-01-01
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5124 Update tag for RecoLocalCalo-EcalDeadChannelRecoveryAlgos to V01-01-00
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5125 Update lwtnn to 2.9
  lwtnn.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5123 Update tag for CalibCalorimetry-EcalTrivialCondModules to V00-03-00
  data/cmsswdata.txt
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5129 Updated root to tip of branch master
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#5131 CXXModule: new build rules
  CXXModules.mk.file
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5132 [71X] Update tag for Configuration-Generator to V01-01-01
  data-Configuration-Generator.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5084 update lhapdf sets to 6.2.1a_1
  lhapdf.spec
  lhapdf_makeLinks.file
  lhapdf_pdfsetsindex.file
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5049 update lhapdfsets to 6.2.1a_1
  lhapdf.spec
  lhapdf_makeLinks.file
  lhapdf_pdfsetsindex.file
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5135 Update cxxmodules branch
  root.spec
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#5134 Updated root to tip of branch master
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#5133 Updated root to tip of branch v6-18-00-patches
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#5137 Initial reference for SimG4CMS-HGCalTestBeam data repo
  cmsswdata.spec
  data/cmsswdata.txt
Labels: comparison-available, externals-pending, orp-approved, pending-signatures, tests-approved

#5141 Revert TF to 1.6 on DEVEL
  bazel.spec
  eigen-toolfile.spec
  pip/py2-protobuf.file
  pip/py2-tensorboard.file
  pip/py2-tensorflow-estimator.file
  pip/py2-tensorflow.file
  pip/requirements.txt
  protobuf.spec
  py2-tensorflow.spec
  tensorflow-1.6.0-eigen-backports.patch
  tensorflow-1.6.0-eigen-rename-sigmoid.patch
  tensorflow-1.6.0-eigen-update-gemm_pack_lhs.patch
  tensorflow-1.6.0-rename-runtime.patch
  tensorflow-deps.file
  tensorflow-python3-sources.spec
  tensorflow-sources.file
  tensorflow-sources.spec
  tensorflow-toolfile.spec
  tensorflow.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-rejected

#5114 Move llvm to 8.0.1 as llvm-lite was updated to 0.29
  codechecker-llvm8.patch
  codechecker.spec
  llvm.spec
  pip/py2-llvmlite.file
  py2-dxr-dxrindex-fpic.patch
  py2-dxr-llvm801.patch
  py2-dxr.spec
  py2-llvmlite-fpic-flag.patch
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#5143 [BuildRules] Use c++ to generate precompiled headers
  scram-project-build.file
Labels: comparison-available, externals-approved, fully-signed, orp-pending, requires-external, tests-approved

#5138 Initial commit for the HLS headers
  cmssw-tool-conf.spec
  hls-toolfile.spec
  hls.spec
Labels: comparison-pending, externals-approved, fully-signed, orp-pending, tests-approved

#5139 Updated root to tip of branch v6-18-00-patches
  root.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5140 Updated dd4hep to tip of branch master
  dd4hep.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#5136 Updated root to tip of branch master cxxmodule update
  root.spec
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#5107 Rivet 3.0.1
  herwigpp.spec
  rivet-1.4.0.patch
  rivet-weightnames.patch
  rivet.spec
  thepeg.spec
  yoda.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#5151 revert rivet on gcc820
  herwigpp.spec
  rivet-1.4.0.patch
  rivet.spec
  thepeg.spec
  yoda.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5152 revert rivet update on gcc9
  herwigpp.spec
  rivet-1.4.0.patch
  rivet.spec
  thepeg.spec
  yoda.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5160 Rivet3 gcc820
  herwigpp.spec
  rivet-1.4.0.patch
  rivet.spec
  thepeg.spec
  yoda.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5161 Rivet3 gcc900
  herwigpp.spec
  rivet-1.4.0.patch
  rivet.spec
  thepeg.spec
  yoda.spec
Labels: comparison-pending, externals-approved, fully-signed, orp-pending, tests-approved

#5150 Add mkFit as an external
  mkfit-toolfile.spec
  mkfit.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5164 Add ROOTVecOps and ROOTDataFrame to root-toolfile
  root-toolfile.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5166 Add fastjet-contrib to rivet-toolfile
  rivet-toolfile.spec
Labels: allow-intrepid42, comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5165 Backport 5164 to 10_6
  root-toolfile.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5148 Update MXNet to 1.5.0
  mxnet-predict-toolfile.spec
  mxnet-predict.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5168 [FWLITE] Added py2-six deps for fwlite
  fwlite-tool-conf.spec
  fwlite_python_tools.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5169 Add mkfit to cmssw-tool-conf
  cmssw-tool-conf.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5172 Updated root to tip of branch master for CXXMODULE IB
  root.spec
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#5170 Updated root to tip of branch master
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#5173 Update cuda to 10.1.168 for x86_64
  cuda.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5176 Update tag for RecoBTag-Combined to V01-02-00
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5175 [BuildRule] improve clang-tidy rule
  scram-project-build.file
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5179 [MKFIT] patch mkfit to build on aarch64/ppc64
  mkfit-2.0.0-non-x86_64-fix.patch
  mkfit-toolfile.spec
  mkfit.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#5180 [CXXMODULE] Updated root to tip of branch master
  root.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5146 Move llvm to 8.0.1 as llvm-lite was updated to 0.29
  codechecker-llvm8.patch
  codechecker.spec
  llvm.spec
  pip/py2-llvmlite.file
  py2-dxr-dxrindex-fpic.patch
  py2-dxr-llvm801.patch
  py2-dxr.spec
  py2-llvmlite-fpic-flag.patch
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#5186 Updated root to tip of branch master
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5183 Update xrootd to 4.10.0 (stable)
  xrootd.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved
