Repository cms-sw/cmsdist, pull requests merged in 2019-05, with the labels that each got.

#4919 [GCC 9] Update gcc to 9.1.0
  gcc.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-rejected

#4844 [102X] Update data-RecoBTag-Combined to V01-01-03
  data-RecoBTag-Combined.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#4823 Backporting sherpa2.2.6 and openloops2.0.0 to 102X
  openloops.spec
  sherpa.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#4923 [BuildRules] Run code-format for all included files i.e. icc, i, inc etc.
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#4924 [BuildRules] Code format updated
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#4928 [BuildRules] Improved check-headers rules
  scram-project-build.file
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#4931 [BuildRules] cmssw-config tag V05-08-33
  scram-project-build.file
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#4929 python tool updates
  pip/requirements.txt
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#4821 backporting sherpa2.2.6 and openloops2.0.0 to 71X
  openloops.spec
  sherpa.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#4822 backporting sherpa2.2.6 and openloops2.0.0 to 93X
  openloops.spec
  sherpa.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#4927 upgrade lhapdf sets to 6.2.1d
  lhapdf.spec
  lhapdf_makeLinks.file
  lhapdf_pdfsetsindex.file
Labels: comparison-available, externals-approved, fully-signed, generators-approved, orp-approved, tests-approved

#4933 [LLVM] Update to version 7.1.0
  llvm.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#4912 Update L1Trigger-L1THGCal to V01-00-12
  data/cmsswdata.txt
Labels: comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#4944 [BuildRukes] Bugfix: update cmssw-config tag to V05-08-35
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#4852 Updated root to tip of branch v6-14-00-patches
  root.spec
Labels: comparison-available, dqm-pending, externals-approved, orp-pending, pending-signatures, requires-external, tests-approved

#4946 Update tensorflow 1.13.1 - gcc700next
  bazel.spec
  libjpeg-turbo.spec
  pip/requirements.txt
  protobuf.spec
  py2-tensorflow.spec
  tensorflow-1.6.0-eigen-backports.patch
  tensorflow-1.6.0-eigen-rename-sigmoid.patch
  tensorflow-1.6.0-eigen-update-gemm_pack_lhs.patch
  tensorflow-1.6.0-rename-runtime.patch
  tensorflow-python3-sources.spec
  tensorflow-sources.spec
  tensorflow-toolfile.spec
  tensorflow.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#4935 [ROOT] Update root 6.14
  root.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#4948 Update GCC 9 minor version to 9.1.1
  gcc.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#4934 [data] Updated CalibCalorimetry-EcalTrivialCondModules to tag V00-02-00
  data/cmsswdata.txt
Labels: comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#4953 new Build rules: changes needed for automatic code-format PRs
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#4960 Debug build of tensorflow for debugging infinite loops (devel)
  tensorflow-python3-sources.spec
  tensorflow-sources.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#4952 [10.6.X] Updated root to tip of branch v6-14-00-patches
  root.spec
Labels: backport-ok, comparison-available, externals-pending, orp-approved, pending-signatures, requires-external, tests-rejected

#4937 [data] PhysicsTools-NanoAOD to tag 01-00-04
  data/cmsswdata.txt
Labels: comparison-pending, externals-approved, fully-signed, orp-pending, tests-started

#4971 [BuildRules] Improved build rules for CXXModules IBs
  scram-project-build.file
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#4979 [BuildRules] Fixed quotation for compile_commands.json
  scram-project-build.file
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#4972 [ROOT][6.16] Update root.spec
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#4973 Updated root to tip of branch master
  root.spec
  scram-project-build.file
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#4847 Update gcc-checker-plugin to get Gcc 9 Fixes
  gcc-checker-plugin.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#4963 [Configuration-Generator] Fix auxiliary decay files for long lived chargino
  data/cmsswdata.txt
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#4985 New dasgoclient version
  dasgoclient-binary.spec
  dasgoclient.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#4986 [ROOT 6.14] Updated root to tip of branch v6-14-00-patches
  root.spec
  scram-project-build.file
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#4992 [ROOT][CXXMODULE] update to tip of root master + cxmodule changes
  root.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#4969 [EgammaAnalysis-ElectronTools] Push the 2018 S+S files
  data/cmsswdata.txt
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#4987 [ROOT master] Updated root to tip of branch master
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#4964 [71X][Configuration-Generator] Fix auxiliary decay files for long lived chargino
  data-Configuration-Generator.spec
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#4995 PhysicsTools-NanoAOD: Adding low pt muon MVA weights
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#4965 [Python] Added hepdata lib python package
  pip/py2-astroid.file
  pip/py2-coverage.file
  pip/py2-hepdata-lib.file
  pip/py2-isort.file
  pip/py2-pylint.file
  pip/py2-pytest-cov.file
  pip/py2-pytest.file
  pip/requirements.txt
  py2-lint.spec
  python_tools.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#4753 adding VBFNLO and Hjets++ to the externals linked to Herwig7
  cmssw-tool-conf.spec
  herwigpp.spec
  hjets-toolfile.spec
  hjets.spec
  vbfnlo-toolfile.spec
  vbfnlo.spec
Labels: comparison-available, externals-approved, fully-signed, generators-approved, orp-approved, tests-approved

#4967 [102X][data] PhysicsTools-NanoAOD to tag 01-00-05
  data-PhysicsTools-NanoAOD.spec
Labels: comparison-pending, externals-approved, fully-signed, orp-approved, tests-started

#4999 added CXXModules.mk for CXXModules IBs to build new pcms for selected packages
  CXXModules.mk.file
  cmssw-queue-override.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#4970 [10.2.X][EgammaAnalysis-ElectronTools] Push the 2018 S+S files
  data-EgammaAnalysis-ElectronTools.spec
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#5006 [BuildRules] Updated tag V05-08-51
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#5005 Rivet 2.7.2 and YODA 1.75
  rivet-2.7.0.patch
  rivet.spec
  yoda.spec
Labels: allow-intrepid42, comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#5010 [cms-git-tools] Get default protocol from git config
  cms-git-tools.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5012 [CXXMODULES] Updated build rules and enabled more modules
  CXXModules.mk.file
  cmssw-cxxmodules.patch.file
  cmssw-queue-override.file
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5013 Updated root to tip of branch v6-14-00-patches
  root.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5019 [L1Trigger-L1THGCal] New motherboard mappings and add numbers of links
  data/cmsswdata.txt
Labels: comparison-pending, externals-approved, fully-signed, orp-approved, tests-started
