Repository cms-sw/cmsdist, pull requests merged in 2019-12, with the labels that each got.

#5394 Update CXXModules.mk.file
  CXXModules.mk.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#5353 [5.3.X] backport cms-git-tools changes
  cms-git-tools.spec
  cmspm.file
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5402 [11.1.X][Cuda] drop compute_61 and add compute_35
  cuda-toolfile.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5398 use -mlong-double-64 to avoid link error on ppc64le
  fftjet.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5384 [Vincia] Updates to version 2.3.02 which addresses compiler warnings
  vincia.spec
Labels: comparison-available, externals-approved, fully-signed, generators-approved, orp-approved, tests-approved

#5403 [11.0.X][Cuda] drop compute_61 and add compute_35
  cuda-toolfile.spec
Labels: backport-ok, comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5399 Updated ROOT - rootmaster
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#5407 [LLVM] Add C++11 attribute [[cms::sa_allow]]
  llvm.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5404 Update tag for MagneticField-Interpolation to V01-01-00
  data/cmsswdata.txt
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5319 Updated root to tip of branch v6-14-00-patches
  root.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5405 Update tag for MagneticField-Interpolation to V01-01-00
  data/cmsswdata.txt
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5408 Update tag for MagneticField-Engine to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5416 Fix rootx11 tool file definition
  root-toolfile.spec
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#5414 Updated ROOT cmsdist/rootmaster
  root.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-rejected

#5415 Update ROOT cmsdist/rootmodule
  root.spec
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#5417 Add missing CMSSaAllowAttr case
  llvm.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#5369 backporting sherpa 2.2.8 and openloops 2.1.0 to 93X
  openloops-user.coll.file
  openloops.spec
  sherpa.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5418 Revert to CUDA 10.1 Update 1 (10.1.168), add support for Power
  cmssw-tool-conf.spec
  cuda-toolfile.spec
  cuda.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5356 [CRAB] Added crab client in cmssw distribution stack
  cms-common.spec
  cmssw-tool-conf.spec
  crab-build.file
  crab-dev.spec
  crab-pre.spec
  crab.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5388 openloops 2.1.0 feed in user defined loop process libraries
  openloops-user.coll.file
  openloops.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5421 [Crab] Do not source package env at post time
  crab-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#5422 Update cms-common to include new crab wrapper
  cms-common.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#5426 [crab] Remove crab script from cms-common and add it in cmsdist
  _crab-startup.file
  cjson.py.file
  cms-common.spec
  crab-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#5423 [OpenLoop-2.1.0] synchronize to full lib process from 11_1_X
  openloops-user.coll.file
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5428 Update ROOT - cmsdist/rootnext
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5430 Update ROOT - cmsdist/rootmodule
  root.spec
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#5429 Update ROOT - cmsdist/rootmaster
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5433 Update tag for CalibPPS-ESProducers to V01-01-00
  data/cmsswdata.txt
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5419 Revert to CUDA 10.1 Update 1 (10.1.168), add support for Power (11.0.x backport)
  cmssw-tool-conf.spec
  cuda-toolfile.spec
  cuda.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5431 [OpenLoop-2.1.0] patch up missing lib for 10_2_X
  openloops-user.coll.file
  openloops.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5432 [OpenLoop-2.1.0] patch up missing lib for 10_6_X
  openloops-user.coll.file
  openloops.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5437 Update llvm package def with new commit
  llvm.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#5442 keep cmssw PYTHONPATH saved in CRAB_CMSSW_SITE_PACKAGES
  _crab-startup.file
  crab-dev.spec
  crab-pre.spec
  crab.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5424 [G4] Update geant4 to 4.10.6.0
  clhep.spec
  geant4-G4PhotonEvaporation.spec
  geant4.spec
  vecgeom.spec
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#5436 [OpenLoop-2.1.0] patch up missing lib for 11_0_X
  openloops-user.coll.file
  openloops.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5445 Update llvm.spec with latest commit
  llvm.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#5376 Update DD4Hep
  dd4hep.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved
