Repository cms-sw/cmsdist, pull requests merged in 2020-09, with the labels that each got.

#6205 Updated root to tip of branch master
  root.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#6204 Updated root to tip of branch v6-22-00-patches
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6211 Added annotationManager to cmsmon tools
  cmsmon-tools.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6213 [BuildRules] fix re-build target issues
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#6214 [BuildRule] Fix prebuild target order
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#6209 Revert "Revert "Update to Rivet 3.1.2 and Yoda 1.8.3""
  fastjet-contrib.spec
  fastjet.spec
  rivet-weightnames.patch
  rivet.spec
  yoda.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#6220 [SCRAMV3] Fixes for patch release
  SCRAMV1.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#6215 Updated root to tip of branch v6-20-00-patches
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6216 Updated root to tip of branch master
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6217 Updated root to tip of branch v6-22-00-patches
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6227 Added Lz4 in to cmssw-tool-conf
  cmssw-tool-conf.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6229 [11.0.X] Added Lz4 in to cmssw-tool-conf
  cmssw-tool-conf.spec
Labels: backport-ok, comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#6234 Updated root to tip of branch v6-22-00-patches
  root.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#6236 Updated root to tip of branch master
  root.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#6235 Updated root to tip of branch v6-20-00-patches
  root.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#6237 Update tag for L1Trigger-CSCTriggerPrimitives to V00-02-00
  data/cmsswdata.txt
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#6228 [11.1.X] Added Lz4 in to cmssw-tool-conf
  cmssw-tool-conf.spec
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#6239 updates for SCRAMV3
  SCRAMV1.spec
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#6244 Update tag for Alignment-OfflineValidation to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#6242 [BuildRules] Update build rules
  scram-project-build.file
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6243 Remove page size flag for non intel archs
  jemalloc.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#6245 Update tag for Alignment-OfflineValidation to V00-01-00 (10_6_X)
  cmsswdata.spec
  data/cmsswdata.txt
Labels: comparison-available, externals-pending, orp-approved, pending-signatures, requires-external, tests-approved

#6249 [BuildRules] export dependencies of header only packages too
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#6251 [BuildRules] Allow to use different python to compile package/python
  scram-project-build.file
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6255 Updated root to tip of branch v6-22-00-patches
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6256 Updated root to tip of branch master
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6261 SCRAM V2: Added support for including CMS_PATH/share/override/python
  SCRAMV1.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6259 Update DD4Hep to last commit on master
  dd4hep.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6260 SCRAM V3: Added support for including CMS_PATH/share/override/python
  SCRAMV1.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#6257 Updated root to tip of branch v6-20-00-patches
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6248 added python packages needed by DQM GUI; enabled onnxruntime pycuda for ppc64
  pip/aiohttp.file
  pip/requirements.txt
  pip/yarl.file
  python_tools.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6231 [10.3.X] Added Lz4 in to cmssw-tool-conf
  cmssw-tool-conf.spec
  lz4.spec
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, tests-rejected

#6232 [10.2.X] Added Lz4 in to cmssw-tool-conf
  cmssw-tool-conf.spec
  lz4.spec
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, tests-rejected

#6230 [10.6.X] Added Lz4 in to cmssw-tool-conf
  cmssw-tool-conf.spec
  lz4.spec
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, tests-rejected

#6263 Added new cmssw-wm-tools tool
  cmssw-tool-conf.spec
  cmssw-wm-tools.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#6266 Update tag for Geometry-TestReference to V00-03-00
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-approved, pending-signatures, tests-pending

#6270 Update tag for L1Trigger-L1THGCal to V01-04-00
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-approved, pending-signatures, tests-pending

#6269 bump py2 versions of tools
  pip/requirements.txt
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6274 [DD4Hep] Update to tip of master branch verison 01-14
  dd4hep.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#6277 [SCRAMV3] Fixes scram dev area issue
  SCRAMV1.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#6280 [SCRAMV3] updated to verison V3_00_11
  SCRAMV1.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6282 Update tag for RecoBTag-Combined to V01-07-00
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-approved, pending-signatures, tests-pending

#6267 Update to CUDA 11.1
  cuda.spec
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-rejected

#6279 [BuildRule] Updates scram build rules
  scram-project-build.file
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6283 added cmsLHEtoEOSManager gcc-fixincludes install only deps for cmssw
  cmsLHEtoEOSManager.tmpl
  cmssw-patch-tool-conf.spec
  cmssw-tool-conf.spec
  extras/cmsdist_packages.py
  extras/gen_package.py
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved
