Repository cms-sw/cmsdist, pull requests merged in 2020-12, with the labels that each got.

#6465 Update CMS monitoring tools
  cmsmon-tools.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#6471 [11.3.X]Update CMS monitoring tools
  cmsmon-tools.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#6462 Upgrade Herwig to v7.2.1, and add patch to fix crash when reading lhe…
  FxFxFileReader.patch
  herwigpp.spec
  thepeg.spec
Labels: comparison-available, externals-approved, fully-signed, generators-approved, orp-approved, tests-approved

#6476 Update tag for L1Trigger-CSCTriggerPrimitives to V00-04-00
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-approved, pending-signatures, tests-pending

#6469 [10_2_X] MSAFETY set to 1e-4
  pythia8.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#6470 [9_4_X] MSAFETY set to 1e-4 -
  pythia8.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#6466 Updated root to tip of branch master
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6467 Updated root modules to tip of branch master
  root.spec
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#6480 Update py3-nootbook to version 6.1.5
  pip/requirements.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6488 Updated root module to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6490 Change source for awkward array
  pip/awkward1.file
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6491 [10.6] Update RecoEgamma-ElID tag to V01-01-04
  data/cmsswdata.txt
Labels: externals-pending, orp-approved, pending-signatures, tests-pending

#6500 added missing fwlite packages
  fwlite_build_set.file
Labels: backport-ok, externals-pending, orp-pending, pending-signatures, tests-pending

#6497 use new ServerUtilities from CRABServer
  crab-dev.spec
Labels: externals-approved, fully-signed, orp-pending, tests-rejected

#6503 use lower case tools
  scramv1-tool-conf.file
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#6485 Rivet 3.1.3 and YODA 1.8.5
  rivet-weightnames.patch
  rivet.spec
  yoda.spec
  yoda_pyroot.patch
Labels: allow-intrepid42, externals-approved, fully-signed, orp-approved, tests-started

#6506 update crab-pre to same version as prod and dev. Ol once does not wor…
  crab-pre.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6505 align crab-prod with tatest, tested crab-dev
  crab-prod.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6504 fix libjpeg-turbo toolfile name
  libjpeg-turbo-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6483 Rivet 3.1.3 and YODA 1.8.5 (11_2_X)
  rivet-weightnames.patch
  rivet.spec
  yoda.spec
  yoda_pyroot.patch
Labels: allow-intrepid42, externals-approved, fully-signed, orp-approved, tests-approved

#6508 make crab-pre point to previous tag of crabserver
  crab-pre.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6499 Rename herwigpp tool to herwig7
  cmssw-tool-conf.spec
  herwig7-toolfile.spec
  herwig7.spec
Labels: externals-approved, fully-signed, orp-approved, tests-rejected

#6486 [Geant4] Update vecgeom and clhep version, get geant4 from it's github
  clhep.spec
  geant4-toolfile.spec
  geant4.spec
  vecgeom-fix-for-arm64.patch
  vecgeom.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6512 [Geant4] Update vecgeom and clhep version, get geant4 from it's github
  clhep.spec
  geant4-toolfile.spec
  geant4.spec
  vecgeom-fix-for-arm64.patch
  vecgeom.spec
Labels: backport-ok, externals-pending, orp-pending, pending-signatures, tests-approved

#6443 Add several hep python tools (mostly histograming helpers)
  pip/boost-histogram.file
  pip/hist.file
  pip/histoprint.file
  pip/mplhep.file
  pip/requirements.txt
  python_tools.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#6515 Update tag for RecoTracker-TkSeedGenerator to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, orp-approved, tests-rejected

#6517 Fix source for 11_2 gcc9
  pip/awkward1.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6487 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6519 Update tag for RecoJets-JetProducers to V05-13-00
  data/cmsswdata.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#6520 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6521 Updated root to tip of branch master (modules)
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#6472 Upgrade Herwig to v7.2.1, and add patch to fix crash when reading lhe…
  FxFxFileReader.patch
  herwigpp.spec
  thepeg.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6474 Upgrade Herwig to v7.2.1, and add patch to fix crash when reading lhe…
  FxFxFileReader.patch
  herwigpp.spec
  thepeg.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#6475 Upgrade Herwig to v7.2.1, and add patch to fix crash when reading lhe…
  FxFxFileReader.patch
  herwigpp.spec
  thepeg.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved
