Repository cms-sw/cmsdist, pull requests merged in 2020-04, with the labels that each got.

#5718 [10.6.X] Update MXNet to 1.5.0
  mxnet-predict-toolfile.spec
  mxnet-predict.spec
Labels: backport-ok, comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5713 Fireworks-Geometry: download cmsGeom2026 from cmsrep
  data/cmsswdata.txt
  data/data-Fireworks-Geometry.file
Labels: comparison-notrun, externals-approved, fully-signed, orp-pending, requires-external, tests-approved

#5721 [BuildRules] Fix clang-tidy script to work with LLVM 9.0.1 too
  scram-project-build.file
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5727 Do not allow to link agaisnt PyROOT library
  root-toolfile.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5724 Root master + build py2/py3 version of root dependent packages
  pip/py2-root_pandas.file
  pip/py3-root_pandas.file
  pip/requirements.txt
  pip/root_numpy.file
  pip/root_pandas.file
  pip/rootpy.file
  python_tools.spec
  root-toolfile.spec
  root.spec
  yoda-toolfile.spec
  yoda.spec
  yoda_pyroot.patch
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#5705 [GCC 9.3] Update gcc on branch 9
  OpenBLAS.spec
  bison.spec
  cmake.spec
  elfutils.spec
  gcc.spec
  gmake.spec
  gmp-static.spec
  gmp.spec
  libxml2.spec
  lz4.spec
  zstd.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#5717 [10.6.X] apply RecoBTag-Combined=V01-03-00 for 106X
  data/cmsswdata.txt
Labels: comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#5690 [11.0.X][FrontierClient] Update to verison 2.9.1
  frontier_client.spec
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5723 [ROOT 620 ] Updated root to tip of branch v6-20-00-patches
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5722 Drop rootpy external from CMS software stack
  python_tools.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5719 [10.2.X][RecoBTag-Combined]DNN models for the ParticleNet tagger
  data-RecoBTag-Combined.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, requires-external, tests-approved

#5707 [10.2.X][FrontierClient] Update to verison 2.9.1
  frontier_client.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5689 [10.6.X][FrontierClient] Update to verison 2.9.1
  frontier_client.spec
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5688 [9.4.X][FrontierClient] Update to verison 2.9.1
  frontier_client.spec
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5687 [9.3.X][FrontierClient] Update to verison 2.9.1
  frontier_client.spec
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5686 [8.0.X][FrontierClient] Update to verison 2.9.1
  frontier_client.spec
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5684 [7.1.X][FrontierClient] Update to verison 2.9.1
  frontier_client.spec
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5683 [5.3.X][FrontierClient] Update to verison 2.9.1
  frontier_client.spec
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5729 Update bleach pip packge 3.1.4 (github security alert)
  pip/requirements.txt
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5734 Include Eigne include directory in ROOT_INCLUDE_PATH
  eigen-toolfile.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#5736 New dasgoclient version
  dasgoclient-binary.spec
  dasgoclient.spec
Labels: comparison-pending, externals-approved, fully-signed, orp-pending, tests-approved

#5737 crab-dev to CRAB Client 3.3.2004.rc3
  crab-dev.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5741 Update tag for L1Trigger-L1THGCal to V01-01-00
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5728 [11.0.X] Fireworks-Geometry: New 2021/26 Geometries
  data/cmsswdata.txt
  data/data-Fireworks-Geometry.file
Labels: backport-ok, comparison-notrun, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#5739 CRAB Client Apr 2020 version in dev and pre
  crab-dev.spec
  crab-pre.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#5742 Remove Dataformats/RPCDigi for C++ modules
  CXXModules.mk.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5732 [Geant4]Update geant4 10.6.1
  clhep.spec
  geant4-G4ABLA.spec
  geant4-G4EMLOW.spec
  geant4-G4INCL.spec
  geant4-G4NDL.spec
  geant4-G4NEUTRONXS.spec
  geant4-G4PARTICLEXS.spec
  geant4-G4PhotonEvaporation.spec
  geant4-G4RadioactiveDecay.spec
  geant4-G4RealSurface.spec
  geant4-G4SAIDDATA.spec
  geant4-toolfile.spec
  geant4.spec
  geant4data.spec
  vecgeom-fix-for-arm64.patch
  vecgeom-toolfile.spec
  vecgeom.spec
Labels: comparison-available, externals-pending, orp-approved, pending-signatures, requires-external, tests-approved

#5746 updated vecgeom patch for arm64: remove mm_free from test
  vecgeom-fix-for-arm64.patch
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#5756 Added common_revision_script helper macro
  crab.spec
  rpm-preamble.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#5759 Updated BuildRules tag to fix cuda compilation
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-rejected

#5762 [ROOT master] Get latest from master
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#5764 [ROOT 6-20] Get latest commits
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5763 [ROOT modules] Get latest from master
  root.spec
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#5766 Enable pyroot_experimental for CXXMODULES IB
  root.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5765 Upgrade Herwig7 from 7.1.4 to 7.2.0
  herwigpp.spec
  thepeg.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#5771 Update crab-dev
  crab-dev.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#5750 cms monitoring tools spec
  cmsmon-tools.spec
  go.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5749 Update upstream repositories for Alpaka and Cupla
  alpaka.spec
  cupla.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5772 Added cmsmon-tools dependency to distribute cmsmon tools
  cmssw-tool-conf.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#5775 Upgrade Herwig 7.1.4 to Herwig 7.2.0
  herwigpp.spec
  thepeg.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#5774 Upgrade Herwig 7.1.4 to Herwig 7.2.0
  herwigpp.spec
  thepeg.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#5773 Upgrade Herwig7 from 7.1.4 to 7.2.0
  herwigpp.spec
  thepeg.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#5777 [ROOT master] Get latest commits
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5780 Crab Client 2004 from pre to prod
  crab-prod.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5783 [Go] Update sources for other archs
  go.spec
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#5743 [ONNX runtime] Update for powerpc
  cmssw-tool-conf.spec
  eigen-altivec-fix.patch
  eigen.spec
  onnxruntime.spec
  pip/onnx.file
  protobuf.spec
  py2-onnx.patch
Labels: comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#5708 [LLVM 10] Update LLVM to 10
  codechecker.spec
  llvm.spec
  pip/llvmlite.file
  pip/numba.file
  pip/oamap.file
  pip/py3-numba.file
  pip/requirements.txt
  py2-dxr-llvm10.patch
  py2-dxr.spec
  py2-llvmlite-llvm9.patch
  py2-oamap-Const2Literal.patch
  py3-numba-llvm33.patch
  python_tools.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-rejected

#5787 [ROOT 620] Get latest commits
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5785 [ROOT master] Get latest commits
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5786 [ROOT modules] Get latest commits
  root.spec
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#5791 [CXXMODULE] Update root to tip of master branch
  root.spec
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#5792 [ROOT6] Update root to tip of master branch
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5790 [DD4Hep] Get latest commits from master
  dd4hep.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved
