Repository cms-sw/cmsdist, pull requests merged in 2020-08, with the labels that each got.

#6124 keep only CastorShowerLibrary_CMSSW500_Standard library
  data/cmsswdata.txt
  data/data-SimG4CMS-Forward.file
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6125 buildrules: another perl script converted to shell
  scram-project-build.file
Labels: comparison-pending, externals-approved, fully-signed, orp-pending, tests-rejected

#6134 SCRAM: use correct basedirectory to switch scram versions
  SCRAMV1.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6136 New buildrules which should work with SCRAM V2 and V3
  scram-project-build.file
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#6135 [10.6] Include libunwind-toolfile
  cmssw-tool-conf.spec
  libunwind-toolfile.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#6137 Update tag for RecoJets-JetProducers to V05-12-00 (backport of #6104)
  data/cmsswdata.txt
Labels: comparison-available, externals-pending, orp-approved, pending-signatures, requires-external, tests-approved

#6138 vulnerabilities found in existing pillow version
  pip/bokeh.file
  pip/py3-pillow.file
  pip/requirements.txt
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6128 Parallel support for HDF5
  hdf5.spec
  pip/h5py.file
  pip/tables.file
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6129 Add check to see that cms-handle code-formatter is linked into clang-tidy and run the unit tests on clang-tools-extra.
  llvm.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#6142 [ROOT] root master
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6140 [ROOT] v6-22-00-patches
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6141 [ROOT] v6-20-00-patches
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6145 Add Niels Lohmann's JSON for Modern C++ header-only library
  cmssw-tool-conf.spec
  json-toolfile.spec
  json.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6143 [ROOT] root cxx modules
  clhep-toolfile.spec
  root.spec
  scram-project-build.file
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#6146 move latest CrabClient to production and test new build in dev
  crab-dev.spec
  crab-pre.spec
  crab-prod.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6150 Update tag for L1Trigger-TrackFindingTMTT to V00-02-00
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-approved, pending-signatures, tests-pending

#6149 update cms common revision to 1210
  cms-common.spec
Labels: comparison-pending, externals-approved, fully-signed, orp-pending, tests-approved

#6144 [LLVM] Remove static libs
  llvm.spec
  py2-dxr-llvm-shared.patch
  py2-dxr.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-rejected

#6147 Update openmpi to 4.0.4
  openmpi.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-rejected

#6154 Update cms-common.spec
  cms-common.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#6120 Update to CUDA 11.0.2 (11.0.207)
  alpaka.spec
  cuda.spec
  cupla.spec
Labels: comparison-pending, externals-approved, fully-signed, orp-pending, tests-rejected

#6156 Update tag for RecoBTag-Combined to V01-06-00
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-approved, pending-signatures, tests-pending

#6155 update scram: avoid recursively changes version between v2 and v3
  SCRAMV1.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#6157 Update cmssw-osenv.spec
  cmssw-osenv.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#6153 [10.6] Update tag for PhysicsTools-NanoAOD to V01-01-00
  data/cmsswdata.txt
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#6159 update cmsswdata to RecoBTag-Combined to V01-06-00
  data/cmsswdata.txt
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#6158 Update igprof.spec
  igprof.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6160 HDF5 toolfile cleanup and added openmpi deps
  hdf5-toolfile.spec
  hdf5.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#6161 Update to CUDA 11.0 Update 1, and update the list of supported architectures
  cuda-flags.file
  cuda.spec
Labels: comparison-available, externals-pending, orp-approved, pending-signatures, tests-started

#6148 Update DD4Hep to latest on master
  dd4hep.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6165 [ROOT] Updated root to tip of branch v6-20-00-patches
  root.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#6164 [ROOT] Updated root to tip of branch master
  root.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#6163 [ROOT] Updated root to tip of branch v6-22-00-patches
  root.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#6166 Add py2-opt-einsum to python_tools
  python_tools.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#6168 incorportate latest fixes,in particular the one for missing py2-future
  crab-prod.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6167 roll back to PREvious CRAB client version.
  crab-pre.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6119 Add awkward1 and uproot4 to python tools
  pip/awkward1.file
  pip/requirements.txt
  pip/uproot4.file
  python_tools.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6162 test latest crab client
  crab-dev.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#6169 Bump davix to 076
  davix.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6170 move forward to 0812 tag to fix httplib import
  crab-pre.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#6173 [ROOT] Update root 6-20
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6172 [ROOT] Update ROOT6 (master)
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6174 [ROOT] Update ROOT622
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6177 Update xrootd to 4.12.3
  pip/requirements.txt
  xrootd.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#6180 Update tag for RecoEgamma-ElectronIdentification to V01-02-00
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-approved, pending-signatures, tests-pending

#6183 Update xrdpyfs ROOT622
  pip/requirements.txt
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6182 Update xrootdpyfs for ROOT6 branch
  pip/requirements.txt
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6184 [CC8] XrootD add skipped flag
  xrootd.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-rejected

#6179 Test latest CRAB Client tag
  crab-dev.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6181 [DD4Hep] Add additional flag to bring missing functions
  dd4hep.spec
  tbb.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#6195 update build rules: Only auto generate lcgdict for package/src dirs
  scram-project-build.file
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6194 [10_2_X] enabling Sherpa2ShortHepMC in sherpa
  sherpa-2.2.10-hepmcshort.patch
  sherpa.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#6193 [11_2_X] enabling Sherpa2ShortHepMC in sherpa
  sherpa-2.2.10-hepmcshort.patch
  sherpa.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#6187 python3 pip package updates
  pip/argon2-cffi.file
  pip/jupyter_client.file
  pip/matplotlib.file
  pip/nbconvert.file
  pip/nbformat.file
  pip/notebook.file
  pip/pandas.file
  pip/py3-ipykernel.file
  pip/py3-matplotlib.file
  pip/requirements.txt
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#6198 Update tag for Geometry-DTGeometryBuilder to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: comparison-pending, externals-approved, fully-signed, orp-pending, tests-pending

#6196 [10_6_X Prod] Enabling Sherpa2ShortHepMC in sherpa
  sherpa-2.2.10-hepmcshort.patch
  sherpa.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#6200 updated pip packages to fix build errors on aarch64
  pip/requirements.txt
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#6199 [GCC10] add xrootdpyfs after root
  python_tools.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#6201 BuildRules: Included biblib path in to CLING_PREBUILT_MODULE_PATH env
  scram-project-build.file
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved
