Repository cms-sw/cmsdist, pull requests merged in 2020-06, with the labels that each got.

#5853 Extend jmalloc to monitor the peak memory usage of each thread (11.1.x)
  jemalloc.spec
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5861 test new CRAB tag naming scheme
  crab-build.file
  crab-dev.spec
  crab-pre.spec
  crab-prod.spec
  crab.spec
Labels: comparison-pending, externals-approved, fully-signed, orp-approved, tests-approved

#5889 [Geant4] Update to verion new patched version 10.6.2
  geant4.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#5898 Patch frontier_client for gcc10
  frontier_client-2.8.20-add-python-dbapi.patch
  frontier_client.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5886 Drop mcdb and libhepml tools
  cmssw-tool-conf.spec
  libhepml-0.2.1-gcc43.patch
  libhepml-0.2.1-leopard.patch
  libhepml-toolfile.spec
  libhepml.spec
  mcdb-toolfile.spec
  mcdb.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#5901 remove cmssw/bin/arch from PYTHONPATH
  cmssw-toolfile.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5899 [GCC10] fix mxnet and update to 1.6.0 tag
  mxnet-predict.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5904 use python based findDependencies
  findDependencies.pl.file
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#5907 update gdb to version 9.2
  gdb.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5908 update gdb and build it with python for PY3 IBs
  gdb.spec
Labels: comparison-pending, externals-approved, fully-signed, orp-pending, tests-approved

#5906 [ROOT 6-22] Get 6-22 branch for root next
  pip/requirements.txt
  pip/root_numpy.file
  pip/root_pandas.file
  pip/rootpy.file
  python_tools.spec
  root.spec
  yoda-toolfile.spec
  yoda.spec
  yoda_pyroot.patch
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-rejected

#5911 added gdb-9.2 patch for PYTHONHOME
  gdb-7.11-set-autoconf-version.patch
  gdb-8.1-fix-PYTHONHOME.patch
  gdb.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5895 [ROOT] get latest commits from master
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#5913 [CXXMODULE] Build rules updated
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5915 [GCC10] change triton flag
  triton-inference-server.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5914 [ROOT master] Fixing commit is merged + few more
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5918 Added hey tool with x509 support
  cmsmon-tools.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#5919 [CRAB] By default make crab complete to use crab-prob
  crab-build.file
  crab-dev.spec
  crab-pre.spec
  crab-prod.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#5920 fix tinyxml2 pcm and add the type_trait boost pcm
  pcm_util.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5921 [80X] source file env so that magic file path is set
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5922 [BuildRule] Make sure the compiler output goes to a log file
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5923 Update tag for L1Trigger-TrackFindingTMTT to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5924 Update tag for L1Trigger-TrackFindingTracklet to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5928 Update cmssw-ccX script which now prefer unpacked.cern.ch over cms-ib repo
  cmssw-osenv.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5925 [10.6] Update cmake protobuf and igprof
  cmake.spec
  igprof.spec
  pip/requirements.txt
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#5869 upgrade pythia8 to 302
  cmssw-tool-conf.spec
  pythia8.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#5932 Enable more modules (modules IB only)
  CXXModules.mk.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5931 Update cms git tools
  cms-git-tools.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5933 [BuildRules] Support using -isystem instead of -I for system tools
  scram-project-build.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#5935 Update to CUDA 11.0 RC (11.0.182)
  cuda-flags.file
  cuda-toolfile.spec
  cuda.spec
  cupla.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5941 use latest CRABServer
  crab-dev.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#5943 Drop the "cub" external library
  cmssw-tool-conf.spec
  cub-toolfile.spec
  cub.spec
Labels: comparison-pending, externals-approved, fully-signed, orp-pending, tests-approved

#5936 Update to CUDA 11.0 RC (11.0.182) [11.1.x]
  cuda-flags.file
  cuda-toolfile.spec
  cuda.spec
  cupla.spec
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5947 Update crab client
  crab-pre.spec
  crab-prod.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#5946 [ROOT 6-22] Test the changes up to tag 6-22
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5944 Drop the "cub" external library (11.1.x)
  cmssw-tool-conf.spec
  cub-toolfile.spec
  cub.spec
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5942 [11.1.X] Update root version to 6.20
  root.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5955 FWLite: Added zstd dependency due to root update
  fwlite-tool-conf.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5903 Build boost with python3 for PY3 IBs
  boost-toolfile.spec
  boost.spec
Labels: comparison-pending, externals-approved, fully-signed, orp-approved, requires-external, tests-rejected

#5953 [11.2 ROOT 622] Get commits after the tag
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5940 upgrade lhapdf to 6.2.3 and sets to 6.2.3c
  lhapdf.spec
  lhapdf_makeLinks.file
  lhapdf_pdfsetsindex.file
Labels: comparison-available, externals-approved, fully-signed, generators-approved, orp-pending, tests-approved

#5956 [ROOT] Updated root 6.20 for master IBs
  fwlite-tool-conf.spec
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5954 DD4Hep - Get latest commits
  dd4hep.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5951 [11.1.X] Update root to tagged version 6.20.06
  root.spec
Labels: comparison-available, externals-approved, fully-signed, orp-pending, tests-approved

#5949 [10.6] Include latest changes from 240 branch
  pythia8.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5960 New dasgoclient version
  dasgoclient-binary.spec
  dasgoclient.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5961 TBB 2020 - get latest version and add cmake config
  tbb.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5962 [10.6] Remove dependency
  igprof.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#5969 Update tag for DQM-SiStripMonitorClient to V01-01-00
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5970 New verison of monit tool which cover annotations
  cmsmon-tools.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5975 [GCC] Treat unused-label warning as error
  gcc-toolfile.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#5977 [ROOT 6-22] Get latest commits
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#5976 [ROOT master] Get latest commits
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#5982 Update tag for L1Trigger-L1THGCal to V01-02-00
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-approved, pending-signatures, tests-pending

#5981 git tools: Rewrite cms-checkdeps in python instead of perl
  cms-git-tools.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#5985 enable cxxmodules fwcore packages
  cmssw-queue-override.file
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#5979 [10.6.x][pythia8] BeamRemnants update for LHE events in 240
  pythia8.spec
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5986 [CXXMODULE] build cxxmodules for FWCore/Framework FWCore/ParameterSet
  cmssw-queue-override.file
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#5978 [ROOT modules] Get latest from master
  root.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5988 Update tag for SimTransport-PPSProtonTransport to V00-02-00
  data/cmsswdata.txt
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5896 [Jemalloc] Track the peak memory used by each thread
  jemalloc.spec
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#5993 [BuildRules] Fixed build rules to not delete the build logs
  scram-project-build.file
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#5995 New version of monit tool; add stern into set of tools
  cmsmon-tools.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5984 Enable FastSimDataFormats modules
  CXXModules.mk.file
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, tests-rejected

#6004 Update tag for L1Trigger-L1TCalorimeter to V01-01-00
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#5996 Add HighFive to externals
  cmssw-tool-conf.spec
  highfive-toolfile.spec
  highfive.spec
  highfive/doc.txt
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-started

#5991 [11.1.X] update L1Trigger-L1THGCal V01-02-00
  data/cmsswdata.txt
Labels: backport-ok, comparison-available, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#5998 [ROOT] Next - tip of branch v6-22-00-patches
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5997 [ROOT] cmsdist master - tip of branch v6-20-00-patches
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#5973 Add Alignment* modules
  CXXModules.mk.file
Labels: comparison-notrun, externals-pending, orp-pending, pending-signatures, requires-external, tests-rejected

#6005 [ROOT][6.20][GCC10] enable root PCM
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-rejected

#5999 [ROOT] tip of ROOT branch master
  root.spec
Labels: comparison-available, externals-pending, orp-pending, pending-signatures, tests-approved

#6006 Revert "Add Alignment* modules"
  CXXModules.mk.file
Labels: comparison-pending, externals-pending, orp-pending, pending-signatures, tests-pending

#6009 Update tag for L1Trigger-DTTriggerPhase2 to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: comparison-pending, externals-pending, orp-approved, pending-signatures, tests-pending

#6001 [10.2.X] Upgrade lhapdf sets from 6.2.1a_1 to 6.2.1a_2, adding CT18*
  lhapdf.spec
  lhapdf_makeLinks.file
  lhapdf_pdfsetsindex.file
Labels: comparison-available, externals-approved, fully-signed, orp-approved, tests-approved

#5897 [11.1.X][Jemalloc] Track the peak memory used by each thread
  jemalloc.spec
Labels: comparison-available, externals-pending, orp-approved, pending-signatures, tests-approved
