Repository cms-sw/cmsdist, pull requests merged in 2021-05, with the labels that each got.

#6852 Keep the PTX in CUDA binaries, so it can be JIT'ted for newer devices (11.3.x)
  cuda-flags.file
Labels: backport-ok, externals-approved, fully-signed, orp-approved, tests-approved

#6861 [BuildRules] LCGDict rules fixed for CXXMODULE IBs
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6829 Upgrade Herwigpp to Herwig 7.2, in 9_4_X
  LesHouchesFileReader.patch
  cmssw-tool-conf.spec
  form-toolfile.spec
  form.spec
  gosam-toolfile.spec
  gosam.spec
  gosamcontrib-toolfile.spec
  gosamcontrib.spec
  herwig7-toolfile.spec
  herwig7.spec
  herwigpp-toolfile.spec
  herwigpp.spec
  madgraph5amcatnlo-compile.patch
  madgraph5amcatnlo-config.patch
  madgraph5amcatnlo-toolfile.spec
  madgraph5amcatnlo.spec
  openloops-user.coll.file
  qgraf-toolfile.spec
  qgraf.spec
  scons.spec
  thepeg-toolfile.spec
  thepeg.spec
Labels: externals-approved, fully-signed, orp-pending, requires-external, tests-approved

#6864 [SCRAM] Fixes for recursive scram build
  SCRAMV1.spec
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6868 [SCRAMV3] Fix for create dev area of AFS
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6871 Update tag for GeneratorInterface-EvtGenInterface to V02-04-00
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, orp-approved, tests-started

#6867 Igprof patch for TBB resumable tasks
  igprof.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#6870 Update tag for RecoEgamma-ElectronIdentification to V01-05-00
  data/cmsswdata.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6792 Update TBB to 2021.2.0 and use cmake to build
  tbb-toolfile.spec
  tbb.spec
Labels: externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#6857 ROOT master - remove a commit to fix failure
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6865 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6848 drop high-level python2 tools
  pip/downhill.file
  pip/histoprint.file
  pip/law.file
  pip/luigi.file
  pip/mpld3.file
  pip/poetry.file
  pip/pycuda.file
  pip/python-daemon.file
  pip/rep.file
  pip/requirements.txt
  pip/root_pandas.file
  pip/rootpy.file
  pip/seaborn.file
  pip/sympy.file
  pip/tensorflow.file
  pip/theanets.file
  pip/uproot.file
  pip/uproot4.file
  pip/virtualenvwrapper.file
  professor.spec
  professor2.spec
  python_tools.spec
  tensorflow-requires.file
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6874 [SCRAM] Fix scram build -j without N option bug
  SCRAMV1.spec
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6866 ROOT 6-22 - get one commit
  root.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6873 Add libunwind dependency on zlib.
  libunwind.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6877 [SCRAM] Protect against failure when run in container
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6876 [10.6.X] Update of GeneratorInterface-EvtGenInterface tag in cmsswdata.txt
  data/cmsswdata.txt
Labels: backport-ok, externals-approved, fully-signed, orp-approved, tests-approved

#6879 update CrabClient-dev
  crab-dev.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6834 GCC 10 is supported by CUDA 11.x
  cuda-flags.file
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6872 Update tag for L1Trigger-CSCTriggerPrimitives to V00-06-00
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#6886 Specify libdir for libunwind
  libunwind.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6885 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6881 Update tag for RecoBTag-Combined to V01-07-01-01-00
  data/cmsswdata.txt
Labels: allow-jpata, externals-approved, fully-signed, orp-approved, tests-approved

#6895 Revert "Build ROOT and DD4Hep in debug mode"
  dd4hep.spec
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#6891 Updated root to tip of branch v6-22-00-patches
  root.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6889 Update tag for RecoEgamma-ElectronIdentification to V01-01-04-01-00
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#6904 Update tag for L1Trigger-CSCTriggerPrimitives to V00-08-00
  data/cmsswdata.txt
Labels: externals-pending, orp-approved, pending-signatures, tests-pending

#6896 Remove root_numpy and root_pandas on cmsdist master
  pip/py2-root_pandas.file
  pip/py3-root_pandas.file
  pip/requirements.txt
  pip/root_numpy.file
  pip/root_pandas.file
  python_tools.spec
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#6882 Update cmssw-wm-tools.spec
  cmssw-wm-tools.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#6902 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#6903 Update tag for L1Trigger-DTTriggerPhase2 to V00-02-00
  data/cmsswdata.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#6906 libunwind - rename lib64 to lib if exists
  libunwind.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6908 Patch the configure.ac of libunwind
  libunwind-fix-comma.patch
  libunwind.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6909 Update tag for Geometry-TestReference to V00-07-00
  data/cmsswdata.txt
Labels: externals-pending, orp-approved, pending-signatures, tests-pending

#6910 Enable libunwind-toolfile and rebuild the external
  cmssw-tool-conf.spec
  libunwind.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6911 Revert "Remove root_numpy and root_pandas on cmsdist master"
  pip/py2-root_pandas.file
  pip/py3-root_pandas.file
  pip/requirements.txt
  pip/root_numpy.file
  pip/root_pandas.file
  python_tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6912 Remove rootnumpy for ROOT master
  pip/py2-root_pandas.file
  pip/py3-root_pandas.file
  pip/requirements.txt
  pip/root_numpy.file
  pip/root_pandas.file
  python_tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#6914 Updated root to tip of branch v6-22-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6915 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6916 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6918 Update utm to 0.8.2
  utm.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6878 drop high-level python2 tools
  pip/downhill.file
  pip/histoprint.file
  pip/law.file
  pip/luigi.file
  pip/mpld3.file
  pip/poetry.file
  pip/pycuda.file
  pip/python-daemon.file
  pip/rep.file
  pip/requirements.txt
  pip/root_pandas.file
  pip/rootpy.file
  pip/seaborn.file
  pip/sympy.file
  pip/tensorflow.file
  pip/theanets.file
  pip/uproot.file
  pip/uproot4.file
  pip/virtualenvwrapper.file
  professor.spec
  professor2.spec
  python_tools.spec
  tensorflow-requires.file
Labels: backport-ok, externals-approved, fully-signed, orp-pending, tests-approved

#6924 [cms-git-tools] Fix for checkdeps to properly checkout all required packs
  cms-git-tools.spec
Labels: externals-approved, fully-signed, orp-pending, tests-started

#6920 Update tag for Geometry-TestReference to V00-08-00
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, orp-pending, tests-pending

#6921 [backport] Update cms-data Geometry/TestReference to V00-08-00
  data/cmsswdata.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#6927 Revert "[backport] Update cms-data Geometry/TestReference to V00-08-00"
  data/cmsswdata.txt
Labels: externals-pending, orp-approved, pending-signatures, tests-pending

#6930 DXR needs py2-parsimonious to run
  pip/requirements.txt
  py2-dxr.spec
  python_tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6934 Update tag for L1Trigger-L1THGCal to V01-05-00
  data/cmsswdata.txt
Labels: externals-pending, orp-approved, pending-signatures, tests-pending

#6928 [backport] Update cms-data Geometry/TestReference to V00-08-00
  data/cmsswdata.txt
Labels: externals-pending, orp-approved, pending-signatures, tests-pending

#6937 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6935 update crab-pre to v3.210323
  crab-pre.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6940 Update tag for L1Trigger-L1TMuon to V01-05-00
  data/cmsswdata.txt
Labels: externals-pending, orp-approved, pending-signatures, tests-pending

#6941 update crab-prod to v3.210505 from crab-dev
  crab-prod.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6942 test crab-dev with latest crabserver
  crab-dev.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6947 Remove py2-sympy from professor2 toolfile
  professor2-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6936 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-rejected

#6797 drop openssl and use it from system
  autotools.spec
  bazel-0.29.1-patches.patch
  blackhat.spec
  cmssw-tool-conf.spec
  coral-tool-conf.spec
  curl.spec
  davix-toolfile.spec
  davix.spec
  frontier_client-toolfile.spec
  frontier_client.spec
  fwlite-tool-conf.spec
  git.spec
  glibc-toolfile.spec
  glibc.spec
  openldap-toolfile.spec
  openldap.spec
  openssl-1.0.2d-disable-install-openssldir.patch
  openssl-1.0.2d-pr3979.patch
  openssl-toolfile.spec
  openssl.spec
  pip/cryptography.file
  pip/pycurl.file
  pip/python-ldap.file
  python.spec
  python3.spec
  root.spec
  scram-project-build.file
  sherpa.spec
  systemtools.spec
  triton-inference-server.spec
  xrootd.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6938 Update tag for PhysicsTools-PatUtils to V00-03-00
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#6945 New dasgoclient version
  dasgoclient-binary.spec
  dasgoclient.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6950 Update cmssw-wm-tools.spec with fix to Tier0 interface
  cmssw-wm-tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6951 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: externals-approved, fully-signed, orp-pending, tests-rejected

#6952 Updated root to tip of branch master
  root.spec
Labels: externals-approved, fully-signed, orp-pending, tests-rejected
