Repository cms-sw/cmsdist, pull requests merged in 2021-04, with the labels that each got.

#6780 Update tag for GeneratorInterface-EvtGenInterface to V02-02-00
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#6782 [SCRAMV3] USe default target/micro-arch during build
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6781 [BuildRules] Fixes for multi-target releases
  SCRAMV1.spec
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6773 [11.2.X] Update tag for L1Trigger-L1TMuon to V01-04-00
  data/cmsswdata.txt
Labels: backport-ok, externals-pending, orp-approved, pending-signatures, requires-external, tests-approved

#6785 [BuildRules] Fix multi-targets symlinks
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6786 [Rivet] build rivet for multi-targets
  rivet-toolfile.spec
  rivet.spec
  vectorization/cmsdist_packages.py
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6789 Set SCRAM_TARGET=auto for skylakeavx512 builds
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#6791 [BuildRules] updates Intel micro-arch maps for skylakeavx512 builds
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6794 CRABClient needs old WMCore to run on CMSSW_9_ or older
  crab-dev.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6793 LLVM - Don't flag EventSetupRecord::get calls if first argument is of type ESGetToken
  llvm.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6790 Updated root to tip of branch v6-22-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6783 [DD4Hep] Try latest version v01-16-01 which is needed by root 6.24 and root master
  dd4hep.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6800 [10.6] update EgammaAnalysis-ElectronTools to V00-03-01
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6798 Update crab client: Move prod to v3.210323 (like dev) and pre to v3.210127 (old prod)
  crab-pre.spec
  crab-prod.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6796 [BuildRules] Drop rootdict rule for LinkDep.h files
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-rejected

#6776 Add GPU support for ONNXRuntime
  cmssw-tool-conf.spec
  cudnn-toolfile.spec
  cudnn.spec
  onnxruntime-toolfile.spec
  onnxruntime.spec
Labels: allow-hqucms, externals-approved, fully-signed, orp-approved, tests-approved

#6795 Disable a warning message when using Eigen in CUDA code
  eigen-toolfile.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6802 Test onnxruntime 1.7.2 integration
  onnxruntime.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6805 Update tag for Geometry-TestReference to V00-05-00
  data/cmsswdata.txt
Labels: externals-pending, orp-approved, pending-signatures, tests-pending

#6804 New dasgoclient version
  dasgoclient-binary.spec
  dasgoclient.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6808 Update tag for L1Trigger-CSCTriggerPrimitives to V00-05-00
  data/cmsswdata.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#6807 Update tag for GeneratorInterface-EvtGenInterface to V02-03-00
  data/cmsswdata.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#6809 Update GeneratorInterface-EvtGenInterface to V02-03-00
  data/cmsswdata.txt
Labels: externals-pending, orp-approved, pending-signatures, tests-approved

#6815 onnxruntime - get updates for Arm
  onnxruntime.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6816 [DD4Hep] Change DD4Hep for special IB
  dd4hep.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#6770 Updated Pygments to 2.7.4
  pip/conan.file
  pip/hyperas.file
  pip/ipykernel.file
  pip/ipython.file
  pip/ipywidgets.file
  pip/jupyter.file
  pip/jupyter_client.file
  pip/jupyter_console.file
  pip/nbconvert.file
  pip/nbdime.file
  pip/nbformat.file
  pip/notebook.file
  pip/qtconsole.file
  pip/rep.file
  pip/requirements.txt
  pip/widgetsnbextension.file
  python_tools.spec
Labels: externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#6820 Update tag for Geometry-TestReference to V00-06-00
  data/cmsswdata.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#6818 onnxruntime - get latest Arm fix
  onnxruntime.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6735 [XRootd] Update to version 5.1.1
  xrootd-toolfile.spec
  xrootd.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#6825 Openloops - remove a process
  openloops-user.coll.file
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#6826 DD4Hep - get latest on master
  dd4hep.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6827 DD4Hep - get latest on master 11.3
  dd4hep.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6821 New dasgoclient version
  dasgoclient-binary.spec
  dasgoclient.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6828 Revert "[XRootd] Update to version 5.1.1"
  xrootd-toolfile.spec
  xrootd.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#6810 ROOT - get latest commits from 6.22
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#6830 Coral - Fix for limiting idle connection pool size
  coral.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6822 Rivet 3.1.4, YODA 1.9.0, Professor 2.3.2
  professor2.spec
  rivet-140-313.patch
  rivet.spec
  yoda.spec
Labels: allow-mseidel42, externals-approved, fully-signed, orp-pending, tests-approved

#6787 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: externals-approved, fully-signed, orp-pending, tests-started

#6835 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6832 move crab-dev to v3.210422
  crab-dev.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6838 Update professor2 patch for PPC
  professor2-ppc64-flag-change.patch
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6839 [11.1.X] Remove crab dependency
  cmssw-tool-conf.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6845 build py2-Pygments which is needed by dxr; treat .icc as cpp files
  Pygments-cpp-extension-fix.patch
  pip/Pygments.file
  pip/requirements.txt
  py2-dxr.patch
  python_tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6847 [CC8] Update SCRAM V3
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#6843 Update MillePede to version V04-09-01
  millepede.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6842 ROOT 6-24 - get latest commits
  root.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6788 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#6853 Update tag for RecoEgamma-PhotonIdentification to V01-01-00
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6855 Enable DYNAMIC_CPU_ARCH in ONNXRuntime to use up to AVX2
  onnxruntime-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, reconstruction-approved, tests-approved

#6854 Profiling tools update.
  gperftools-toolfile.spec
  gperftools.spec
  igprof.spec
  libunwind.spec
Labels: externals-approved, fully-signed, orp-pending, requires-external, tests-approved

#6844 Update tag for RecoBTag-Combined to V01-11-00
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#6849 Update SCRAM V3
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#6851 Keep the PTX in CUDA binaries, so it can be JIT'ted for newer devices
  cuda-flags.file
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6860 [SCRAMV3] Fix for scram tool info
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected
