Repository cms-sw/cmsdist, pull requests merged in 2021-06, with the labels that each got.

#6954 [BuildRules] Fix the issue with scram b after adding an extra package
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#6949 Fix for EvtGen with Pythia8 >= 304
  evtgen-2.0.0.patch
  evtgen.spec
Labels: externals-approved, generators-pending, orp-pending, pending-signatures, tests-approved

#6953 Update tag for PhysicsTools-PatUtils to V00-03-00
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#6957 update crabclient dev and prod to v3.210601
  crab-dev.spec
  crab-prod.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6960 Update tag for RecoEgamma-ElectronIdentification to V01-06-00
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, orp-pending, tests-started

#6961 Update tag for RecoJets-JetProducers to V05-14-00
  data/cmsswdata.txt
Labels: externals-pending, orp-approved, pending-signatures, tests-pending

#6955 dropping more python2 tools
  pip/Keras.file
  pip/bleach.file
  pip/cryptography.file
  pip/hepdata-lib.file
  pip/html5lib.file
  pip/hyperas.file
  pip/ipython.file
  pip/jupyter_core.file
  pip/matplotlib.file
  pip/nbconvert.file
  pip/nbformat.file
  pip/poetry.file
  pip/py3-keras2onnx.file
  pip/pyOpenSSL.file
  pip/pycuda.file
  pip/requirements.txt
  pip/tensorboard.file
  pip/tensorflow.file
  pip/uproot-methods.file
  pip/uproot.file
  pip/uproot4.file
  python_tools.spec
  tensorflow-requires.file
Labels: externals-approved, fully-signed, orp-pending, tests-rejected

#6958 Oracle: update instantclient 19.11
  oracle.spec
Labels: db-pending, externals-pending, orp-pending, pending-signatures, tests-approved

#6929 Triton: enable GPU support
  triton-inference-server-toolfile.spec
  triton-inference-server.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6970 [classlib] Fix needed for GCC 11
  classlib.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6965 Update tag for RecoEgamma-ElectronIdentification to V01-01-04-02-00
  data/cmsswdata.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#6933 PPC - remove -mlong-double-64 flag and use the default
  compilation_flags.file
  fftjet.spec
  fmt.spec
  geant4.spec
  llvm-gcc-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-rejected

#6963 Update OpenBLAS to 0.3.15
  OpenBLAS-fix-dynamic-arch.patch
  OpenBLAS.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6966 adding ppjjjj library [10_6_X backport]
  openloops-user.coll.file
Labels: externals-approved, fully-signed, generators-approved, orp-approved, tests-approved

#6976 Update tag for GeneratorInterface-EvtGenInterface to V02-05-00
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, orp-approved, tests-started

#6969 [BuildRules] Fixes for clang tidy rules
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6972 drop root_numpy and root_pandas deps
  python_tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#6978 py3-Theano: fix relocation
  pip/Theano.file
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6977 Update RecoJets-JetProducers to V05-14-00
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#6983 Update tag for L1Trigger-L1TMuon to V01-05-00
  data/cmsswdata.txt
Labels: externals-pending, orp-approved, pending-signatures, tests-pending

#6985 [BuildRules] Fix TSAN build issues
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#6890 Update LLVM to 12.0
  llvm.spec
  pip/llvmlite.file
  py2-llvmlite-llvm9.patch
  py2-llvmlite-removeMethod.patch
  py2-llvmlite-removeduplicate.patch
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6973 removal of additional python2 tools
  pip/GitPython.file
  pip/Jinja2.file
  pip/Mako.file
  pip/astroid.file
  pip/avro.file
  pip/bokeh.file
  pip/climate.file
  pip/conan.file
  pip/cryptography.file
  pip/flake8.file
  pip/flit.file
  pip/gitdb2.file
  pip/ipython.file
  pip/jedi.file
  pip/jsonschema.file
  pip/jupyter_client.file
  pip/matplotlib.file
  pip/mpld3.file
  pip/mplhep.file
  pip/nbconvert.file
  pip/nbdime.file
  pip/pexpect.file
  pip/py2-matplotlib.file
  pip/py3-gitdb.file
  pip/py3-keras2onnx.file
  pip/py3-tables.file
  pip/py3-tensorflow.file
  pip/pylint.file
  pip/python-ldap.file
  pip/qtconsole.file
  pip/requests-oauthlib.file
  pip/requests-toolbelt.file
  pip/requests.file
  pip/requirements.txt
  pip/smmap2.file
  pip/tables.file
  pip/tensorboard.file
  pip/tensorflow.file
  pip/terminado.file
  pip/traitlets.file
  pip/virtualenv.file
  pip/yarl.file
  python_tools.spec
  tensorflow-requires.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6988 py2-Jinja2 is needed by DXR
  pip/py2-Jinja2.file
  pip/py3-Jinja2.file
  pip/requirements.txt
  py2-dxr.spec
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#6987 remove more python2 tools
  pip/aiohttp.file
  pip/argon2-cffi.file
  pip/astroid.file
  pip/autopep8.file
  pip/avro.file
  pip/bokeh.file
  pip/conan.file
  pip/entrypoints.file
  pip/fire.file
  pip/flake8.file
  pip/flit.file
  pip/fs.file
  pip/hyperopt.file
  pip/importlib-resources.file
  pip/jsonschema.file
  pip/jupyter_client.file
  pip/luigi.file
  pip/matplotlib.file
  pip/mock.file
  pip/nbconvert.file
  pip/networkx.file
  pip/pandas.file
  pip/py2-matplotlib.file
  pip/py3-numba.file
  pip/py3-tensorflow.file
  pip/pycuda.file
  pip/python-daemon.file
  pip/pytools.file
  pip/requests.file
  pip/requirements.txt
  pip/stevedore.file
  pip/tensorflow.file
  pip/terminado.file
  pip/tornado.file
  pip/traitlets.file
  pip/virtualenv.file
  pip/xrootdpyfs.file
  python_tools.spec
  tensorflow-requires.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6989 [DXR] Use get dxr sources from cms-externals
  py2-dxr-clang36.patch
  py2-dxr-clang37.patch
  py2-dxr-clang700.patch
  py2-dxr-dxrindex-fpic.patch
  py2-dxr-fix-clang-linker-flags.patch
  py2-dxr-llvm-shared.patch
  py2-dxr-llvm10.patch
  py2-dxr-llvm801.patch
  py2-dxr-sqlite38.patch
  py2-dxr.patch
  py2-dxr.spec
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-started

#6975 Update vecgeom to 1.1.16
  vecgeom-fix-for-arm64.patch
  vecgeom-fix-vector.patch
  vecgeom.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6994 [DXR] Update DXR code to work with PY3
  pip/pysqlite3.file
  pip/requirements.txt
  py3-dxr-toolfile.spec
  py3-dxr.spec
  python_tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6995 update CrabClient version in dev
  crab-dev.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6991 Updated root to tip of branch v6-22-00-patches
  root.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6998 Update tag for PhysicsTools-PatUtils to V00-05-00
  data/cmsswdata.txt
Labels: externals-pending, orp-approved, pending-signatures, tests-started

#6993 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#7000 [10.6] Backport of 6998
  data/cmsswdata.txt
Labels: externals-pending, orp-approved, pending-signatures, tests-pending

#6971 Update eigen, get omitted commit
  eigen.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#6990 continue with removing python2 versions
  pip/Keras.file
  pip/bokeh.file
  pip/cffi.file
  pip/conan.file
  pip/flake8.file
  pip/h5py.file
  pip/hepdata-lib.file
  pip/html5lib.file
  pip/hyperopt.file
  pip/importlib-metadata.file
  pip/importlib-resources.file
  pip/jsonschema.file
  pip/keras-applications.file
  pip/lz4.file
  pip/nbdime.file
  pip/pkgconfig.file
  pip/pytest-cov.file
  pip/rep.file
  pip/requirements.txt
  pip/tornado.file
  pip/uproot.file
  pip/uproot4.file
  python_tools.spec
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-rejected

#7003 Patch tkonline to bring pure virtual functions
  tkonlinesw-bring-pvf.patch
  tkonlinesw.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7004 [DXR] Py3 updates needed to avoid creashes with multi-threading
  py3-dxr.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7005 Update pillow to 8.2.0 to fix the security issue reported by GH
  pip/requirements.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7006 [BuildRules] Fix issue with generating rootmap files during PR tests
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7007 [DXR] Added deps on py3-Pygments which is required at runtime by dxr
  py3-dxr.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6986 Oracle: update instantclient 19.11
  oracle.spec
Labels: backport-ok, externals-pending, orp-pending, pending-signatures, tests-approved

#7002 Bring the -mcpu=power8 flag
  compilation_flags.file
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7009 minor fix to crab client
  crab-dev.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7008 continue with removing python2 versions
  pip/Keras.file
  pip/bokeh.file
  pip/cffi.file
  pip/conan.file
  pip/flake8.file
  pip/h5py.file
  pip/hepdata-lib.file
  pip/html5lib.file
  pip/hyperopt.file
  pip/importlib-metadata.file
  pip/importlib-resources.file
  pip/jsonschema.file
  pip/keras-applications.file
  pip/lz4.file
  pip/nbdime.file
  pip/pkgconfig.file
  pip/pytest-cov.file
  pip/rep.file
  pip/requirements.txt
  pip/tornado.file
  pip/uproot.file
  pip/uproot4.file
  python_tools.spec
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-approved

#6799 [GCC10] Update version to 10.3.0
  gcc-103-substitution-bug-fix.patch
  gcc.spec
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-started

#7013 Update tag for Validation-HGCalValidation to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#7014 cmssw-env: Fixes for quoted args
  cmssw-osenv.spec
Labels: externals-approved, fully-signed, orp-pending, tests-started

#7015 [BuildRules] use python3 in scripts
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7012 DD4Hep - move to tags v01-17-00
  dd4hep.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#7016 Remove unavailable download for openloops
  openloops-user.coll.file
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#7020 Update cmssw-wm-tools.spec
  cmssw-wm-tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7018 Remove unavailable download for openloops
  openloops-user.coll.file
Labels: externals-pending, generators-pending, orp-pending, pending-signatures, tests-approved

#7021 [BuildRules] use python3 in scripts
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7022 Update openloops-user.coll.file
  openloops-user.coll.file
Labels: externals-pending, orp-approved, pending-signatures, tests-pending

#7023 Update openloops-user.coll.file
  openloops-user.coll.file
Labels: externals-pending, orp-approved, pending-signatures, tests-pending

#7024 move tested dev to prod
  crab-prod.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7025 updated DetectorDescription-Schema=V02-03-00
  data/cmsswdata.txt
  data/data-DetectorDescription-Schema.file
Labels: externals-approved, fully-signed, orp-pending, tests-started

#7026 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#7027 Update tag for RecoMuon-TrackerSeedGenerator to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, orp-pending, tests-started

#7028 Update tag for RecoTracker-MkFit to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#7019 cleaning up unused py2 tools ; restoring tensorflow as part of python_tools.spec
  pip/absl-py.file
  pip/argon2-cffi.file
  pip/astroid.file
  pip/fire.file
  pip/flake8.file
  pip/fs.file
  pip/grpcio.file
  pip/isort.file
  pip/llvmlite.file
  pip/luigi.file
  pip/requirements.txt
  pip/tensorboard.file
  pip/traitlets.file
  py2-backports.spec
  python_tools.spec
  tensorflow-requires.file
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-rejected

#7029 rebuild with new CRABServer to make S3 work on SL6
  crab-dev.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7030 fix DetectorDescription-Schema data directory name
  data/data-DetectorDescription-Schema.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6996 move pybind11 to python3 only
  fwlite-tool-conf.spec
  onnxruntime.spec
  pip/awkward1.file
  pip/correctionlib.file
  pip/py3-scipy.file
  pip/requirements.txt
  py2-pybind11-toolfile.spec
  py3-pybind11-toolfile.spec
  python_tools.spec
Labels: externals-pending, orp-approved, pending-signatures, tests-approved

#7032 moving new, tested crab-dev to prod for SL6 compat
  crab-prod.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7033 Update buildrule and scram
  SCRAMV1.spec
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6917 update mkfit to 3.0.1
  mkfit-toolfile.spec
  mkfit.spec
Labels: externals-pending, orp-approved, pending-signatures, requires-external, tests-approved

#7035 [TBB] Commit in master suggested by TBB devs
  tbb.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7036 Revert "[TBB] Commit in master suggested by TBB devs"
  tbb.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#7037 Update tag for GeneratorInterface-EvtGenInterface to V02-06-00
  data/cmsswdata.txt
Labels: externals-pending, orp-approved, pending-signatures, tests-pending

#7034 remove py2-scipy
  fwlite_python_tools.spec
  pip/Keras.file
  pip/Theano.file
  pip/hyperopt.file
  pip/py2-scikit-learn.file
  pip/py2-xgboost.file
  pip/pybrain.file
  professor.spec
  python_tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7041 [G4][geant4_vecgeom] Update geant4 to 10.7.2
  geant4.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#7042 [G4][geant4_only] Update geant4 to 10.7.2
  geant4.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7045 [BuildRules] Add unit test time in the test logs
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6997 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7046 Update tag for L1Trigger-CSCTriggerPrimitives to V00-09-00
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, orp-approved, tests-started

#7048 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: externals-approved, fully-signed, orp-pending, tests-rejected

#7047 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7054 restore pyyaml on python2 as needed by conddb
  pip/Keras.file
  pip/bokeh.file
  pip/conan.file
  pip/hepdata-lib.file
  pip/requirements.txt
  python_tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7038 [10.6] Update tag for GeneratorInterface-EvtGenInterface to V02-06-00
  data/cmsswdata.txt
Labels: backport-ok, externals-approved, fully-signed, orp-approved, tests-approved

#7050 Update tag for GeneratorInterface-EvtGenInterface to V02-00-11-01-00
  data-GeneratorInterface-EvtGenInterface.spec
Labels: externals-approved, fully-signed, generators-approved, orp-approved, tests-approved

#7051 [TBB] Use another repo/branch/tag for PPC
  tbb.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#7055 [BuildRules] Fix the EDM_PLUGIN="0" flag in plugisn/BuildFile
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7053 Get catch2 2.13.6
  catch2.spec
Labels: externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#7057 Update versions for different tools; replace local builds with binary downloads; add trivy tool
  cmsmon-tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7058 [11.3] Update tag for RecoMuon-TrackerSeedGenerator to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: backport-ok, externals-approved, fully-signed, orp-approved, tests-approved

#7056 [SCRAM] Update to support generating multiple tests using single command
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-started

#7060 [CC8] Fix trivy sources: expand after changing to directory
  cmsmon-tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7061 [SCRAM] Added for and foreach attributes for unit tests
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7063 Added detect_odr_violation=0 to asan option
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#7064 patch openloops to use curl instead of urlopen to ignore SSL cert issues
  openloops-urlopen2curl.patch
  openloops.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#7071 update crabclient DEV
  crab-dev.spec
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-started

#7068 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7072 [11.3][OpenLoops] Generate process_src.tgz to be uploaded as source
  openloops-common.file
  openloops-process.spec
  openloops-urlopen2curl.patch
  openloops.spec
Labels: backport, externals-pending, orp-pending, pending-signatures, tests-approved

#7066 [OpenLoops 2.1.2] Generate process_src.tgz to be uploaded as source
  openloops-common.file
  openloops-process.spec
  openloops-urlopen2curl.patch
  openloops.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#7067 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: externals-approved, fully-signed, orp-pending, tests-rejected

#7065 Update devel to python3.9.5
  opencv.spec
  pip/py3-tensorflow.file
  pip/requirements.txt
  py3-pybind11-toolfile.spec
  python3.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7074 Update tag number for root 6.24
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#7070 Moving externals towards python3
  cmssw-tool-conf.spec
  openloops-common.file
  openloops-process.spec
  openloops-urlopen2curl.patch
  openloops.spec
  pip/requirements.txt
  py2-pygithub.spec
  py2-sqlobject.spec
  python_tools.spec
  scons-toolfile.spec
  scons.spec
  sherpa.spec
  sip-toolfile.spec
  sip.spec
  yoda.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7075 added rootntuple tool definition
  root-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7078 build sherpa using python3
  rpm-preamble.file
  sherpa.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7077 [SCRAM] Extra checks of tags and attributes, deploy docs
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7084 Py3 drop used pkgs
  apache-ant.spec
  apache-tomcat.spec
  cmssw-tool-conf.spec
  cvs2git-toolfile.spec
  cvs2git.spec
  geneva-toolfile.spec
  geneva.spec
  testdownload.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started
