Repository cms-sw/cmsdist, pull requests merged in 2021-10, with the labels that each got.

#7346 Minimal backport of CUDA-related changes
  cmssw-tool-conf.spec
  cuda-compatible-runtime.spec
  cuda.spec
  scram-project-build.file
  scram-tools.file/tools/cuda-compatible-runtime/cuda-compatible-runtime.xml
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#7353 update conan and fix dip build
  dip.spec
  pip/requirements.txt
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7354 build dip with cmake instead of conan
  dip.spec
  log4cplus.spec
  scram-tools.file/tools/dip/log4cplus.xml
  scram-tools.file/tools/log4cplus/log4cplus.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7350 Test building Geant4 with C++17
  geant4.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#7351 OpenBLAS: Fix parallel compilation option
  OpenBLAS.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7352 [VecGeom] Update to version v1.1.17
  vecgeom.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7356 Fix libunwind libdir path
  libunwind.spec
  scram-tools.file/tools/gperftools/gperf.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#7355 Test if yoda_pyroot.patch is still necessary (after dropping Py2)
  yoda.spec
  yoda_pyroot.patch
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7358 Update tag for RecoMuon-TrackerSeedGenerator to V00-02-00
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, tests-started, orp-pending

#7349 Update mkFit to V3.3.0-0
  mkfit.spec
Labels: tests-approved, orp-approved, externals-pending, pending-signatures, requires-external

#7361 Update tag for RecoTracker-MkFit to V00-05-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#7359 [DEVEL] Drop python2 from CMS software stack
  archive/py2-future.spec
  archive/python.spec
  cmssw-tool-conf.spec
  coral-tool-conf.spec
  fwlite-tool-conf.spec
  fwlite_python_tools.spec
  pcm_util.spec
  python_tools.spec
  tensorflow-sources.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7369 Update cmssw-env to allow to use any cmssw image
  cmssw-osenv.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7366 fix py3-anyio dependency. Adding setuptools-scm deps properly fix the version issue
  pip/anyio.file
  pip/requirements.txt
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7363 Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7371 backport bootstrap changes from GCC11 branch
  bootstrap-bundle.spec
  file-bootstrap.spec
  libarchive-bootstrap.spec
  lua-bootstrap.spec
  patchelf-bootstrap.spec
  rpm-preamble.file
  rpm.spec
  xz-bootstrap.spec
Labels: externals-approved, fully-signed, tests-started, orp-pending

#7374 Update TBB to 2021.4.0; remove upstreamed patches
  tbb.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7387 Update mkFit to V3.4.0-0
  mkfit.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external

#7401 Update tag for RecoTauTag-TrainingFiles to V00-03-00
  data/cmsswdata.txt
Labels: orp-approved, externals-pending, pending-signatures, tests-started
