Repository cms-sw/cmsdist, pull requests merged in 2021-11, with the labels that each got.

#7422 update bootstrap files
  bootstrap-bundle.spec
  bootstrap-driver.spec
  file-bootstrap.spec
  libarchive-bootstrap.spec
  lua-bootstrap.spec
  patchelf-bootstrap.spec
  rpm-set_runpath.file
  rpm.spec
  xz-bootstrap.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7420 rootmaster: Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7421 rootmodule: Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7423 sync rpm-preamble from gcc11 branch
  rpm-preamble.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7424 allow version suffix options
  cmsLHEtoEOSManager.tmpl
  cmssw-ib.spec
  cmssw-wm-tools.spec
  crab-build.file
  crab-dev.spec
  crab-pre.spec
  crab-prod.spec
  rpm-preamble.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7426 Py3 cleanup: drop py3-rep
  pip/pkgconfig.file
  pip/requirements.txt
  python_tools.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#7276 Update libffi to 3.4.2
  libffi.spec
Labels: tests-approved, hold, externals-pending, pending-signatures, orp-pending

#7357 upgrade lhapdf to 6.4.0, sets to 6.4.0b
  lhapdf.spec
  lhapdf_makeLinks.file
  lhapdf_pdfsetsindex.file
Labels: tests-approved, externals-approved, orp-approved, generators-approved, fully-signed

#7429 Include tensorflow dependencies
  tensorflow.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7437 Drop py3-nbdime from cmssw distribution
  pip/requirements.txt
  python_tools.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#7430 rootmaster: Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7431 rootmodule: Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7439 Rivet 3.1.5, YODA 1.9.2
  rivet.spec
  yoda.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7427 Update mkFit release to V3.5.1-0
  mkfit.spec
Labels: tests-approved, orp-approved, externals-pending, pending-signatures, requires-external

#7443 Update tag for RecoTracker-MkFit to V00-07-00
  data/cmsswdata.txt
Labels: orp-approved, externals-pending, pending-signatures, tests-started

#7435 [12.1.X] Update tag for DQM-EcalMonitorClient to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#7434 [12.0.X] Update tag for DQM-EcalMonitorClient to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#7433 Update tag for DQM-EcalMonitorClient to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#7444 [12.1.X] Update of mkFit release and configuration (backport of PRs #7427 + #7443)
  data/cmsswdata.txt
  mkfit.spec
Labels: tests-approved, orp-approved, externals-pending, pending-signatures, requires-external

#7447 update crabclient to v3.211112
  crab-dev.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7448 rootmaster: Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7449 rootmodule: Updated root to tip of branch master
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7451 [Coral] Fixes to complete FrontierAccess plugin thread-safety
  coral.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7455 dont add WMCore packages to crab-dev client
  crab-build.file
  crab-dev.spec
  crab-pre.spec
  crab-prod.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7460 Update tag for Validation-HGCalValidation to V00-02-00
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, tests-started, orp-pending

#7456 rootmaster: Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7458 update crab-dev to v3.211122
  crab-build.file
  crab-dev.spec
  crab-pre.spec
  crab-prod.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7457 rootmodule: Updated root to tip of branch master
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7461 align crab-pre(vious) with current crab-prod
  crab-pre.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7462 move data packages to github
  data-package-build.file
  data/cmsswdata.txt
  data/data-CalibCalorimetry-CaloMiscalibTools.file
  data/data-FastSimulation-MaterialEffects.file
  data/data-L1Trigger-RPCTrigger.file
  data/data-RecoParticleFlow-PFBlockProducer.file
  data/data-SimG4CMS-Calo.file
  data/data-Validation-Geometry.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7463 always create realverson directory in share area
  cmsswdata.file
  cmsswdata.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7464 Use original config version instead of wrapper
  crab-build.file
  crab-dev.spec
  crab-pre.spec
  crab-prod.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7467 rollback config -> wrapper
  crab-build.file
  crab-dev.spec
  crab-pre.spec
  crab-prod.spec
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#7466 Added cs8 support, remove harded coded usage of amd64
  cmssw-osenv.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7470 allow to use configuration only from WMCore directory
  crab-build.file
  crab-dev.spec
  crab-pre.spec
  crab-prod.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7469 BuildRules: Do not add EDM_TOOL_PREFIX if unit tests sets NO_TEST_PREFIX
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#7419 Update cuda-compatible-runtime to add kernel checks
  cuda-compatible-runtime.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7473 Update 00-nvidia-drivers to check if the CUDA devices can run a kernel
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7472 cms-common: added CentOS Stream support
  cms-common.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7450 Update sqlite to 3.36.0
  sqlite.spec
Labels: tests-approved, hold, externals-pending, pending-signatures, orp-pending

#7477 Update tag for RecoEgamma-PhotonIdentification to V01-03-00
  data/cmsswdata.txt
Labels: externals-approved, orp-approved, fully-signed, tests-started

#7478 Update tag for RecoEgamma-ElectronIdentification to V01-09-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#7481 Update tag for RecoTracker-MkFit to V00-08-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#7465 Update mkFit release for CMSSW_12_2_0_pre3
  mkfit.spec
Labels: orp-approved, externals-pending, pending-signatures, tests-started

#7480 small fix to crab-dev. Now v3.211130
  crab-dev.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending
