Repository cms-sw/cmsdist, pull requests merged in 2021-07, with the labels that each got.

#7082 updated xrootd and blackhat to use py3 only; drop distcc/ccache
  blackhat.spec
  ccache-gcc-toolfile.spec
  ccache.spec
  cmssw-tool-conf.spec
  das_client.spec
  distcc-gcc-toolfile.spec
  distcc.spec
  rpm-preamble.file
  tensorflow-requires.file
  xrootd.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7083 use python to build ninja
  ninja.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7081 remove pyminuit and its dependencies
  cmssw-tool-conf.spec
  professor-toolfile.spec
  professor.spec
  pyminuit2-cling.patch
  pyminuit2-toolfile.spec
  pyminuit2.spec
Labels: externals-pending, generators-pending, orp-pending, pending-signatures, tests-approved

#7090 python3 migration: drop py2-backports
  pip/entrypoints.file
  pip/flake8.file
  pip/fs.file
  pip/ipython.file
  pip/nbconvert.file
  pip/nbdime.file
  pip/py2-matplotlib.file
  py2-backports.spec
  python_tools.spec
  tensorflow-requires.file
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7089 [GOSAM] updated gosam to 2.1.0
  gosam.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7087 py2 cleanup: fastjet and mxnet-predict build with py3
  fastjet-toolfile.spec
  fastjet.spec
  mxnet-predict.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7086 py2 cleanup: doxygen lhapdf and libxslt
  doxygen.spec
  lhapdf.spec
  libxslt.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7093 remove python2 bindings from opencv and llvm
  llvm.spec
  opencv.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7092 Python3 migration: drop py2-cython and only built it for py3
  frontier_client.spec
  gosam.spec
  lhapdf.spec
  pip/cython.file
  pip/h5py.file
  pip/pandas.file
  pip/py2-scipy.file
  pip/py3-numpy.file
  pip/py3-scipy.file
  pip/requirements.txt
  professor2.spec
  python_tools.spec
  rivet.spec
  tensorflow-requires.file
  yoda.spec
Labels: externals-approved, fully-signed, orp-pending, tests-started

#7096 [DEVEL] Disable python for lhapdf: need lhapdf 6.3.0 for py3.9
  lhapdf.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7095 remove python2 bindings from opencv and llvm
  llvm.spec
  opencv.spec
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7101 [FWLite] added python3 toolfile
  fwlite-tool-conf.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#7100 [10.2.X][Pythia8]Lower resonance width to 0.1 as in P8.240
  pythia8.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#7105 remove root_numpy/pandas
  pip/py3-root_pandas.file
  pip/requirements.txt
  pip/root_pandas.file
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7103 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7085 Move boost to python3
  boost-toolfile.spec
  boost.spec
Labels: externals-approved, fully-signed, orp-approved, requires-external, tests-rejected

#7107 move gdb to python3
  gdb.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7108 more changes for py3 in CRABClient
  crab-dev.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7109 Update tag for L1Trigger-TrackFindingTracklet to V00-02-00
  data/cmsswdata.txt
Labels: externals-pending, orp-approved, pending-signatures, tests-pending

#7114 Remove python deps from cmssw/fwlite
  cmssw-ib.spec
  cmssw.spec
  fwlite.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#7106 cleanup python2; use rpm macros for python versions
  boost-toolfile.spec
  coral-tool-conf.spec
  coral-toolfile.spec
  coral.spec
  cuda.spec
  fastjet-toolfile.spec
  fastjet.spec
  frontier_client.spec
  gosam-toolfile.spec
  llvm-gcc-toolfile.spec
  llvm.spec
  pip/python-ldap.file
  professor2-toolfile.spec
  professor2.spec
  python-toolfile.spec
  python3-toolfile.spec
  python_tools.spec
  rivet-toolfile.spec
  rivet.spec
  root.spec
  scram-project-build.file
  sherpa-toolfile.spec
  xrootd.spec
Labels: externals-approved, fully-signed, orp-pending, requires-external, tests-approved

#7111 Update to python 3.9.6
  python3.spec
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-rejected

#7117 [BuildRules] Updated to avoid explicit python3 calls; set SCRAM_TEST env
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7118 [SCRAM] Update doc
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7119 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7123 [SCRAMV1] check for flags names
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7120 [SCRAMV2] Bug fix, do not allow make fragments in BuildFiles
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7124 [SCRAM] V2_2_9_pre15 for 11.2.X
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7122 Upgrade lhapdf to 6.3.0, sets to 6.3.0f
  lhapdf.spec
  lhapdf_makeLinks.file
  lhapdf_pdfsetsindex.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7125 [SCRAM V3] Fail on invalid values in BuildFiles
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7127 [SimG4CMS-Calo] HF ShowerLibrary for Run3
  data/cmsswdata.txt
  data/data-SimG4CMS-Calo.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#7130 Updated root to tip of branch v6-22-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7129 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, requires-external, tests-rejected

#7134 Update fastjet to 3.4.0
  fastjet.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7132 [GEANT4][10.7.2] Fixed Physics List destruction
  geant4.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7136 update crab-dev to v3.210714
  crab-dev.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7133 [GEANT4][VECGEOM][10.7.2] Fixed Physics List destruction
  geant4.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7140 [DEVEL] enable build with python
  lhapdf.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7143 [devel] sync changes from master
  lhapdf.spec
  py3-pybind11-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7112 remove python2 pip support and remaining python2 packages except for future
  fwlite_python_tools.spec
  pip/backports-functools_lru_cache.file
  pip/backports-lzma.file
  pip/backports-shutil_get_terminal_size.file
  pip/backports-shutil_which.file
  pip/backports-ssl_match_hostname.file
  pip/configparser.file
  pip/py2-PyYAML.file
  pip/py2-prettytable.file
  pip/py2-setuptools-scm.file
  pip/py2-wcwidth.file
  pip/requirements.txt
  professor2-toolfile.spec
  py2-future.spec
  py2-pip.spec
  py2-setuptools.spec
  py3-dxr-toolfile.spec
  py3-numpy-toolfile.spec
  python_tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7144 Update tag for L1Trigger-CSCTriggerPrimitives to V00-10-00
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, orp-approved, tests-started

#7145 Fix for DXR, use py3-dxr instead of py2-dxr
  scram-project-build.file
Labels: externals-approved, fully-signed, orp-pending, tests-started

#7146 [BuildRules] cleanup PYTHON27; use python3 as default
  cmssw-tool.file
  cmssw-toolfile.spec
  coral-tool.file
  scram-project-build.file
  scramv1-tool-conf.file
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7142 Update Triton to v2.11
  cmake.spec
  cmssw-tool-conf.spec
  triton-inference-client-toolfile.spec
  triton-inference-client.spec
  triton-inference-client/model_config.cc.file
  triton-inference-client/model_config.h.file
  triton-inference-server-toolfile.spec
  triton-inference-server.spec
Labels: externals-approved, fully-signed, orp-pending, requires-external, tests-rejected

#7141 [Tensorflow] Update to version 2.5.0
  bazel-3.7.0-patches.patch
  bazel.spec
  eigen.spec
  pip/keras-nightly.file
  pip/requirements.txt
  pip/tensorboard-data-server.file
  pip/tensorboard.file
  pip/tensorflow.file
  tensorflow-requires.file
  tensorflow-sources.file
  tensorflow-sources.spec
  tensorflow.spec
Labels: externals-pending, orp-pending, pending-signatures, reconstruction-pending, tests-approved

#7113 update mkfit to V3.1.0
  mkfit.spec
Labels: externals-pending, orp-approved, pending-signatures, tests-approved

#7149 Update tag for RecoTracker-MkFit to V00-02-00
  data/cmsswdata.txt
Labels: externals-pending, orp-approved, pending-signatures, tests-started

#7151 [TF] patch it to use correct pybind11 paths
  tensorflow-sources.file
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7152 [Frontier client] Fixes for python3 transition
  frontier_client.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#7116 Upgrade pythia8 to 306
  pythia8.spec
Labels: externals-approved, fully-signed, generators-approved, orp-pending, tests-approved

#7153 Download tensorboard data server soruces from githhub to fix cc8 builds
  pip/tensorboard-data-server.file
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#7157 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7158 Patch herwig to use python3 when running madgraph in the Matchbox
  herwig7.spec
  herwig_Matchbox_mg_py3.patch
Labels: externals-approved, fully-signed, orp-pending, tests-rejected

#7163 Fix python toolfile yo use python2 version
  scram-tools.file/tools/python/env.sh
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7161 [Openloops] fix using openloop process sources
  openloops-process.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7162 [SimG4CMS-Calo] New revision of HFShowerLibrary_run3_v5.root library
  data/cmsswdata.txt
  data/data-CalibCalorimetry-CaloMiscalibTools.file
  data/data-FastSimulation-MaterialEffects.file
  data/data-L1Trigger-RPCTrigger.file
  data/data-RecoParticleFlow-PFBlockProducer.file
  data/data-SimG4CMS-Calo.file
  data/data-Validation-Geometry.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7166 make DBG build flags persistent to avoid setting them in dev area
  cmssw-queue-override.file
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7165 drop systemtools package
  cmssw-tool-conf.spec
  coral-tool-conf.spec
  fwlite-tool-conf.spec
  scram-tool-conf.file
  systemtools.spec
  tkonlinesw.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7160 Updated root to tip of branch rootnext
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7167 Herwig7: use python3 instead of python
  herwig7.spec
  herwig_Matchbox_mg_py3.patch
  madgraph5amcatnlo-py39.patch
  madgraph5amcatnlo.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7168 Update the NVIDIA GDRCopy library to version 2.2
  cmssw-tool-conf.spec
  gdrcopy.spec
  ucx.spec
Labels: externals-approved, fully-signed, orp-pending, tests-rejected

#7169 [GDB] Update to version 10.2
  gdb.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7175 remove unneeded triton toolfile
  scram-tools.file/tools/triton-inference-server/triton-inference-server.xml
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7176 updated tools for for cxxmodules flags
  pcm_util.spec
  scram-tool-conf.file
  scram-tools.file/tools/boost/boost_header.xml
  scram-tools.file/tools/boost/env.sh
  scram-tools.file/tools/cmssw/cmssw.xml
  scram-tools.file/tools/cmssw/env.sh
  scram-tools.file/tools/pcm_util/pcm_util.xml
  scram-tools.file/tools/root/env.sh
  scram-tools.file/tools/root/root.xml
  scram-tools.file/tools/tbb/env.sh
  scram-tools.file/tools/tbb/tbb.xml
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#7172 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7177 enable the gdb wrapper again; looks like it need PYTHONHOME
  gdb.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#7171 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7174 [TBB] Updated to version v2021.3.0 with patches for ASAN and PPC
  tbb.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#7178 [BuildRules] Fix for project rename
  scram-project-build.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7184 [TBB] Updated to version v2021.3.0 with patches for ASAN and PPC
  tbb.spec
Labels: backport, externals-pending, orp-pending, pending-signatures, tests-pending

#7186 GCC 11 Fix for onnxruntime
  onnxruntime.spec
  pip/requirements.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#7183 Update py3-wheel, py3-numpy and py3-wrapt
  pip/numpy.file
  pip/requirements.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-approved
