Repository cms-sw/cmsdist, pull requests merged in 2021-12, with the labels that each got.

#7484 CRAB: update crab-prod to v3.211130
  crab-build.file
  crab-dev.spec
  crab-pre.spec
  crab-prod.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7485 Update tag for RecoTracker-FinalTrackSelectors to V01-03-00
  data/cmsswdata.txt
Labels: externals-approved, orp-approved, fully-signed, tests-started

#7482 [12.1.X] Update of mkFit release and configuration (backport of PRs #7465 + #7481)
  data/cmsswdata.txt
  mkfit.spec
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#7486 Update RecoTracker-FinalTrackSelectors tag (backport of #36285)
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#7490 Update tag for CondTools-SiPhase2Tracker to V00-02-00
  data/cmsswdata.txt
Labels: orp-approved, externals-pending, pending-signatures, tests-started

#7487 New version of tools
  cmsmon-tools.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7489 Update python-ldap 3.4.0
  pip/python-ldap.file
  pip/requirements.txt
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7491 Drop qtconsole, qtpy and py3-jupyter
  pip/jupyter.file
  pip/qtconsole.file
  pip/requirements.txt
  python_tools.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external

#7492 Remove python and py2-future
  archive/py2-future.spec
  archive/python.spec
  cmssw-tool-conf.spec
  coral-tool-conf.spec
  fwlite-tool-conf.spec
  fwlite_python_tools.spec
  pcm_util.spec
  python_tools.spec
  tensorflow-sources.file
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#7445 [12.2.X] Move to root 6.24
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7495 new version for crab-dev
  crab-dev.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7501 remove python deps from tool files
  scram-tools.file/tools/das_client/das_client.xml
  scram-tools.file/tools/frontier_client/frontier_client.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7503 Fixes needed for GCC11 IBs
  cmsLHEtoEOSManager.tmpl
  cmssw-wm-tools.spec
  crab-pre.spec
  crab-prod.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7499 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7504 fix git to not fail is build direction is not reachable
  git-2.19.0-runtime.patch
  git.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7498 Enable CMS_DEPRECATED warnings for user dev area
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7497 Remove h5py_cache
  pip/requirements.txt
  python_tools.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending, requires-external

#7441 update sigcpp from 2.6.2 to 3.0.7
  scram-tools.file/tools/sigcpp/sigcpp.xml
  sigcpp.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external

#7509 New dasgoclient version
  dasgoclient-binary.spec
  dasgoclient.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7507 [ROOT62.4] Update root to latest v6.24 changes
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7514 [DD4hep] Update to v01-19
  dd4hep.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7522 New dasgoclient version
  dasgoclient-binary.spec
  dasgoclient.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7516 Drop -fsanitize=pointer-compare from ASAN IB
  scram-project-build.file
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending
