Repository cms-sw/cmsdist, pull requests merged in 2021-03, with the labels that each got.

#6655 Boost - update to 1.75.0
  boost.spec
Labels: externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#6682 [7_1_X] upgrade sherpa to 2.2.11
  sherpa.spec
Labels: allow-SiewYan, externals-pending, generators-approved, orp-approved, pending-signatures, tests-rejected

#6676 Updated root to tip of branch master
  root.spec
Labels: externals-approved, fully-signed, orp-pending, tests-rejected

#6692 [SCRAMV3] create scram wrapper to unset PYTHONPATH/LD_LIBRARY_PATH
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6660 Remove Rivet AnalysisHandler patch
  rivet-140-313.patch
  rivet.spec
Labels: allow-intrepid42, externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#6683 Update protobuf 3.15.1 and grpc 1.35.0
  grpc-ssl-fix.patch
  grpc.spec
  pip/requirements.txt
  protobuf.spec
Labels: externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#6695 DD4Hep update to 1-16 tag
  dd4hep.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6697 Updated root to tip of 6-22 - rootnext
  root.spec
Labels: externals-approved, fully-signed, orp-pending, requires-external, tests-rejected

#6700 [SCRAMV3] update wrapper to unset PYTHONPATH
  SCRAMV1.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#6696 Updated root to tip of 6-22 - cmsdist master
  root.spec
Labels: externals-approved, fully-signed, orp-approved, requires-external, tests-rejected

#6701 [Protobuf] Patches to avoid GCC10 build errors
  grpc-toolfile.spec
  protobuf-3.15-gcc10.patch
  protobuf.spec
  tensorflow-sources.file
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6703 New dasgoclient version
  dasgoclient-binary.spec
  dasgoclient.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6705 fix ipython/pylint relocation
  pip/py3-ipython.file
  pip/py3-pylint.file
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6706 move latest version to prod (pre stays as fallback)
  crab-prod.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6704 Update ROOT master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6674 Update Tensorflow 2.4.1
  cmssw-tool-conf.spec
  eigen.spec
  flatbuffers-toolfile.spec
  flatbuffers.spec
  opencv.spec
  pip/flatbuffers.file
  pip/google-auth-oauthlib.file
  pip/google-auth.file
  pip/py2-tensorboard.file
  pip/py2-tensorflow.file
  pip/py3-tensorboard.file
  pip/py3-tensorflow.file
  pip/requests-oauthlib.file
  pip/requirements.txt
  pip/rsa.file
  pip/tensorboard-plugin-wit.file
  python_tools.spec
  tensorflow-python3-sources.spec
  tensorflow-requires.file
  tensorflow-sources.file
  tensorflow-sources.spec
  tensorflow.spec
Labels: externals-approved, fully-signed, orp-pending, requires-external, tests-approved

#6693 bump py2 and py3 versions to latest in pypi
  pip/PyYAML.file
  pip/flit-core.file
  pip/mpmath.file
  pip/pydantic.file
  pip/requirements.txt
  pip/singledispatch.file
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6707 [OpenCV] Apply opencv/opencv#19692 to fix ppc64le build issues with eigen
  opencv.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6711 ROOT next - move from 6-22 to 6-24
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6710 Updated root to tip of branch v6-22-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6708 Upgrade to Herwig 7.2.2
  FxFxFileReader.patch
  LesHouchesFileReader.patch
  herwig7.spec
  thepeg.spec
Labels: externals-approved, fully-signed, generators-approved, orp-approved, tests-approved

#6709 Rename herwigpp to herwig7, and upgrade to Herwig 7.2.2
  FxFxFileReader.patch
  LesHouchesFileReader.patch
  cmssw-tool-conf.spec
  herwig7-toolfile.spec
  herwig7.spec
  thepeg.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#6713 [TBB] Set TBB_PREVIEW_RESUMABLE_TASKS macro
  tbb-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6719 Update tag for EgammaAnalysis-ElectronTools to V00-03-01
  data/cmsswdata.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#6717 Updated root to tip of branch master (need to pick a fix)
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6715 Added AVX512 build support
  OpenBLAS-disable-tests.patch
  OpenBLAS-fix-dynamic-arch.patch
  OpenBLAS.spec
  tensorflow.spec
  vecgeom-fix-vector.patch
  vectorization/cmsdist_packages.py
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6722 Update HepMC source to cms-externals
  hepmc.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6728 added cmssw avx512 support
  gcc-toolfile.spec
  scram-project-build.file
  vectorization/haswell.file
  vectorization/nehalem.file
  vectorization/sandybridge.file
  vectorization/skylake-avx512.file
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6718 Update fastjet to 3.4.0 beta
  fastjet.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#6732 [ROOT] Update to version 6.22.08
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#6730 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6729 Updated root to tip of branch master
  root.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6733 ROOT - Update modules branch
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#6691 Update LLVM to 11.1
  llvm-gcc-toolfile.spec
  llvm.spec
  pip/llvmlite.file
  pip/py3-numba.file
  pip/requirements.txt
  py2-llvmlite-llvm9.patch
  py2-llvmlite-removeduplicate.patch
  python_tools.spec
Labels: externals-approved, fully-signed, orp-pending, requires-external, tests-approved

#6725 draft hepmc with cmake; cleanup old patches
  HepMC-2.06.07-nodoc.patch
  HepMC-2.06.07-pyinit.patch
  hepmc-2.03.06-reflex.patch
  hepmc-2.06.07-WeightContainer-fix-size_type.patch
  hepmc.spec
  rivet.spec
  sherpa.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6731 Update to new version; add new prometheus version; add aps tools
  cmsmon-tools.spec
Labels: externals-approved, fully-signed, orp-pending, tests-started

#6736 make sure to use python2 for pylint and ipython
  pip/py2-ipython.file
  pip/py2-pylint.file
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6699 Boost - update to 1.75.0
  boost-1.75.0-disable-statx.patch
  boost.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6734 [LLVM] Added EventSetupRecord::get checker
  llvm.spec
Labels: externals-approved, fully-signed, orp-pending, requires-external, tests-approved

#6738 Do not use -l $(nproc) to get correct resource usage
  clhep.spec
  google-benchmark.spec
  grpc.spec
  llvm.spec
  lwtnn.spec
  mxnet-predict.spec
  onnxruntime.spec
  opencv.spec
  protobuf.spec
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6739 add cuda to ROOT_INCLUDE_PATH
  cuda-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6740 added dip externals and its dependencies
  cmssw-tool-conf.spec
  dip-toolfile.spec
  dip.spec
  pip/PyJWT.file
  pip/conan.file
  pip/deprecation.file
  pip/fasteners.file
  pip/node-semver.file
  pip/requirements.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6744 Updated root to tip of branch v6-22-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6749 Update py3-pillow to version 8.1.1 due to security issues
  pip/requirements.txt
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6745 Updated root to tip of branch master
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6742 Back port geant4 10.7.1 changes from geant4_vecgeom
  clhep.spec
  geant4-G4EMLOW.spec
  geant4-G4ENSDFSTATE.spec
  geant4-G4PARTICLEXS.spec
  geant4-G4PhotonEvaporation.spec
  geant4-G4RadioactiveDecay.spec
  geant4-G4RealSurface.spec
  geant4-toolfile.spec
  geant4.spec
  vecgeom-fix-for-arm64.patch
  vecgeom-fix-vector.patch
  vecgeom.spec
Labels: externals-approved, fully-signed, orp-approved, requires-external, tests-approved

#6750 Update to newest version of cmsmon-tools; added k8s_info
  cmsmon-tools.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6753 Update modules IB CLHEP
  clhep.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#6755 crab client v3.210323
  crab-dev.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6754 [BuildRules] use TARGET keywords instead of VECTOR for micro-inst builds
  gcc-toolfile.spec
  scram-project-build.file
  vectorization/cmsdist_packages.py
Labels: externals-pending, orp-pending, pending-signatures, tests-rejected

#6752 Try Madgraph 2.7.3 for py3 compatibility
  madgraph5amcatnlo-compile.patch
  madgraph5amcatnlo-config.patch
  madgraph5amcatnlo.spec
Labels: externals-approved, fully-signed, generators-approved, orp-pending, tests-approved

#6756 Remove vecgeom macros to avoid redefinition warnings
  vecgeom-toolfile.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-approved

#6758 [CC8] Sync madgraph 2.7.3
  madgraph5amcatnlo-config.patch
  madgraph5amcatnlo.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6746 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: externals-pending, orp-pending, pending-signatures, tests-pending

#6765 Dip add platform dependent
  dip-toolfile.spec
  dip.spec
  pip/conan.file
Labels: externals-pending, orp-pending, pending-signatures, tests-started

#6764 Update to CUDA 11.2 Update 2
  cuda.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6769 Update tag for RecoHGCal-TICL to V00-02-01
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, orp-approved, tests-started

#6762 patching CLEO model for production studies
  0001-applyng-fix-FULSOM-Bryan-May-12-2015-Change-boost-L1.patch
  evtgen.spec
Labels: externals-approved, fully-signed, orp-approved, tests-approved

#6771 [Coral] Bug fix for the DB connection lifetime
  coral.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6772 Update tag for L1Trigger-L1TMuon to V01-04-00
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, orp-pending, tests-started

#6775 patching CLEO model for production studies
  evtgen.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved

#6779 [GitTools] enable -A for git-cms-merge/checkout-topic
  cms-git-tools.spec
Labels: externals-approved, fully-signed, orp-pending, tests-approved
