Repository cms-sw/cmsdist, pull requests merged in 2021-09, with the labels that each got.

#7257 Update to CUDA 11.4.1
  cuda.spec
  cudnn.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, backport-ok

#7256 Update OpenMPI to version 4.1.1
  openmpi.spec
Labels: tests-approved, bug-fix, externals-approved, fully-signed, orp-pending

#7258 Update LLVM to version 12.0.1
  llvm.spec
Labels: tests-approved, bug-fix, externals-pending, pending-signatures, orp-pending

#7260 ThePEG - remove `-g` flag from the compilation
  thepeg.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7261 [Herwig7] Patch FXFX.h to match thepeg/LesHouches.h
  herwig7-fxfx-fix.patch
  herwig7.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7265 [cmssw-ib] Use latest buildLogAnalyzer.py which treats private header usage as build errors
  cmssw-ib.spec
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#7266 Update tag for L1Trigger-CSCTriggerPrimitives to V00-11-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#7268 update crab-dev with latest bug fix
  crab-dev.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7269 [HFShowerLibrary] Update to version v6
  data/cmsswdata.txt
  data/data-SimG4CMS-Calo.file
Labels: orp-approved, externals-pending, pending-signatures, tests-started

#7280 Drop byacc
  byacc.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7282 Update tag for CalibPPS-ESProducers to V01-04-00
  data/cmsswdata.txt
Labels: tests-approved, orp-approved, externals-pending, pending-signatures

#7278 Enable the use of cuDNN in ONNX on ARM for CentOS 8
  scram-tools.file/tools/onnxruntime/onnxruntime.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7277 Update to CUDA 11.4.2
  cuda.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7285 Update CLHEP
  clhep.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7288 update crab-dev to v3.210909 and set to use 1.5.2 wmcore
  crab-dev.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7279 Add the cuda-compatible-runtime test as a new external
  cmssw-tool-conf.spec
  cuda-compatible-runtime.spec
  cuda.spec
  scram-tools.file/tools/cuda-compatible-runtime/cuda-compatible-runtime.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7289 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7293 [BuildRules] Use CUDA runtime compatibility to set cuda env
  scram-project-build.file
Labels: externals-approved, fully-signed, tests-started, orp-pending

#7284 Update cgal
  cgal-4.2-cmake-string-replace.patch
  cgal.spec
  cmssw-tool-conf.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7294 Remove doxygen from cmssw dist
  cmssw-tool-conf.spec
  doxygen.spec
  scram-tools.file/tools/doxygen/doxygen.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7295 Drop unused spec
  cms-sdt-pages.spec
  cmssw-coverity.spec
  cmssw-dqm-reference-deployer.spec
  cmssw-dqm-reference-hi.spec
  cmssw-dqm-reference-nonhi.spec
  cmssw-dqm-reference.file
  cmssw-dqm-reference.spec
  cmssw-git-mirror.spec
  gfortran-macosx.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7296 drop openssl from bootstrap bundle
  bootstrap-bundle.spec
  openssl-bootstrap.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7297 cleanup data package generation
  data/package.sh
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7287 Update mkfit to V3.2.0-0
  mkfit.spec
Labels: tests-approved, orp-approved, externals-pending, pending-signatures, requires-external

#7298 Update tag for RecoTracker-MkFit to V00-04-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#7299 Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7301 Updated correctionlib version 2.0.0 and its dependencies
  pip/correctionlib.file
  pip/requirements.txt
  pip/rich.file
  scram-tools.file/tools/py3-correctionlib/correctionlib.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7303 Remove unused pip files
  pip/gitdb2.file
  pip/onnxruntime.file
  pip/pyOpenSSL.file
  pip/pysqlite.file
  pip/root_numpy.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7304 added dummy test-download package to show how to use custom download command
  pip/cmstest.file
  pip/requirements.txt
  pip/test-download.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7302 Drop dmtcp package, keeping the spec in archive
  archive/dmtcp-3.0.0-dev-ptr-int-comp.patch
  archive/dmtcp-remove-git-hooks.patch
  archive/dmtcp.spec
  cmssw-tool-conf.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7305 use default aiohttp version 3.7.4
  pip/requirements.txt
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7306 remove unused data package Geometry-TrackerCommonData
  data/cmsswdata.txt
  data/data-Geometry-TrackerCommonData.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7308 Drop fitsio spec
  fitsio.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7310 Update form and clean up recipe
  form.spec
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#7313 Update DD4Hep 12_1 to specific commit
  dd4hep.spec
Labels: tests-approved, reconstruction-pending, externals-pending, pending-signatures, orp-pending

#7317 update pdf sets for ultra legacy release
  lhapdf.spec
  lhapdf_makeLinks.file
  lhapdf_pdfsetsindex.file
Labels: tests-approved, externals-approved, orp-approved, generators-approved, fully-signed

#7318 Drop graphviz
  archive/graphviz.spec
  cmssw-tool-conf.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7314 Update DD4Hep 12_0 to specific commit
  dd4hep.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#7316 Update Geant4 to 10.7.2
  geant4.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#7281 Update UTM to 0.9.1
  utm.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7319 Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7320 Update ROOT modules branch
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7321 Update gnuplot to 5.2.8
  gnuplot.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7309 Update fmt to 8.0.1
  fmt.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7324 Update json to 3.10.2
  json.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7328 Test if patch for libunwind is still needed
  igprof-gcc8.patch
  libunwind.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7331 Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7337 [12.0] Update UTM 0.9.1
  utm.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#7334 Valgrind version 3.17.0
  scram-tools.file/tools/valgrind/valgrind.xml
  valgrind.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7339 Update qgraf to 3.4.2
  qgraf.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7341 Buildrule tag update to V07-00-00
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7343 Added glibc-headers in bootstrap for cc8 and slc7
  bootstrap-driver.spec
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#7348 simplify bootstrap-driver
  bootstrap-driver.spec
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#7330 clean up binary moves in python packages
  pip/ipython.file
  pip/jupyter-client.file
  pip/jupyter-console.file
  pip/luigi.file
  pip/nbformat.file
  pip/notebook.file
  pip/pylint.file
  pip/pytest.file
  pip/sympy.file
  pip/tables.file
  pip/wheel.file
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external
