Repository cms-sw/cmsdist, pull requests merged in 2022-02, with the labels that each got.

#7592 [AARCH64][GCC10] Build with -march=armv8-a
  OpenBLAS.spec
  boost.spec
  compilation_flags.file
  fastjet.spec
  fftjet.spec
  fmt.spec
  geant4.spec
  grpc-gcc11.patch
  mkfit.spec
  root.spec
  scram-tools.file/tool-env.file
  tensorflow-sources.file
  vecgeom.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7604 Update tag for RecoEcal-EgammaClusterProducers to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#7605 Update crab client
  crab-build.file
  crab-dev.spec
  crab-pre.spec
  crab-prod.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7529 Updated boost to 1.78
  boost.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending, requires-external

#7602 [ROOT 6.26] Root update v6 26 00 patches 20220203
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7601 [ROOT master] Updated root to tip of branch master
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#7483 external lib for HYDJET++
  cmssw-tool-conf.spec
  hydjet2.spec
  hydjet2/doc.txt
  scram-tools.file/tools/hydjet2/hydjet2.xml
Labels: tests-approved, externals-approved, generators-approved, fully-signed, orp-pending, requires-external

#7606 Update tag for RecoMuon-TrackerSeedGenerator to V00-03-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7613 update to latest CRAB tag
  crab-prod.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7615 Update tag for RecoBTag-Combined to V01-12-00
  data/cmsswdata.txt
Labels: orp-approved, externals-pending, pending-signatures, tests-started

#7611 [geant4_vecgeom] Update Geant4 to 11.0, G4EMLOW to 8.0, G4PARTICLEXS to 4.0
  geant4-G4EMLOW.spec
  geant4-G4PARTICLEXS.spec
  geant4.spec
  vecgeom.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7612 Update Geant4 to 11.0, G4EMLOW to 8.0, G4PARTICLEXS to 4.0
  cmssw-tool-conf.spec
  dd4hep.spec
  geant4-G4EMLOW.spec
  geant4-G4PARTICLEXS.spec
  geant4.spec
  scram-tools.file/tools/geant4/geant4vis.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7616 Update Boost version 1.78
  boost-1.75.0-disable-statx.patch
  boost.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7619 Update tag for RecoParticleFlow-PFProducer to V16-02-00
  data/cmsswdata.txt
Labels: externals-approved, orp-approved, fully-signed, tests-started

#7618 remove unused files
  afs-relocation-cern.spec
  cmsos.file
  fwlite_application_set.file
  rpm-preamble.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7626 Update tag for RecoMuon-MuonIdentification to V01-13-00
  data/cmsswdata.txt
Labels: orp-approved, externals-pending, pending-signatures, tests-started

#7622 [Coral] Add const to char* to fix compiler errors with PyString_AsString
  coral.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7625 update crab-prod to last tested crab-dev
  crab-prod.spec
Labels: externals-approved, fully-signed, tests-started, orp-pending

#7630 [build rules] fix for edm class check rules
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7634 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7636 [ROT626] Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7528 remove mkFit external
  cmssw-vectorization.file
  mkfit-2.0.0-non-x86_64-fix.patch
  mkfit.spec
  scram-tools.file/tools/mkfit/mkfit.xml
  scram-tools.file/tools/mkfit/vectorized.tmpl
  vectorization/cmsdist_packages.py
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external

#7639 Update glimpse to 4.18.7-6; fix source URL (the old one is dead)
  glimpse.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7640 Update glimpse to 4.18.7-6; fix source URL (the old one is dead)
  glimpse.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending, backport-ok

#7638 Update GBL (and move to git instead of svn)
  gbl.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external

#7617 [TF] Added build with GPU support but default is to build without GPU
  tensorflow-requires.file
  tensorflow-sources.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7644 CORAL: Replace deprecated std::auto_ptr with std::unique_ptr and move some header files out of src (cms-externals/coral#9)
  coral.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7643 [ROOT626] Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7642 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7645 Update tag for Alignment-OfflineValidation to V00-02-00
  data/cmsswdata.txt
Labels: orp-approved, externals-pending, pending-signatures, tests-started

#7641 Update to CUDA 11.4.4
  cuda.spec
Labels: tests-approved, bug-fix, externals-pending, pending-signatures, orp-pending

#7646 New dasgoclient version
  dasgoclient.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7594 XRootD: Update to version 5.4.0 and build with scitokens-cpp
  scitokens-cpp.patch
  scitokens-cpp.spec
  scram-tools.file/tools/scitokens-cpp/scitokens-cpp.xml
  scram-tools.file/tools/xrootd/xrootd.xml
  xrootd.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7651 [DEVEL] Update XRootd 5.4.1
  xrootd.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7652 XRootD: Update to version 5.4.1 and build with scitokens-cpp
  scitokens-cpp.patch
  scitokens-cpp.spec
  scram-tools.file/tools/scitokens-cpp/scitokens-cpp.xml
  scram-tools.file/tools/xrootd/xrootd.xml
  xrootd.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending, backport-ok
