Repository cms-sw/cmsdist, pull requests merged in 2022-08, with the labels that each got.

#8010 [ROOT626] Root update v6 26 00 patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8009 [ROOT6] Root update master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8011 Update crab-prod to v3.220714
  crab-pre.spec
  crab-prod.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8013 Update tag for DQM-Integration to V00-02-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8015 Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending

#8014 Root update master 20220808
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8017 Update alpaka to the develop branch as of 2022.08.11
  alpaka.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8018 Update alpaka to the develop branch as of 2022.08.11 [12.4.x]
  alpaka.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending, backport

#8022 Remove py3-xrootdpyfs and py3-fs, see #7521
  archive/fs.file
  archive/xrootdpyfs.file
  pip/requirements.txt
  python_tools.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8019 Fix YODA recipe
  yoda.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8021 Root update v6 26 00 patches 20220815
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8020 Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8028 [vecgeom][gcc11] drop CMAKE_CXX_FLAGS_RELEASE to let veccgeom use its default flags
  vecgeom.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8026 [GCC Flags] drop -Wstrict-overflow which has been deprecated since gcc8
  scram-tools.file/tools/gcc/env.sh
  scram-tools.file/tools/icc/icc-cxxcompiler.xml
  scram-tools.file/tools/icx/icx-cxxcompiler.xml
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8029 Set `HWLOC_PLUGINS_PATH`
  scram-tools.file/tools/hwloc/hwloc.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8031 Update tag for Validation-HGCalValidation to V00-05-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8035 Update crab-prod to v3.220823
  crab-prod.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8034 [ROOT6] Root update master 20220823
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8033 [ROOT626] Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8037 [BuildRules] Include LTO changes but keep them disabled for non-LTO builds
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8038 [BuildRules] testing LTO rules
  scram-project-build.file
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8041 Update tag for L1Trigger-Phase2L1ParticleFlow to V00-04-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8044 Pass the host compiler's triple as the target to hipcc/llvm
  scram-tools.file/tools/gcc/env.sh
  scram-tools.file/tools/gcc/gcc-cxxcompiler.xml
  scram-tools.file/tools/rocm/rocm.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, heterogeneous-approved

#8039 [GCC][PATCH] libstdc++: Mark non-exported function always_inline
  fakesystem.spec
  gcc-03af8492bee6243a9d10e78fea1a3e423bd5f9cd.patch
  gcc.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8046 Fix ROCM_FLAGS
  scram-tools.file/tools/rocm/rocm.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, heterogeneous-approved

#8047 nbconvert vulnerable to cross-site scripting (XSS)
  pip/nbconvert.file
  pip/requirements.txt
  pip/tinycss2.file
Labels: externals-approved, fully-signed, tests-started, orp-pending

#8049 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8052 [12.4][BuildRules] back port multi-vec fixes
  SCRAMV1.spec
  scram-project-build.file
Labels: tests-approved, externals-approved, orp-approved, fully-signed
