Repository cms-sw/cmsdist, pull requests merged in 2022-12, with the labels that each got.

#8212 [G4] Update clhep to 2.4.6.0
  clhep.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8215 Update igprof to handle unrecognosed prologue for movq instruction with XMM registers
  igprof.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8216 Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8211 [G4VECGEOM] Update clhep to 2.4.6.0, vecgeom to 1.2.1
  clhep.spec
  dd4hep.spec
  geant4.spec
  vecgeom.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8222 Update tag for RecoEgamma-ElectronIdentification to V01-12-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8223 ROOT 6 with LLVM 13: Updated root to tip of branch master
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8225 [12.6.X] Update tag for RecoEgamma-ElectronIdentification to V01-12-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8226 [G4][VecGeom] Update Geant4 11.1.0 and build g4/dd4hep with default flags
  dd4hep.spec
  geant4.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8227 [G4] Update geant4 version to v11.1.0
  geant4.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8206 Update git to 2.38.1
  git.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8221 Update zstd to latest version 1.5.2
  zstd.spec
Labels: tests-approved, hold, externals-pending, pending-signatures, orp-pending

#8231 Update hwloc to version 2.9.0
  hwloc.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8232 Update oneTBB to version v2021.8.0-rc1
  tbb.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8235 Update tag for CalibTracker-SiStripDCS to V01-01-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8234 [boost] Better annotate interprocess_exception
  boost.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8237 Minor updates to the TBB build configuration
  tbb.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8238 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8236 Incorporating `murre` tool under cmsmon-tools.
  cmsmon-tools.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8240 [boost] Include name of already existing item in segment_manager
  boost.spec
Labels: externals-approved, fully-signed, tests-started, orp-pending
