Repository cms-sw/cmsdist, pull requests merged in 2022-01, with the labels that each got.

#7535 Update lxml to verion 4.6.5
  pip/requirements.txt
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7518 Drop py-theanets and py-climate
  archive/climate.file
  archive/theanets.file
  pip/requirements.txt
  python_tools.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7536 test latest crab client (no asourl/db)
  crab-dev.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7233 XrootD - backport 531 from devel to master
  libunwind.spec
  scram-tools.file/tools/xrootd/xrootd.xml
  xrootd.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external

#7515 Update Correctionlib to version 2.1.0
  pip/requirements.txt
Labels: tests-approved, externals-approved, fully-signed, orp-pending, urgent

#7539 fronteir client: patch for function arg/return types in frontier_client
  frontier_client.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7540 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7543 Update UTM to version 0.10.0
  utm.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#7541 [ROOT626] Root update v6 26 00 patches 20220112
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7545 Update py-pillow to version 9.0.0
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7546 Updated cmsos to support rhel OS
  cms-common.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7537 Fix check for requirements (#7534), add missing dependencies
  pip/GitPython.file
  pip/PyNaCl.file
  pip/Theano.file
  pip/arrow.file
  pip/cachecontrol.file
  pip/correctionlib.file
  pip/cryptography.file
  pip/deprecated.file
  pip/jeepney.file
  pip/jinja2-time.file
  pip/keyring.file
  pip/make.file
  pip/opt-einsum.file
  pip/pygithub.file
  pip/requirements.txt
  pip/secretstorage.file
  pip/setuptools-rust.file
  pip/smmap2.file
  python_tools.spec
  rust.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7549 [py-make] use tagged source URL
  pip/make.file
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7558 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending, requires-external

#7560 Removing unused patches and spec files.
  0001-Revert-r248245-breaks-ROOT.patch
  alpgen.patch
  beecrypt.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7561 Removed unused file and spec files-Part 2
  cms_oracleocci_abi_hack-fake.spec
  cms_oracleocci_abi_hack.spec
  cmssw-src.spec
  cmssw-xmldata-build.file
  conddbdata-rpm-build.file
  configurations.file
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7562 Removed unused patch, file and spec files-Part 3
  dasgoclient-binary.spec
  data-build-github-new.file
  data-rpm-build.file
  dire.spec
  distcc-gcc7.patch
  eigen-altivec-fix.patch
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7563 Removed unused spec files-Part4
  p5-compress-zlib.spec
  p5-extutils-makemaker.spec
  p5-sort-key.spec
  p5-text-glob.spec
  p5-time-hires.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7565 Removed unused spec and patch files-Part5
  gcc-checker-plugin.spec
  gcc-remove-LWG2825-LWG2756-r245024.patch
  geant4-G4NEUTRONXS.spec
  geant4-bench.spec
  gengetopt.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7569 Removed unused spec and patch files-Part6
  icc-scram.spec
  lcg-dummy.spec
  libatomic_ops.spec
  libffi-3.2.1-fix-include-path.patch
  libunwind-fix-comma.patch
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7570 Removed unused spec, file and patch files-Part7
  local-cern-siteconf.spec
  local-princeton-siteconf.spec
  make-4.2.1.patch
  mysql.spec
  neon.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7572 Removed unused spec, file and patch files-Part8
  partial.py.file
  patch-setup.patch
  pcre2-toolfile.spec
  pip/nbdime.file
  popt.spec
  pylint-2.4.2-encoding.patch
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7566 Fixes needed for ubi8
  SCRAMV1.spec
  bootstrap-driver.spec
  scram-tools.file/tools/pythia6/pydata.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7573 Removed unused patch, file and spec files-Part9
  readline.spec
  readline6.3-upstream-patches1-6.patch
  tauola-27.121-gfortran.patch
  tgsinventorfix.cc.file
  vincia.spec
  weekly.spec
  xgboost-arm-and-ppc-py-0-82.patch
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7574 Removed unused patch and spec files-Part10
  evtgen-1.6.0-configure-new-gcc.patch
  gengetopt-parallelbuild.patch
  icc-provides.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7564 added ubi8 cmsos support
  cms-common.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7557 [CXXMODULE] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7500 [12.3.X] Move to root 6.24
  root.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7576 Update to libunwind 1.6.2
  libunwind.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7577 update cmsos for ubi
  cms-common.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7578 update ipython to get a security fix
  pip/requirements.txt
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7579 igprof patch needed for aarch64
  igprof-gcc8.patch
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7550 New package: libzmq
  libzmq.spec
  pip/pyzmq.file
  scram-tools.file/tools/libzmq/libzmq.xml
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7544 Update OpenMPI and other network components
  gdrcopy.spec
  hwloc.spec
  openmpi.spec
  rdma-core.spec
  ucx.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending

#7580 New dasgoclient version: v02.04.39
  dasgoclient.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7436 Update Geant4 to 10.7ref09
  cmssw-tool-conf.spec
  dd4hep.spec
  geant4.spec
  scram-tools.file/tools/geant4/geant4vis.xml
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending, requires-external

#7583 SCRAM: fix for ifso and ifarch tags
  SCRAMV1.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7585 added rocky and alma linux cmsos support
  cms-common.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7581 Update alpaka to the HEAD of the develop branch as of 2022.01.24
  alpaka.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7586 [ROOT626] Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7587 [ROOT6] Root update master 20220126
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending
