Repository cms-sw/cmsdist, pull requests merged in 2022-07, with the labels that each got.

#7972 [SCRAM] bug fix, make sure HOME env is set before using it
  SCRAMV1.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7970 Update Geant4 to 11.0.6
  geant4.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7971 Update Geant4 to 11.0.6 in geant4vecgeom IBs
  geant4.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7973 Root update master 20220704
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7974 Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7977 [LTO] added lto flags to be used by dedicated LTO builds
  compilation_flags.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7982 [LXML] NULL Pointer Dereference in lxml
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7980 Multi-arch IBs env fix for patch releases
  scram-project-build.file
  scram-tools.file/tools/cmssw/cmssw.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7979 Update hwloc to version 2.8.0
  hwloc.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7986 Update alpaka to the devel branch as of 2022.06.21
  alpaka.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external, heterogeneous-approved

#7988 Update alpaka to the devel branch as of 2022.06.21 [12.4.x]
  alpaka.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok, heterogeneous-approved

#7989 [llvm] cleanup lto flags not supported by llvm
  scram-tools.file/tools/llvm/llvm-cxxcompiler.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7987 Disable aggressive compiler optimizations for VecGeom
  vecgeom.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7991 Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7990 Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7993 Update tag for RecoEgamma-PhotonIdentification to V01-05-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#7994 update crab-dev to v3.220714
  crab-dev.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7995 Update tag for RecoMET-METPUSubtraction to V01-02-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#7992 [vecgeom] Disable aggressive compiler optimizations
  vecgeom.spec
Labels: tests-rejected, orp-approved, simulation-pending, externals-pending, pending-signatures

#7998 Revert "[vecgeom] Disable aggressive compiler optimizations"
  vecgeom.spec
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8000 Revert "Revert "[vecgeom] Disable aggressive compiler optimizations""
  vecgeom.spec
Labels: orp-approved, simulation-approved, externals-pending, pending-signatures, tests-started

#7997 [12_4_X][vecgeom] Disable aggressive compiler optimizations for VecGeom
  vecgeom.spec
Labels: orp-approved, externals-pending, pending-signatures, tests-started

#7999 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8003 Update tag for L1Trigger-CSCTriggerPrimitives to V00-12-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8005 [Backport 12_4_X] Update tag for L1Trigger-CSCTriggerPrimitives to V00-12-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external, backport-ok

#8007 [ROOT626] Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8006 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending
