Repository cms-sw/cmsdist, pull requests merged in 2022-06, with the labels that each got.

#7906 [12.4.X][igprof][el8] Handle ENDBR64 instruction
  igprof.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#7903 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending, backport-ok

#7910 Update to HEAD of libunwind master. Patch is no longer needed.
  libunwind-dwarf.patch
  libunwind.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7909 [XROOTD] Build client only
  xrootd.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7912 Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7916 Bumping up sherpa to 2.2.12
  sherpa.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7919 Update python bottle version to 0.12.21
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7914 [12_4_X] bumping up sherpa to 2.2.12
  sherpa.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#7915 [10_6_X] bumping up sherpa to 2.2.12
  sherpa.spec
Labels: tests-rejected, externals-approved, orp-approved, fully-signed, backport-ok

#7918 [12_4_X] Update tag for RecoTauTag-TrainingFiles to V00-06-00
  data/cmsswdata.txt
Labels: tests-approved, orp-approved, externals-pending, pending-signatures, requires-external

#7921 Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7923 added pysocks as requests dependency
  pip/requests.file
  pip/requirements.txt
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7924 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7925 Update tag for L1Trigger-L1TGlobal to V00-03-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#7927 [SCRAM] Allow conditional dependency for different flavors
  SCRAMV1.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7930 Update tag for RecoEgamma-ElectronIdentification to V01-11-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#7926 [12.4.X] Updated files for the v1_1_0 menu for Run 3 (and minor fix for v1_0_0)
  data/cmsswdata.txt
Labels: tests-rejected, orp-approved, externals-pending, pending-signatures, requires-external, backport-ok

#7932 [BuildRules] Fix findDependency whcih was broken due to python compile rules changes
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7933 Fix genreflex cppflags
  scram-project-build.file
  scram-tools.file/tools/root/rootrflx.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7937 Update tag for L1Trigger-TrackTrigger to V00-02-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#7935 remove cuda-gcc-support tool if cuda gcc support not available
  scram-tool-conf.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7934 Add back and update the compiler flags to the alpaka tools
  scram-tools.file/tools/alpaka/alpaka-cuda.xml
  scram-tools.file/tools/alpaka/alpaka-serial.xml
  scram-tools.file/tools/alpaka/alpaka-tbb.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7928 Update pacparser to 1.4.0
  frontier_client.spec
  pacparser.spec
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#7936 [DEVEL] Added alpaka build rules
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7938 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7939 [ROOT626] Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7940 [Backport 12_4_X] Update to HEAD of libunwind master. Patch is no longer needed
  libunwind-dwarf.patch
  libunwind.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#7941 Add back and update the compiler flags to the alpaka tools [12.4.x]
  scram-tools.file/tools/alpaka/alpaka-cuda.xml
  scram-tools.file/tools/alpaka/alpaka-serial.xml
  scram-tools.file/tools/alpaka/alpaka-tbb.xml
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#7942 [DEVEL] Enable alpaka cuda and serial backends
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7944 [BuildRules] Enabled alpaka build rules
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending, backport-ok

#7947 [security] Update notebook for Token bruteforcing
  pip/requirements.txt
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7948 Update tag for RecoEcal-EgammaClusterProducers to V00-02-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#7946 [ROOT6] Root update master 20220620
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7945 [ROOT626] Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7950 [SCRAM] fix a typo for alpaka flags
  SCRAMV1.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7949 BuildRules: remove extra local flags for dev area
  scram-project-build.file
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7951 [Build Rules] Auto link alpaka backend libraries
  SCRAMV1.spec
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7956 Numpy version 1.22.4, cython 0.29.30
  pip/requirements.txt
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7960 [BuildRules] Fixed code and header checks for alpaka
  SCRAMV1.spec
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7961 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7962 [ROOT626] Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7954 Update jemalloc to version 5.3.0 [12.4.x]
  jemalloc-common.file
  jemalloc-debug.spec
  jemalloc.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#7964 [BuildRule] bug fix, properly set code check alpakabackend tool name
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7952 [Pythia8] Enable Vincia ME corrections
  pythia8.spec
Labels: tests-approved, externals-approved, generators-approved, fully-signed, orp-pending

#7966 Update tag for MagneticField-Interpolation to V01-02-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#7969 Update tag for RecoBTag-Combined to V01-14-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#7967 update jupyter-server to version 1.18.0
  pip/requirements.txt
Labels: externals-pending, pending-signatures, tests-started, orp-pending
