Repository cms-sw/cmsdist, pull requests merged in 2022-10, with the labels that each got.

#8107 Set `ALPAKA_DEFAULT_HOST_MEMORY_ALIGNMENT=128`
  scram-tools.file/tools/alpaka/alpaka.xml
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#8108 Set `ALPAKA_DEFAULT_HOST_MEMORY_ALIGNMENT=128` [12.5.x]
  scram-tools.file/tools/alpaka/alpaka.xml
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport

#8119 Update tag for CalibTracker-SiPixelESProducers to V02-03-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8118 Update crab client dev and pre
  crab-dev.spec
  crab-pre.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8113 Root update master 20221003
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8120 Update geant4 to 11.0.8
  geant4.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8121 Update geant4 to 11.0.8
  geant4.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8117 Python package update to fix the dependabot alerts
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8123 cmssw-osenv: prefer apptiner over singularity if available
  cmssw-osenv.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8122 make cmsswdata and geant4data toolfiles readable by all
  cmsswdata.file
  cmsswdata.spec
  geant4data.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8124 Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8116 Update some python packages to align with Spack
  pip/poetry-cyclic-deps.patch
  pip/requirements.txt
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8126 Update cms-git-tools.spec
  cms-git-tools.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8127 Fix git-cms-checkdeps to track non empty deps
  cms-git-tools.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8129 make cmsswdata and g4data readable by all
  cmsswdata.file
  geant4data.spec
Labels: externals-approved, fully-signed, tests-started, orp-pending

#8128 Add G4HepEm to CMSSW
  cmssw-tool-conf.spec
  g4hepem.spec
  scram-tools.file/tools/g4hepem/g4hepem_interface.xml
  scram-tools.file/tools/g4hepem/g4hepemcore.xml
  scram-tools.file/tools/g4hepem/g4hepemstatic.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#8133 [ROOT6] Updated root to tip of branch master
  dd4hep.spec
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8134 [XRootD] Update to bug fixe version 5.5.1
  xrootd.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8135 update to latest client
  crab-dev.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8137 Update tag for L1Trigger-L1TMuon to V01-07-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8140 Update tag for L1Trigger-L1TGlobal to V00-04-00
  data/cmsswdata.txt
Labels: orp-approved, externals-pending, pending-signatures, tests-started

#8141 Update tag for RecoTracker-FinalTrackSelectors to V01-04-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8148 make sure all tool files are readable
  scram-tool-conf.file
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8139 [Pythia8][306] Pythia Update to fix tau decays
  pythia8.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#8146 [Backport 12_5] Update L1Trigger-L1TGlobal to V00-04-00
  data/cmsswdata.txt
Labels: tests-approved, orp-approved, externals-pending, pending-signatures, requires-external

#8145 [ROOT626] Root update v6 26 00 patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8142 Update tag for L1Trigger-L1TMuon to V01-07-00 - [CMSSW_12_5_X]
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#8143 Update tag for L1Trigger-L1TMuon to V01-07-00 - [CMSSW_12_4_X]
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#8147 [Backport 12_4] Pythia Update to fix tau decays
  pythia8.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external

#8151 [Backport 12_5] Pythia Update to fix tau decays
  pythia8.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external

#8153 [cmssw-osenv] Check and mount for /pool
  cmssw-osenv.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8144 [ROOT6] Root update master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8109 Rivet 3.1.7 & YODA 1.9.7
  rivet.spec
  sherpa.spec
  yoda.spec
Labels: tests-approved, generators-pending, externals-approved, pending-signatures, orp-pending

#8152 [ROOT] Allow submodules to contain headers missing headers
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8159 promote crab-dev to crab-prod. crab-pre to old crab-prod
  crab-dev.spec
  crab-pre.spec
  crab-prod.spec
Labels: externals-approved, fully-signed, tests-started, orp-pending
