Repository cms-sw/cmsdist, pull requests merged in 2022-05, with the labels that each got.

#7836 add Utilities/OpenSSL in fwlite build set
  fwlite_build_set.file
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#7834 New dasgoclient version
  dasgoclient.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7828 Update alpaka to the devel branch as of 2022.04.27 / 879b95ffce2
  alpaka.spec
  cmssw-tool-conf.spec
  cupla.spec
  scram-tools.file/tools/alpaka/alpaka-cuda.xml
  scram-tools.file/tools/alpaka/alpaka-serial.xml
  scram-tools.file/tools/alpaka/alpaka-tbb.xml
  scram-tools.file/tools/cupla/cupla-cuda.xml
  scram-tools.file/tools/cupla/cupla-serial.xml
  scram-tools.file/tools/cupla/cupla-tbb.xml
  scram-tools.file/tools/cupla/cupla.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7838 Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7837 Root update master 20220502
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7841 Update ROOT in CXXMODULES IBs
  root.spec
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#7840 Geant4/VecGeom: use gcc-ar to support LTO builds
  geant4.spec
  scram-tools.file/tools/geant4/geant4core.xml
  scram-tools.file/tools/geant4/geant4static.xml
  vecgeom.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7735 Update vecgeom to 1.1.20
  geant4.spec
  scram-tools.file/tools/veccore/veccore.xml
  scram-tools.file/tools/vecgeom/vecgeom.xml
  veccore.spec
  vecgeom.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7843 Update crab client
  crab-build.file
  crab-dev.spec
  crab-pre.spec
  crab-prod.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7842 Update alpaka to the devel branch as of 2022.05.03 / c493040fe0b
  alpaka.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7845 update vecgeom to 1.2.0 and geant4 to 11.0ref04
  geant4.spec
  vecgeom.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7848 Update tag for L1Trigger-L1TMuon to V01-06-00
  data/cmsswdata.txt
Labels: orp-approved, externals-pending, pending-signatures, tests-started

#7844 [master] Drop legacy MC generators
  cascade-2.2.0-nomanual.patch
  cascade-2.2.04-drop-dcasrn.patch
  cascade-2.2.04-getenv.patch
  cascade.spec
  charybdis-1.003-archive-only.patch
  charybdis-1003-macosx.patch
  charybdis.spec
  cmssw-tool-conf.spec
  herwig-6.520-tauoladummy.patch
  herwig.spec
  jimmy-4.2-configure-update.patch
  jimmy.spec
  photos-215.5-update-configure.patch
  photos.spec
  scram-tools.file/tools/cascade/cascade.xml
  scram-tools.file/tools/cascade/cascade_headers.xml
  scram-tools.file/tools/charybdis/charybdis.xml
  scram-tools.file/tools/herwig/herwig.xml
  scram-tools.file/tools/jimmy/jimmy.xml
  scram-tools.file/tools/jimmy/jimmy_headers.xml
  scram-tools.file/tools/photos/photos.xml
  scram-tools.file/tools/photos/photos_headers.xml
  scram-tools.file/tools/tauola/tauola.xml
  scram-tools.file/tools/tauola/tauola_headers.xml
  scram-tools.file/tools/toprex/toprex.xml
  scram-tools.file/tools/toprex/toprex_headers.xml
  tauola-27.121-gfortran-tauola-srs.patch
  tauola-27.121.5-configure-makefile-update.patch
  tauola-27.121.5-gfortran-taueta.patch
  tauola.spec
  toprex-4.23-archive-only.patch
  toprex-4.23-macosx.patch
  toprex.spec
Labels: tests-approved, orp-approved, externals-pending, pending-signatures, requires-external

#7851 Update SCRAM and build rules
  SCRAMV1.spec
  scram-project-build.file
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7850 dxr: bundle up dxr/trilite and re2 sources
  py3-dxr.spec
  trilite.patch
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7857 Update tag for Validation-HGCalValidation to V00-03-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#7854 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7855 [ROOT626] Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7856 [CXXMODULE] Update to latest root master changes
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7858 meschach: fix for parallel build
  meschach-1.2b-parallel-build.patch
  meschach.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7860 SCRAM: Updated doc for ifarch and ifos BuildFile tags
  SCRAMV1.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7864 Update jupyter-server and notebook
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7868 Update tag for RecoEgamma-ElectronIdentification to V01-10-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#7865 [BuildRules] Do not create python/package symlink to src/package/python
  cmssw-patch-build.file
  scram-project-build.file
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7866 [SCRAM] Allow conditional dependency
  SCRAMV1.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7871 Define TBB_PREVIEW_TASK_GROUP_EXTENSIONS
  scram-tools.file/tools/tbb/tbb.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7873 [ROOT626] Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7872 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7875 Update libzmp to version 4.3.4
  libzmq.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7869 Rivet 3.1.6 + YODA 1.9.5
  rivet.spec
  yoda.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7876 Update tag for RecoTauTag-TrainingFiles to V00-04-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#7862 Update tensorflow to 2.6.3
  pip/requirements.txt
  tensorflow-sources.file
  tensorflow-sources.spec
  tensorflow.spec
Labels: tests-approved, reconstruction-approved, externals-approved, fully-signed, orp-pending

#7877 Update tag for RecoTauTag-TrainingFiles to V00-04-00
  data/cmsswdata.txt
Labels: tests-approved, orp-approved, externals-pending, pending-signatures, requires-external

#7870 [xrootd] Use FORCE_ENABLED to make sure xrootd fails if any deps is not found
  davix.spec
  xrootd.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7884 Make abseil-cpp and c-ares (required for grpc) external packages
  abseil-cpp.spec
  c-ares.spec
  grpc.spec
  scram-tools.file/tools/abseil-cpp/abseil-cpp.xml
  scram-tools.file/tools/c-ares/c-ares.xml
  scram-tools.file/tools/grpc/grpc.xml
  triton-inference-client.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#7889 Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7887 update cryptography for el8; slc7 should use old version 3.2.1
  pip/cmsdist_packages.py
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7885 Make package and toolfile for jemalloc with heap profiling enabled.
  cmssw-drop-tools.file
  cmssw-tool-conf.spec
  jemalloc-prof.spec
  scram-tools.file/tools/jemalloc-prof/jemalloc-prof.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7893 [py-crytograpghy] use version 3.0 for slc7
  pip/requirements.txt
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7888 Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7890 Updated root to tip of branch v6-24-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7867 Update the OpenMPI configure options
  openmpi.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending

#7894 [igprof][el8] Handle ENDBR64 instruction
  igprof.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7891 Update tensorflow to version 2.6.4
  pip/requirements.txt
  tensorflow-sources.file
  tensorflow-sources.spec
  tensorflow.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#7895 use cmsswdata_version_link macro to create full version symlink
  cmsswdata.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#7896 [cms-common] cmsrel/cmsenv changed to functions for bash
  cms-common.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7897 Update OpenMPI to version 4.1.4
  openmpi.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7899 [cmssw-env] Added `--ignore-mount dir1,dir2` option to ignore mount some path
  cmssw-osenv.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#7900 [12.4.X] use cmsswdata_version_link macro to create full version symlink
  cmsswdata.file
Labels: tests-approved, externals-approved, fully-signed, orp-pending, backport-ok

#7898 Update OpenMPI to version 4.1.4 [12.4.x]
  openmpi.spec
Labels: tests-rejected, bug-fix, externals-approved, orp-approved, fully-signed, backport-ok

#7902 Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#7901 Root update master 20220530
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending
