Repository cms-sw/cmsdist, pull requests merged in 2023-03, with the labels that each got.

#8341 [xrootd] Updated to version 5.5.3
  xrootd.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8292 [SimG4CMS-Calo] Update HFShowerLibrary_run3_v7
  data/cmsswdata.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8316 Update Alpaka to the development branch as of 2023.02.15 [13.0.x]
  alpaka.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#8334 Update OpenMPI to version 4.1.5 [13.0.x]
  openmpi.spec
Labels: tests-approved, bug-fix, externals-approved, orp-approved, fully-signed, backport-ok

#8348 Update tag for HeterogeneousCore-SonicTriton to V00-02-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8324 Update Triton client to version 2.25
  scram-tools.file/tools/triton-inference-client/triton-inference-client.xml
  triton-inference-client.spec
  triton-inference-client/model_config.cc.file
  triton-inference-client/model_config.h.file
Labels: tests-approved, orp-approved, externals-pending, pending-signatures, requires-external

#8350 Update tag for RecoEcal-EgammaClusterProducers to V00-03-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8351 Update tag for RecoEgamma-EgammaPhotonProducers to V00-02-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8346 [BuildRules] Enable alpaka ROCm backend
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, urgent

#8347 [BuildRules] Enable alpaka ROCm backend [13.0.x]
  scram-project-build.file
Labels: tests-approved, externals-approved, orp-approved, fully-signed, urgent, backport-ok

#8345 Update ROOT 6.26 in CMSSW master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8355 [TBB] Fix concurrent_[bounded_]queue correctness on weak memory models
  tbb-782.patch
  tbb.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8356 Replace c++1z with c++17
  scram-tools.file/tools/gcc/env.sh
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#8361 [BuildRules] Changes for running unit tests from separate test dirs
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8359 [ROOTMaster] Update rootmaster 20230306
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8360 [ROOT628] Update root628 20230306
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8366 [BuildRules] More fixes for running tests in individual dirs
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8364 Update to cuDNN 8.8.0, pyCUDA 2022.2.2
  cudnn.spec
  pip/requirements.txt
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8367 protobuf/grpc: patch applied for deprecated std::iterator
  grpc.spec
  protobuf.spec
  triton-inference-client.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8372 Build ONNXRuntime for same cuda archs as the rest of cms externals
  onnxruntime.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8375 Update UTM to 0.11.1
  utm.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8373 [ROOT6] Update root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8374 [ROOT628] Root update v6 28 00 patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8376 Create RPM macro to generate CMAKE_PREFIX_PATH
  rpm-preamble.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#8379 Add AXOL1TL extras spec
  AXOL1TL.spec
  cmssw-tool-conf.spec
  scram-tools.file/tools/AXOL1TL/axol1tl.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8383 Update UCX to version 1.14.0
  ucx.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8387 Update tag for RecoEgamma-EgammaPhotonProducers to V00-03-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8385 [BuildRules] Enable usage of separate unit tests directory at project level
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8386 Update utm to v0.11.2
  utm.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8382 Explicitly use the GNU binutils ld.bfd linker
  scram-tools.file/tools/gcc/env.sh
Labels: tests-rejected, externals-approved, fully-signed, orp-pending

#8390 [Geant4] Fix LTO warnings about uninitialized variables
  geant4.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8389 Rename jemalloc libraries with debug and profiling options enabled.
  cmssw-drop-tools.file
  jemalloc-common.file
  jemalloc-debug.spec
  jemalloc-prof.spec
  jemalloc.spec
  scram-tools.file/tools/jemalloc-debug/jemalloc-debug.xml
  scram-tools.file/tools/jemalloc-prof/jemalloc-prof.xml
  scram-tools.file/tools/jemalloc/jemalloc.xml
Labels: tests-approved, externals-approved, fully-signed, orp-pending, requires-external

#8393 [jemalloc] move common sections in to jemalloc-common
  jemalloc-common.file
  jemalloc-debug.spec
  jemalloc-prof.spec
  jemalloc.spec
  patchelf.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8392 [BuildRules] More updates for unit tests
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8378 [Backport to 13_0] Update UTM to version 0.11.2
  utm.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#8370 Package the HIP/ROCm and ROCrand libraries
  cmssw-tool-conf.spec
  fakesystem.spec
  rocm-rocrand.spec
  rocm.spec
  scram-tools.file/tools/alpaka/alpaka-rocm.xml
  scram-tools.file/tools/rocm-rocrand/rocm-rocrand.xml
  scram-tools.file/tools/rocm/rocm-rocrand.xml
Labels: tests-rejected, externals-approved, orp-approved, fully-signed

#8399 [BuildRules] Re-revert to tag V07-09-00
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8371 Package the HIP/ROCm and ROCrand libraries [13.0.x]
  cmssw-tool-conf.spec
  fakesystem.spec
  rocm-rocrand.spec
  rocm.spec
  scram-tools.file/tools/alpaka/alpaka-rocm.xml
  scram-tools.file/tools/rocm-rocrand/rocm-rocrand.xml
  scram-tools.file/tools/rocm/rocm-rocrand.xml
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#8404 Update cms-common: map rhel/rocky/alma distros to el
  cms-common.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8396 Update ROOT in master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8394 [ROOT6] Update root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8395 [ROOT628] Root update v6 28 00 patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8405 drop G4GEOM_USE_USOLIDS flag to fix G4 compilation warnings in cmssw
  scram-tools.file/tools/geant4/env.sh
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8407 [FWLite] Added utm dependency
  fwlite-tool-conf.spec
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8409 Update tag for CondTools-Hcal to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8358 [TBB] Fix concurrent_[bounded_]queue correctness on weak memory models [13.0.x]
  tbb-782.patch
  tbb.spec
Labels: tests-approved, bug-fix, externals-approved, fully-signed, orp-pending, urgent, backport-ok

#8410 Imported yaml-cpp 0.7.0
  cmssw-tool-conf.spec
  scram-tools.file/tools/yaml-cpp/yaml-cpp.xml
  yaml-cpp.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8411 yaml-cpp: fix relocation
  yaml-cpp.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8408 Use VecGeom for limited number of shapes
  geant4.spec
Labels: externals-approved, fully-signed, tests-started, orp-pending

#8413 [ROOT628] Root update v6 28 00 patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8412 [ROOT6] Updated root to tip of master
  root.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending

#8349 Add patches to propagate lhe numbering through herwig
  LHEEventNum.patch
  LHEEventNumFxFx.patch
  LesHouchesFileReader.patch
  herwig7.spec
  thepeg.spec
Labels: tests-approved, externals-approved, orp-approved, generators-approved, fully-signed, requires-external

#8417 Revert "Add patches to propagate lhe numbering through herwig"
  LHEEventNum.patch
  LHEEventNumFxFx.patch
  LesHouchesFileReader.patch
  herwig7.spec
  thepeg.spec
Labels: tests-pending, orp-approved, externals-pending, pending-signatures
