Repository cms-sw/cmsdist, pull requests merged in 2023-12, with the labels that each got.

#8848 Add the ROCm SMI library
  scram-tools.file/tools/rocm/rocm.xml
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8844 [ROOT628] Updated root to tip of branch v6-28-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8843 [ROOT630] Updated root to tip of branch v6-30-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8850 crab-setup - support zsh login shell
  crab/crab-setup.sh.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8845 [ROOT626] Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending

#8852 upgrade lhapdf to 6.5.4, sets to 6.5.1c
  lhapdf.spec
  lhapdf_makeLinks.file
  lhapdf_pdfsetsindex.file
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8856 save crab-prod as crab-pre, then bump to v3.231101
  crab-pre.spec
  crab-prod.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8854 Updated root to tip of branch v6-28-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8855 Updated root to tip of branch v6-30-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8857 bump crab-dev to v3.231204
  crab-dev.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8853 Updated root to tip of branch master
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8858 Patch rivet, yoda, thepeg, fastjet and tkonlinesw to avoid deprecated warnings
  fastjet-deprecated-warn.patch
  fastjet.spec
  rivet-deprecated-warn.patch
  rivet.spec
  thepeg-deprecated-warn.patch
  thepeg.spec
  tkonlinesw-deprecated-warn.patch
  tkonlinesw.spec
  yoda-deprecated-warn.patch
  yoda.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8860 [13_0_X] Update Generator tag to V01-07-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#8862 Update hwloc to version 2.10.0
  hwloc.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending

#8872 Update tag for L1Trigger-DTTriggerPhase2 to V00-03-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8869 Revert lhapdf to 6.4.0 but keep lhapdh_dataset 6.5.1c
  lhapdf.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8873 [boost] Change mpl::integral_c to boost::integral_constant to avoid Clang16
  boost.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending

#8871 Updated root to tip of branch v6-30-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8882 Update tag for Configuration-Generator to V01-08-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8883 [106X] Configuration-Generator to V01-08-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#8884 [124X] Configuration-Generator to V01-08-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#8885 [130X] Configuration-Generator to V01-08-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#8388 Add recipe for pytorch (C++ interface only)
  FindEigen3.cmake.file
  FindFMT.cmake.file
  cmssw-tool-conf.spec
  fxdiv.spec
  psimd.spec
  pytorch-ignore-different-cuda-include-dir.patch
  pytorch-missing-braces.patch
  pytorch-system-fmt.patch
  pytorch.spec
  scram-tools.file/tools/pytorch/pytorch-cuda.xml
  scram-tools.file/tools/pytorch/pytorch.xml
  scram-tools.file/tools/pytorch/torch-interface.xml
Labels: tests-approved, externals-approved, analysis-approved, fully-signed, orp-pending, requires-external

#8875 dd4hep: Update to tag v01-27-01
  dd4hep.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8880 Update python packages to get the security fixes
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8886 Update AXOL1TL.spec to include model v3
  AXOL1TL.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8894 Update tag for RecoTracker-MkFit to V00-13-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8891 Updated root to tip of branch master
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8890 [cuda-runtime] add extra cuda runtime libs needed by pytorch
  cuda-runtime.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8796 [12.4.X] Add fix for segfault in Min Bias
  herwig7.spec
  herwig_MB.patch
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#8795 [10.6..X] Add fix for segfault in Min Bias
  herwig7.spec
  herwig_MB.patch
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#8898 Update tag for SimCalorimetry-EcalEBTrigPrimProducers to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8899 Update crab-dev.spec
  crab-dev.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8878 [Geant4] Update to 11.2.0 for G4VecGeom IBs
  geant4-G4ABLA.spec
  geant4-G4EMLOW.spec
  geant4-G4INCL.spec
  geant4-G4NDL.spec
  geant4.spec
  vecgeom.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8839 Minimal backport of Alpaka fixes for ROCm 5.3 and later
  alpaka.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8902 [14.0.X] Updated root to tip of branch v6-30-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#8900 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#8903 [ROOT628] Updated root to tip of branch v6-28-00-patches
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#8901 Add L1METML extra
  L1METML.spec
  cmssw-tool-conf.spec
  scram-tools.file/tools/L1METML/l1metml.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8905 Update Intel oneAPI compiler to version 2024.0
  icx.spec
  scram-tools.file/tools/icx/icx-cxxcompiler.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8877 [Geant4] Update to 11.2.0 for G4 IBs
  geant4-G4ABLA.spec
  geant4-G4EMLOW.spec
  geant4-G4INCL.spec
  geant4-G4NDL.spec
  geant4.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8908 [BuildRule] Unit test colored output
  scram-project-build.file
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8910 [geant4] Cleanup spec
  geant4.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8911 [json] Version 3.11.3; build with cmake
  json.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8906 Add TOoLLiP extra
  TOoLLiP.spec
  cmssw-tool-conf.spec
  scram-tools.file/tools/TOoLLiP/toollip.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8913 [json] Explicitly added cmake and gmake deps
  json.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8912 Added celeritas version 0.4.1
  celeritas.spec
  cmssw-tool-conf.spec
  scram-tools.file/tools/celeritas/celeritas.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#8914 [celeritas] build with -DCMAKE_POSITION_INDEPENDENT_CODE=ON
  celeritas.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8907 added build options which can be controlled via cmsBuild
  compilation_flags_lto.file
  cpp-standard.file
  etc/build_options.py
  geant4.spec
  scram-tools.file/tool-env.file
  scram-tools.file/tools/gcc/env.sh
  scram-tools.file/tools/gcc/gcc-cxxcompiler.xml
  warning-flags.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8916 celeritas: support for geant4 11.2
  celeritas.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8917 cmssw-tool-conf: Added back celeritas for G4 branch
  cmssw-tool-conf.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external
