Repository cms-sw/cmsdist, pull requests merged in 2023-06, with the labels that each got.

#8529 [12_6_X] Update tag for Configuration-Generator to V01-06-00
  data/cmsswdata.txt
Labels: tests-approved, orp-approved, externals-pending, pending-signatures

#8536 Update tag for DataFormats-Scouting to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8537 Update llvm.spec with latest commit hash
  llvm.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8538 [13.1.X] Update llvm.spec with latest hash
  llvm.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#8541 HDF5: Version 1.14.1 with hdf5 cxx library enabled
  hdf5.spec
  scram-tools.file/tools/hdf5/hdf5-cpp.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8540 Updated root to tip of branch v6-28-00-patches
  root.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending

#8539 Root update master 20230605
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8544 Update tag for DataFormats-Scouting to V00-02-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8543 Bump crab-dev to v3.230612
  crab-dev.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8547 [ROOT6] Root update master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8548 [ROOT628] Root update v6 28 00 patches
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8550 Update frontier client to version 2.10.2
  frontier_client.spec
  pacparser-python-fix.patch
  pacparser.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8551 Update OpenCV to 4.7.0
  opencv.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8557 [G4VECGEOM] Update Geant4 to 11.1.2
  geant4.spec
Labels: externals-approved, fully-signed, tests-started, orp-pending

#8553 Update TBB to version 2021.9.0
  tbb-782.patch
  tbb.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending

#8552 Update Pythia to 8.309
  pythia8.spec
Labels: tests-approved, externals-approved, orp-approved, generators-approved, fully-signed, requires-external

#8545 GCC 11.4; CUDA 11.8; cleanup for cmsplatf/cmsos use
  archive/python.spec
  boost.spec
  bootstrap-driver.spec
  bz2lib.spec
  cmake.spec
  cuda.spec
  curl.spec
  evtgen.spec
  gcc.spec
  gdbm.spec
  gnuplot.spec
  hdf5.spec
  hector.spec
  pip/pillow.file
  pythia6.spec
  python3.spec
  rpm-preamble.file
  sqlite.spec
  starlight.spec
  swig.spec
  tensorflow-sources.spec
  tkonlinesw.spec
  valgrind.spec
  vecgeom.spec
  xerces-c.spec
  xrootd.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#8546 Update GCC to 13.1.0 for EL9
  gcc.spec
Labels: tests-pending, hold, externals-pending, pending-signatures, orp-pending

#8554 DD4hep: Get latest DD4hep v1-25 commit
  dd4hep.spec
Labels: externals-approved, fully-signed, tests-started, orp-pending, requires-external

#8563 Geant4: Cleanup unused cmake variables
  geant4.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8562 Drop py3-Theano, py3-downhill and py3-hep_ml
  pip/Theano.file
  pip/downhill.file
  pip/hep_ml.file
  pip/keras.file
  pip/requirements.txt
  python_tools.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8559 [ROOT6] Update ROOT to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8560 [ROOT628] Root update v6 28 00 patches
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8561 Add patch for pythia8 and c++20; update alpaka to pick up fix for c++20
  alpaka.spec
  pythia8.spec
  pythia8_309-289.patch
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8572 [CUDART] CUDA update to 11.8.0
  cuda-version.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8568 stop distributing old DBS Client with CRAB. Fix #8566
  crab-build.file
  crab-dev.spec
  crab-pre.spec
  crab-prod.spec
  crab/crab-setup.csh.file
  crab/crab-setup.sh.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8576 [ROOT628] ROOT update v6 28 00 patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8575 [ROOT6] Update ROOT to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8573 Update hwloc to version 2.9.2
  hwloc.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8574 Revert "Update TBB to version 2021.9.0"
  tbb-782.patch
  tbb.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending
