Repository cms-sw/cmsdist, pull requests merged in 2023-08, with the labels that each got.

#8565 Update TF to 2.12 (backport from IB/CMSSW_13_2_X/g13 branch)
  abseil-cpp.spec
  bazel-3.7.0-patches.patch
  bazel-absl.patch
  bazel.spec
  eigen.spec
  fasthadd.spec
  flatbuffers-7422.patch
  flatbuffers.spec
  gbl.spec
  grpc-gcc11.patch
  grpc.spec
  java-env.spec
  libzmq.spec
  lwtnn.spec
  onnxruntime.spec
  opencv.spec
  pip/jax.file
  pip/ml_dtypes.file
  pip/onnx.file
  pip/requirements.txt
  pip/tensorflow-io-gcs-filesystem.file
  pip/tensorflow.file
  professor2.spec
  protobuf-3.15-gcc10.patch
  protobuf.spec
  py3-onnx.patch
  py3-tensorflow-io-gcs-filesystem.patch
  scram-tools.file/tools/abseil-cpp/abseil-cpp.xml
  tensorflow-sources.file
  tensorflow-sources.spec
  tensorflow.spec
Labels: tests-rejected, externals-approved, orp-approved, fully-signed, requires-external

#8625 [ROOT628] ROOT update v6 28 00 patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8624 [ROOT6] ROOT update master
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8619 Update Intel oneAPI compiler to version 2023.2.0 [13.2.x]
  icx.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#8633 Python packages: Updates versions with security fixes
  pip/cmsdist_packages.py
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8628 Fasthadd: move back to master repo after merging cms-sw/cmssw#42228
  fasthadd.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8630 Update ROOT in master with v6.26 patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8631 [G4] Update Geant4 to 11.1.ref07
  geant4.spec
  scram-tools.file/tools/geant4/geant4core.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8632 [G4VECGEOM] Update Geant4 to 11.1.ref07
  geant4.spec
  scram-tools.file/tools/geant4/geant4core.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8637 drop py3-py package which is now part of pytest
  pip/py.file
  pip/pytest.file
  pip/requirements.txt
  python_tools.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8617 Define c++ standard in one place
  abseil-cpp.spec
  bazel.spec
  cpp-standard.file
  cuda-flags.file
  dd4hep.spec
  eigen.spec
  gbl.spec
  geant4.spec
  grpc.spec
  heppdt.spec
  lwtnn.spec
  opencv.spec
  pip/onnx.file
  professor2.spec
  protobuf.spec
  py3-onnx.patch
  rivet.spec
  root.spec
  scram-tools.file/tool-env.file
  scram-tools.file/tools/gcc/env.sh
  starlight-r193-allow-setting-CMAKE_CXX_FLAGS.patch
  starlight.spec
  tbb.spec
  tensorflow-sources.file
  triton-inference-client.spec
  vecgeom.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8639 TF: keep read cpp-standard first
  tensorflow-sources.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8638 SCRAMV1: Do not update scram links.db via package installation
  SCRAMV1.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8558 Use C++20 with more packages
  opencv-cpp20.patch
  opencv.spec
  pip/onnx.file
  protobuf.spec
  py3-onnx.patch
  sherpa-cpp20.patch
  sherpa.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8641 [ROOT628] ROOT update v6 28 00 patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8640 [ROOT6] Root update master
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8643 [Gcc12]Update cuda version 12.2.1
  cuda.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8645 Minimal backport of fixes and updates to alpaka::Vec
  alpaka.spec
Labels: tests-approved, bug-fix, orp-approved, externals-pending, pending-signatures

#8649 Update tag for L1Trigger-TrackTrigger to V00-03-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#8646 Minimal backport of fixes and updates to alpaka::Vec [13.2.x]
  alpaka.spec
Labels: tests-approved, bug-fix, externals-approved, orp-approved, fully-signed, backport-ok

#8647 Update alpaka to pickup fixes for C++20 and alpaka::Vec [13.1.x]
  alpaka.spec
Labels: tests-approved, bug-fix, externals-approved, orp-approved, fully-signed, backport-ok

#8648 Update alpaka to pickup fixes for C++20 and alpaka::Vec [13.0.x]
  alpaka.spec
Labels: tests-approved, bug-fix, externals-approved, orp-approved, fully-signed, backport-ok

#8653 Update tag for DQM-Integration to V00-03-00
  data/cmsswdata.txt
Labels: tests-pending, externals-approved, fully-signed, orp-pending

#8651 [ROOT628] Root update v6 28 00 patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8650 [ROOT6] Updated ROOT to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8655 Update tag for DQM-Integration to V00-03-00 [13_2_X]
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8583 Update XRootD to version 5.6.1
  xrootd.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8660 Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8659 Updated root to tip of branch v6-28-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8658 Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8662 [xrootd] avoid explicitly setting UUID lib and include flags
  xrootd.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8661 [xrootd][el9] Workaround for finding uuid
  xrootd.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8664 cms-common: Fix for scram site runtime hook XrdSecPROTOCOL
  cms-common.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8663 Update py3-tornado and py3-GitPython
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8635 Update gperftools/tcmalloc to 2.11
  gperftools.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8656 Update ROCm to version 5.6
  rocm-rocrand.spec
  rocm.spec
  scram-tools.file/tools/rocm/rocm.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8642 Force check dependencies for provides and requires
  cuda-compatible-runtime.spec
  llvm.spec
  openmpi.spec
  oracle.spec
  ucx.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8666 cms-common: Fix typo for almalinux
  cms-common.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8667 Add missing rocm deps on zstd
  rocm.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8668 [ROOT6] Updated root to tip of branch master
  dd4hep.spec
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8669 [ROOT628] Updated root to tip of branch v6-28-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8671 Update igprof.spec with aligned_alloc commit
  igprof.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8673 [ROOT 6.28.06] Updated root to tip of branch v6-28-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending
