Repository cms-sw/cmsdist, pull requests merged in 2023-11, with the labels that each got.

#8798 Updated root to tip of branch v6-28-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8799 Updated root to tip of branch v6-30-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8800 Update tag for DQM-Integration to V00-05-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8797 Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8803 Update tag for RecoBTag-Combined to V01-19-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8794 Add fix for segfault in Min Bias
  herwig7.spec
  herwig_MB.patch
Labels: tests-approved, externals-approved, orp-approved, generators-approved, fully-signed

#8806 [ROOT630] Root update v6 30 00 patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8808 [ROOt630] Root update v6.30.01
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8805 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8814 Update tag for IOPool-Input to V00-03-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8811 [G4] Update Geant4 to 11.1.ref10
  geant4.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8807 [XRootD] Update t version 5.6.3
  xrootd.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8813 Update yaml-cpp.spec
  yaml-cpp.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8815 Update tag for RecoTauTag-TrainingFiles to V00-08-00
  data/cmsswdata.txt
Labels: externals-approved, orp-approved, fully-signed, tests-started, requires-external

#8818 [BuildRules] Fix running alpaka-backend tests
  scram-project-build.file
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8816 [ROOT6] Updated ROOT to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8817 [ROOT630] ROOT update v6 30 00 patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8819 add clang-uml for making class diagrams
  clang-uml.spec
  cmssw-tool-conf.spec
  scram-tools.file/tools/clang-uml/clang-uml.xml
Labels: tests-approved, externals-approved, fully-signed, orp-pending, tests-external-failure

#8809 madgraph5amcatnlo: use external collier and ninja instead of downloading them
  collier.spec
  gosamcontrib.spec
  madgraph5amcatnlo-config.patch
  madgraph5amcatnlo.spec
Labels: tests-approved, externals-approved, generators-approved, fully-signed, orp-pending, requires-external

#8820 Changes needed for ASAN/UBSAN ROOTX IBs
  SCRAMV1.spec
  cmssw-queue-override.file
  scram-project-build.file
  scram-tools.file/tools/gcc/gcc-cxxcompiler.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8824 Update tag for RecoEgamma-ElectronIdentification to V01-13-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8831 [G4] Update geant4 to 11.2.cand02
  geant4.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending

#8830 Updated root to tip of branch master
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#8828 Update valgrind to 3.22
  valgrind.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8834 [hls] Fix for uninitialized/maybe-uninitialized warnings
  hls-fix-uninitialized.patch
  hls.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8833 [hepmc] Enable c++17 std and fix deprecated std::iterator warnings
  hepmc.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8835 [hepmc3] Update to version 3.2.7
  hepmc3.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8836 [scipy] Fix prebuild commands
  pip/scipy.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8847 Update tag for RecoTracker-FinalTrackSelectors to V01-05-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8840 [LTO] Improve link time by using multiple process for linking
  compilation_flags_lto.file
  scram-project-build.file
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8846 Update CICADA external to v1.2.1
  CICADA.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending
