Repository cms-sw/cmsdist, pull requests merged in 2023-05, with the labels that each got.

#8480 openloops: Fixes for scon and python3
  openloops-py3.patch
  openloops.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8487 Fix for llvm-static checks
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#8486 [G4Vecgeom] Update Geant4 11.1.ref04
  geant4.spec
Labels: externals-approved, fully-signed, tests-started, orp-pending

#8489 Update tag for DataFormats-FEDRawData to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8485 fastjet 3.4.1 and fastjet-contrib 1.051
  fastjet-contrib.spec
  fastjet.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8490 Update xrootd to version 5.5.4
  scram-tools.file/tools/xrootd/xrootd.xml
  xrootd.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8491 Update tag for L1Trigger-Phase2L1ParticleFlow to V00-05-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8492 Update tag for RecoBTag-Combined to V01-17-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8483 Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8497 Updated root to tip of branch v6-28-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8498 Root update master 20230505
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8500 Update tag for DataFormats-L1TGlobal to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: tests-pending, externals-approved, fully-signed, orp-pending

#8501 Added RecoPPS-Local data package
  cmsswdata.spec
  data/cmsswdata.txt
  data/data-RecoPPS-Local.file
  rpm-preamble.file
Labels: externals-approved, fully-signed, tests-started, orp-pending

#8499 [com-common] script to set up venv in CMS environment
  cms-common.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8495 Update tag for RecoBTag-Combined to V01-17-00 [CMSSW_13_1_X]
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8493 Update tag for RecoBTag-Combined to V01-17-00 [CMSSW_13_0_X]
  data/cmsswdata.txt
Labels: tests-pending, externals-approved, orp-approved, fully-signed

#8484 Update XRootD to 5.x in CMSSW 10_6_X
  pip/requirements.txt
  python_tools.spec
  root.spec
  rpm-preamble.file
  xrootd-toolfile.spec
  xrootd.spec
Labels: tests-rejected, externals-approved, orp-approved, fully-signed, requires-external

#8504 Update tag for DataFormats-HLTReco to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8509 cxxmodule: ignore pybind11/eigen headers
  pcm_util.spec
  pip/pybind11.file
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8508 Updated scram to support site based project/runtime hooks
  SCRAMV1.spec
  SCRAMV2.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8506 [ROOT628] Root update v6 28 00 patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8510 Update tag for L1Trigger-Phase2L1ParticleFlow to V00-06-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8507 Rivet 3.1.8 & YODA 1.9.8
  rivet-140-313.patch
  rivet-disable-doc.patch
  rivet.spec
  yoda.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8513 [ROOT628] Updated root to tip of branch v6-28-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8512 [ROOT6] Root update master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8519 Update tag for Configuration-Generator to V01-06-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8524 [BuildRules] USe nvidia-drivers LIBDIR for compatibility drivers
  cmssw-drop-tools.file
  scram-project-build.file
  scram-tools.file/tools/cuda/nvidia-drivers.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8514 Update ROOT in master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8517 Fix unpacking oracle/bazel sources for for RPM 4.18
  bazel.spec
  oracle.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#8525 [LLVM16] Testing llvm16.0.3 in CLANG IBs
  llvm.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, backport-ok

#8515 Roll back to CUDA 12.0.1 [gcc 12]
  cuda.spec
  ucx.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending, requires-external

#8526 [GCC] Update to GCC 12.3.1
  gcc.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8523 [10_6_X] Update (add) tag for Configuration-Generator to V01-06-00
  data/cmsswdata.txt
Labels: tests-approved, generators-pending, orp-approved, externals-pending, pending-signatures

#8528 [13_0_X] Update tag for Configuration-Generator to V01-06-00
  data/cmsswdata.txt
Labels: tests-approved, orp-approved, externals-pending, pending-signatures

#8520 [13_1_X} Update tag for Configuration-Generator to V01-06-00
  data/cmsswdata.txt
Labels: tests-approved, orp-approved, externals-pending, pending-signatures
