Repository cms-sw/cmsdist, pull requests merged in 2023-01, with the labels that each got.

#8242 [BuildRules] Added support to skip header consistency checks for selected files
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8241 Update root 6.26
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8243 Sync LTO changes to master but keep LTO disabled by default
  compilation_flags.file
  compilation_flags_lto.file
  dd4hep.spec
  geant4.spec
  scram-project-build.file
  scram-tools.file/tool-env.file
  scram-tools.file/tools/gcc/gcc-cxxcompiler.xml
  vecgeom.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8244 sync lto changes and enable lto for lto branch
  compilation_flags.file
  compilation_flags_lto.file
  dd4hep.spec
  geant4.spec
  scram-project-build.file
  scram-tools.file/tool-env.file
  vecgeom.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8246 use INCLUDE instead of IMPORT: to fix recursive parsing issue
  cmssw-patch.spec
  cmssw.spec
  coral.spec
  fwlite.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8247 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8251 [G4][11.1.0] Fixed run time problem in hadron elastic process
  geant4.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8254 [SCRAM] Properly restore and set the build time env
  SCRAMV1.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8252 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8255 BuildRules] Fix alpaka tests command names
  scram-project-build.file
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8256 [BuildRules] Use default compiler for alpaka/serial dev.cc files
  scram-project-build.file
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8257 Update tag for RecoTracker-MkFit to V00-11-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8261 [ROOT628] Root update v6 28 00 patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8259 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8262 Bug fix: Added back scram build runtests_TESTNAME support
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8263 crab-dev - crabclient v3.230124, crabserver v3.221205
  crab-dev.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8264 [BuildRules] Allow packages to export lib even if there are no cxx files
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8265 use python3 for root tools
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8266 Set the CXXFLAGS for the host compiler when using ROCm libraries
  scram-tools.file/tools/rocm/rocm.xml
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8267 [ROOT626] Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8268 [BuildRules] First implementation of RocM build rules
  scram-project-build.file
  scram-tools.file/tools/rocm/rocm.xml
Labels: tests-approved, externals-approved, fully-signed, orp-pending, requires-external

#8270 [buildrules] disable USE_CMS_DEPRECATED only for cmssw 12 and below
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8271 [Buildrules] Treat ROCM_CXXFLAGS/LDFLAGS as valid compiler flags
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8272 [SCRAM] Fix for iftool with !name
  SCRAMV1.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8274 [BuildRules] Use hipcc to link product which has hip.cc sources
  scram-project-build.file
Labels: externals-approved, fully-signed, tests-started, orp-pending

#8273 Update to ROCm 5.4.2 and TBB 2021.8.0
  rocm.spec
  scram-tools.file/tools/rocm/rocm.xml
  tbb.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8277 [ROOT626] Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending

#8276 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending
