Repository cms-sw/cmsdist, pull requests merged in 2023-04, with the labels that each got.

#8416 bump crab-prod to v3.230227
  crab-pre.spec
  crab-prod.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8422 Update tag for RecoBTag-Combined to V01-15-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8420 [PGO] Initial changes to support PGO builds
  cmssw-patch-build.file
  cmssw-tool-conf.spec
  compilation_flags_pgo.file
  dd4hep.spec
  g4hepem.spec
  geant4.spec
  pgo/cmsdist_packages.py
  rpm-preamble.file
  scram-project-build.file
  scram-tools.file/tool-env.file
  scram-tools.file/tools/gcc/gcc-cxxcompiler.xml
  scram-tools.file/tools/geant4/env.sh
  scram-tools.file/tools/llvm/llvm-cxxcompiler.xml
  vecgeom.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8425 [ROOT628] Updated root to tip of branch v6-28-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8427 bump crab-dev to latest tag
  crab-dev.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8426 Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8423 [G12] Update GCC and UCX
  gcc.spec
  ucx.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8424 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8430 PGO: CMSSW_PGO_DIRECTORY only for pgo generation
  pgo/cmsdist_packages.py
  pgo/compilation_flags_pgo.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8419 Update hwloc to version 2.9.1
  hwloc.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8432 bump crab-prod to v3.230404
  crab-prod.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8431 [GCC12] Apply patch for spurious Warray-bounds diagnostics
  gcc.spec
  scram-tools.file/tools/gcc/env.sh
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending, requires-external

#8296 Update gcc 12 builds to CUDA 12.1
  cuda.spec
  cudnn.spec
  onnxruntime.spec
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8415 Update G4 11.1.1, vecgeom 1.2.1, clhep 2.4.6 and G4-data
  clhep.spec
  geant4-G4EMLOW.spec
  geant4-G4PARTICLEXS.spec
  geant4.spec
  scram-tools.file/tools/geant4/geant4vis.xml
  scram-tools.file/tools/vecgeom/vecgeom.xml
  vecgeom.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8397 Update onnxruntime to 1.14.1
  onnxruntime.spec
Labels: tests-approved, orp-approved, externals-pending, pending-signatures, requires-external

#8434 Updated root to tip of branch v6-28-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8436 Update tag for RecoBTag-Combined to V01-15-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8435 Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8433 Updated root to tip of branch master
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#8437 created cmssw-el[5,6,7] scripts
  cmssw-osenv.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8438 Update tag for Configuration-Generator to V01-03-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8440 Update tag for Configuration-Generator to V01-04-00
  data/cmsswdata.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8439 [106X] Update tag for Configuration-Generator to V01-04-00
  data/cmsswdata.txt
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external, backport-ok

#8441 bump crab client to v3.230417
  crab-dev.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8443 [ROOT6] Update root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8444 [ROOT628] Update root to tip of branch v6-28-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8448 [BuildRules] Rocm/Cuda unit test improvement
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8450 Update sherpa to 2.2.15
  sherpa.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8449 [BuildRules] cuda/rocm tests and multi-vec env selection
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8454 bump CRABClient to v3.230417
  crab-prod.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8455 Update llvmlite to v0.41.0dev0 which has llvm14 support
  pip/llvmlite.file
  pip/requirements.txt
  py3-llvmlite-14.patch
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8453 [BuildRules] allow to enable disable dedicated unit test directory
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8452 [13.0][BuildRules] Improved unit testing for gpu/rocm/alpaka based tests
  scram-project-build.file
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8456 [13.0.X] Backport SCRAM V3_00_60 into CMSSW_13_0_X
  SCRAMV1.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8457 Update tag for RecoBTag-Combined to V01-16-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8459 Update RecoMuon-TrackerSeedGenerator to V00-05-00
  data/cmsswdata.txt
Labels: tests-approved, orp-approved, externals-pending, pending-signatures

#8460 [Backport 13_0] Update tag for RecoBTag-Combined to V01-16-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8461 [Backport 13_0] Update RecoMuon-TrackerSeedGenerator to V00-05-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8464 Mount /etc/pki/ca-trust from host to avoid rebuilding containers with updated trusted ca
  cmssw-osenv.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8462 [ROOT6] Root update master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8463 [ROOT628] Root update v6 28 00 patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8465 Update tag for Configuration-Generator to V01-05-00
  data/cmsswdata.txt
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8466 Search for unpack containers under /cvmfs/singularity.opensciencegrid.org too
  cmssw-osenv.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8467 [106X] Update tag for Configuration-Generator to V01-05-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#8451 Drop mxnet (cms-sw/cmssw#30432)
  archive/mxnet-predict.spec
  cmssw-tool-conf.spec
  python_tools.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#8469 llvm does not support -fno-fat-lto-objects
  scram-tools.file/tools/llvm/llvm-cxxcompiler.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#8213 Update LLVM to version 14.0.6
  llvm.spec
  pip/llvmlite.file
  pip/requirements.txt
  py3-dxr.spec
  py3-llvmlite-fpic-flag.patch
  py3-llvmlite-removeMethod.patch
  py3-llvmlite-version.patch
  rust-libstdc.patch
  rust.spec
  scram-tools.file/tools/llvm/llvm-ccompiler.xml
  scram-tools.file/tools/llvm/llvm-cxxcompiler.xml
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#8471 [rust] Delete .git files which are breaking slc7 builds
  rust.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8470 Update to CUDA 12.1.1 [gcc12 builds]
  cuda.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8473 drop numba and llvmlite
  pip/requirements.txt
  python/setup.py
  python_tools.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#8476 Update tag for DQM-EcalMonitorClient to V00-03-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8477 Update tag for DQM-EcalMonitorClient to V00-03-00 [13_0_X]
  data/cmsswdata.txt
Labels: tests-approved, orp-approved, externals-pending, pending-signatures

#8479 Update tag for DataFormats-Common to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8478 build google-benchmark with -fPIE
  google-benchmark-gcc11.patch
  google-benchmark.spec
  scram-tools.file/tools/google-benchmark/google-benchmark.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending
