Repository cms-sw/cmsdist, pull requests merged in 2023-10, with the labels that each got.

#8731 [SCRAMV1] Fix for PGO/Multivec env setup
  SCRAMV1.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8733 [13.2][SCRAMV1] Fix for PGO/Multivec env setup
  SCRAMV1.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending, backport-ok

#8736 Update tag for DataFormats-DetId to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8735 Updated root to tip of branch v6-28-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8740 Update py3-avro: Contains fix for improper Input Validation
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8745 Update tag for DQM-Integration to V00-04-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8744 Update tag for RecoEgamma-EgammaPhotonProducers to V00-04-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8728 [10.6.X] Add patches to propagate lhe numbering through herwig
  LHEEventNum.patch
  LHEEventNumFxFx.patch
  LesHouchesFileReader.patch
  herwig7.spec
  thepeg.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external, backport-ok

#8746 bump crab-dev to v3.231010
  crab-dev.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8750 Update tag for RecoBTag-Combined to V01-18-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8751 Update tag for GeneratorInterface-EvtGenInterface to V02-07-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8753 [12.4.X] GeneratorInterface-EvtGenInterface to V02-07-00
  data/cmsswdata.txt
Labels: tests-pending, externals-approved, orp-approved, fully-signed, backport-ok

#8754 [13.0] GeneratorInterface-EvtGenInterface to V02-07-00
  data/cmsswdata.txt
Labels: tests-pending, externals-approved, orp-approved, fully-signed, backport-ok

#8752 [ROOT628] Updated root to tip of branch v6-28-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8762 Update tag for IOPool-Input to V00-02-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8760 [ROOT630] Updated root to tip of branch v6-30-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8759 [ROOT628] Updated root to tip of branch v6-28-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8758 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8729 [12.4.X] Add patches to propagate lhe numbering through herwig
  LHEEventNum.patch
  LHEEventNumFxFx.patch
  LesHouchesFileReader.patch
  herwig7.spec
  thepeg.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external, backport-ok

#8764 Update libunwind to v1.7.2
  libunwind.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8748 [CLHEP] Update to version 2.4.7.1
  clhep.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#8765 Update GitPython to version 3.1.37
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8766 [DEVEL] drop -Wno-deprecated and -Wno-deprecated-copy flags
  scram-tools.file/tools/gcc/gcc-cxxcompiler.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8768 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8769 [ROOT630] Updated root to tip of branch v6-30-00-patches
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8771 cms-git-tools: Introduce cms-squash-topic
  cms-git-tools.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#8767 Update CUDA to support Pascal, Volta, Turing, Ampere and Lovelace GPUs
  cuda-flags.file
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8741 [G4] Update geant4 to 11.1.ref09
  dd4hep.spec
  geant4.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8775 [G4] Reorder the vecgeom flag to avoid automatic forward port
  geant4.spec
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8772 clhep: Build with c++17 i.e. default std used for building cmssw
  clhep.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8770 [ROOT628] Updated root to tip of branch v6-28-00-patches
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8781 Update CICADA version
  CICADA.spec
Labels: tests-approved, orp-approved, externals-pending, pending-signatures

#8782 Mark the `TriangularSolverMatrix` "kernel" functions as `EIGEN_DEVICE_FUNC`
  eigen.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8778 Updated root to tip of branch v6-28-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#8779 Updated root to tip of branch v6-30-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending, requires-external

#8780 Add conifer external
  cmssw-tool-conf.spec
  conifer.spec
  scram-tools.file/tools/conifer/conifer.xml
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8788 [XRootD] Update to version 5.6.2
  xrootd.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8786 Update conifer version
  conifer.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8787 [LLVM] Update to version 17.0.3
  llvm.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8777 Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending, requires-external

#8789 [Geant4] G4TransportationWithMsc: Always update momentum direction
  geant4.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8792 bump CRABClient v3.231010 to prod. Previos prod to pre
  crab-pre.spec
  crab-prod.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8793 Update crab-dev to v3.230130
  crab-dev.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8791 [LLVM] Update to version 17.0.3
  llvm.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending, backport-ok
