Repository cms-sw/cmsdist, pull requests merged in 2024-09, with the labels that each got.

#9382 [ROOT632] Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9383 BuildRules: add default test path for cuda/rocm unit tests
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9381 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9389 cmssw-osenv: added extra paths to mount; set LC_ALL=C
  cmssw-osenv.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9386 [LLVM] Update to version 18.1.6
  clang-uml.spec
  llvm.spec
  py3-dxr-Markup.patch
  py3-dxr.spec
  scram-tools.file/tools/llvm/llvm-cxxcompiler.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9308 [12_4_X] Bump cepgen version to 1.2.5
  cepgen.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external

#9398 [ROOT632] Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9400 [BuildRules] new build targets to enable/disable alpaka backends
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9399 [ROOT6] Updated root to tip of branch master with llvm18
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#9241 [TF] Update TF v2.16.1
  abseil-cpp.spec
  bazel-absl.patch
  pip/blosc2.file
  pip/keras.file
  pip/numpy.file
  pip/optree.file
  pip/requirements.txt
  tensorflow-sources.file
  tensorflow-sources.spec
  tensorflow-xla-runtime.spec
  tensorflow.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9395 Update some Python packages following dependabot alert
  pip/aiohappyeyeballs.file
  pip/aiohttp.file
  pip/cryptography.file
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9401 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9402 [ROOT632] Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#9403 Fix TensorFlow for AArch64
  tensorflow-sources.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9409 Set default keras backend at runtime
  pip/keras.file
  scram-tools.file/tools/tensorflow/tensorflow.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9411 [Davix] Update to version 0.8.7
  davix.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9406 Update gosamcontrib version
  gosamcontrib-module-patch.patch
  gosamcontrib.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9413 [rivet] Apply missing header VetoedFinalState.hh change
  rivet.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9415 [PY312] Fix for fix for TF 2.16
  tensorflow-sources.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9416 [py312][xrootd] disable python binding for slc7 due to openssl version 1.0.2
  xrootd.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9410 [PY312] Update various base level tools e.g zlib, xz, cmake and more
  autotools.spec
  bz2lib.spec
  cmake.spec
  curl.spec
  db6.spec
  expat.spec
  gdbm.spec
  gmake.spec
  libffi.spec
  libjpeg-turbo.spec
  libpng.spec
  libtiff.spec
  libuuid-2.40-disable-get_uuid_via_daemon.patch
  libuuid.spec
  m4-centos8.patch
  nasm.spec
  python3.spec
  sqlite.spec
  xz.spec
  zlib.spec
  zstd.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9414 [Python 3.12] Fixes for slc7
  freetype.spec
  matplotlib-freetype-slc7.patch
  mplsetup.patch
  pip/lockfile.file
  pip/matplotlib.file
  pip/optree.file
  pip/rfc3986-validator.file
  pip/scikit-build-core.file
  qhull.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9418 Set Tensorflow logging level to 3
  scram-tools.file/tools/tensorflow/tensorflow.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9427 [TF] fixes zlib headers
  tensorflow-sources.file
  tensorflow-sources.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9428 [ROOT632] Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9429 Update SCRAM, build rules and cms-common with rivet hook
  SCRAMV1.spec
  cms-common.spec
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9430 Updated root to tip of branch v6-30-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9384 [14.1]BuildRules: add default test path for cuda/rocm unit tests
  scram-project-build.file
Labels: tests-approved, externals-approved, fully-signed, orp-pending, backport-ok

#9385 [14.0]BuildRules: add default test path for cuda/rocm unit tests
  scram-project-build.file
Labels: tests-approved, externals-approved, fully-signed, orp-pending, backport-ok

#9434 [TF] Do not use mcpu/mtune native if CMS arch_build_flags are not set
  tensorflow-sources.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9436 Updated cms-common and git-tools
  cms-common.spec
  cms-git-tools.spec
  crab/crab-env.sh.file
  crab/crab-setup.sh.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9431 [14_1_X] Set Tensorflow logging level to 3
  scram-tools.file/tools/tensorflow/tensorflow.xml
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9432 [14_0_X] Set Tensorflow logging level to 3
  scram-tools.file/tools/tensorflow/tensorflow.xml
Labels: tests-approved, externals-approved, fully-signed, orp-pending, backport-ok

#9437 Update hwloc to version 2.11.2
  hwloc.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9438 [TF] Update Tensorflow to 2.17.0 build with c++20 standard
  bazel-absl.patch
  bazel.spec
  eigen.spec
  flatbuffers.spec
  pip/requirements.txt
  scram-tools.file/tools/tensorflow/tensorflow-c.xml
  scram-tools.file/tools/tensorflow/tensorflow-executable_run_options.xml
  scram-tools.file/tools/tensorflow/tensorflow-runtime.xml
  scram-tools.file/tools/tensorflow/tensorflow-tf2xla.xml
  scram-tools.file/tools/tensorflow/tensorflow-xla_compiled_cpu_function.xml
  scram-tools.file/tools/tensorflow/tensorflow.xml
  tensorflow-sources.file
  tensorflow-sources.spec
  tensorflow-xla-runtime-absl.patch
  tensorflow-xla-runtime.spec
  tensorflow.spec
  tfaot-compile.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9439 Update crab-dev.spec
  crab-dev.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending
