Repository cms-sw/cmsdist, pull requests merged in 2024-11, with the labels that each got.

#9496 bump crab-dev.spec
  crab-dev.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9495 [rivet] fix to avoid invalid read
  rivet.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9497 [pypi] Update packages with security fixes
  pip/requirements.txt
  py3-onnx.patch
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9494 Update gdrcopy to v2.4.2
  gdrcopy.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9500 [ROOT632] Updated ROOT to tip of branch v6-32-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9501 Bump crab-prod to v3.241030
  crab-pre.spec
  crab-prod.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9499 [ROOT6] Updated ROOT to tip of branch master
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9508 [10.6.X] Backport the electron & photon energy correction file
  data/cmsswdata.txt
Labels: externals-approved, fully-signed, tests-started, orp-pending, backport-ok

#9503 Update Intel tools to oneAPI 2025.0
  icx.spec
  intel-vtune.spec
  scram-tools.file/tools/intel-vtune/intel-vtune.xml
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9510 cleanup intel-vtune; remove duplicate toolfile
  intel-vtune.spec
  scram-tools.file/tools/intel-vtune/intel-vtune.xml
Labels: externals-approved, fully-signed, tests-started, orp-pending

#9511 bump crab-dev.spec
  crab-dev.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9512 [ROOTMaster] Updated root to tip of branch master
  dd4hep.spec
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9513 [G4]Update to version 11.3.cand00 along with G4 dataset
  geant4-G4PhotonEvaporation.spec
  geant4-G4RadioactiveDecay.spec
  geant4.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external, tests-ib-failure

#9506 [13_2_X] Update tag for RecoBTag-Combined to V01-25-00
  data/cmsswdata.txt
Labels: tests-approved, orp-approved, externals-pending, pending-signatures, requires-external, backport-ok

#9515 pythia8: Drop cxxcompiler dependency as this cause duplicate cxxflags
  scram-tools.file/tools/pythia8/pythia8.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9516 [ROOT6.32] Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9514 [pythia6]Move pythia6_pdfdummy in to separate tool
  SCRAMV1.spec
  scram-project-build.file
  scram-tools.file/tools/pythia6/pythia6.xml
  scram-tools.file/tools/pythia6/pythia6_pdfdummy.xml
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external

#9517 Drop histobook: not used in cms and package has no update for 6 years
  pip/histbook.file
  pip/requirements.txt
  python_tools.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending, requires-external

#9519 py3-dxr: Fix for python 3.12
  py3-dxr.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9521 typo: fix pythia6_pdfdummy tool revision
  scram-tools.file/tools/pythia6/pythia6_pdfdummy.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9522 [ROOTMaster] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9523 [Master] Updated root to tip of branch v6-30-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9520 Update ROCm to 6.2.4 and GPU targets
  rocm-rocrand.spec
  rocm.spec
  scram-tools.file/tools/rocm/rocm.xml
Labels: tests-rejected, externals-approved, fully-signed, orp-pending

#9526 [Buildrules] Avoid duplicate compilation messages for BUILD_LOG=yes
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9527 Update hepdata-lib to v0.17.0
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9531 bump CRAB client and server version to v3.241125
  crab-dev.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9533 Enable as needed flag
  scram-tools.file/tools/gcc/env.sh
  scram-tools.file/tools/lhapdf/lhapdf.xml
  scram-tools.file/tools/pythia6/pythia6.xml
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#9536 SCRAM: Update scram tool info to show tool revision
  SCRAMV1.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9529 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#9505 [14_1_X] Update tag for RecoBTag-Combined to V01-25-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9537 [BuildRules]Make each per-Alpaka-backend library to depend on the main library
  scram-project-build.file
Labels: tests-rejected, externals-approved, fully-signed, orp-pending

#9540 update cms-tfaot: added revision in toolfiles
  pip/cms-tfaot.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9539 security fixes: update aiohttp and tornado
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending
