Repository cms-sw/cmsdist, pull requests merged in 2024-01, with the labels that each got.

#8918 move common flags in separate file
  scram-tool-conf.file
  scram-tools.file/tool-env.file
  scram-tools.file/toolfile.file
  toolflags.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8919 cmssw-osenv: Fix multi-command handling
  cmssw-osenv.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8920 celeritas: Disable OpenMP and fix the lib link order
  celeritas.spec
  scram-tools.file/tools/celeritas/celeritas.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#8921 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8923 opencv: Update to version 4.9.0 which contains C++20 fixes
  opencv.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8925 cmssw-elX: source cmsset_default.sh in the new shell
  cmssw-osenv.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8933 Update crab-dev.spec
  crab-dev.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8932 xrootd: Update to version 5.6.4
  xrootd.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8928 [ROOT6] Updated root to tip of branch master
  root.spec
  xrootd.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8940 move CRABClient v3.240110 to crab-prod
  crab-prod.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8939 PGO: Use env variables with fprofile-use instead of %q{VAR}
  scram-project-build.file
  scram-tools.file/tools/gcc/gcc-cxxcompiler.xml
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8924 [13.0.X] Upgrade lhapdf sets to 6.5.1c
  lhapdf.spec
  lhapdf_makeLinks.file
  lhapdf_pdfsetsindex.file
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#8946 Update tag for GeneratorInterface-EvtGenInterface to V02-08-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8942 Update dd4hep v01-27-02: Adapt to ROOT 6.31
  dd4hep.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8944 scram-tools: Fix for replacing `@VAR@` in toolfile; remove PGO-Profiles subdir
  scram-tools.file/bin/get_tools
  scram-tools.file/tools/gcc/gcc-cxxcompiler.xml
  scram-tools.file/tools/icc/intel-license.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8945 Python tools versions with security fixes updates
  pip/requirements.txt
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8936 Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending, requires-external

#8948 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8949 Updated root to tip of branch v6-30-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#8951 Support for psABI micro architectures
  cmssw-vectorization.file
  scram-project-build.file
  vecgeom-fix-vector.patch
  vectorization/cmsdist_packages.py
  vectorization/x86-64-v2.file
  vectorization/x86-64-v3.file
  vectorization/x86-64-v4.file
Labels: externals-approved, fully-signed, tests-started, orp-pending

#8947 Improve protobuf text_format output
  protobuf.spec
  protobuf_text_format.patch
Labels: tests-rejected, externals-approved, fully-signed, orp-pending, requires-external

#8954 Update tag for DataFormats-L1ScoutingRawData to V00-01-00
  cmsswdata.spec
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8955 Update tag for DataFormats-L1Scouting to V00-01-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8953 Update Millepede to V04-14-00
  millepede.spec
Labels: tests-approved, externals-approved, alca-approved, fully-signed, orp-pending, requires-external

#8956 Update tag for RecoMuon-MuonIdentification to V01-16-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8959 cms-common: fixed gsl runtime hook to include openblas libs
  cms-common.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8960 cms-common: Fix for gsl-config
  cms-common.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8958 Fix gsl-config so that by default it uses openblas lib
  gsl.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8962 cms-common: support for ignoring site specific hooks
  SCRAMV1.spec
  cms-common.spec
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8963 Update tag for HeterogeneousCore-SonicTriton to V00-03-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8964 Update tag for RecoBTag-Combined to V01-20-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8965 Update tag for RecoEcal-EgammaClusterProducers to V00-04-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8967 Update tag for RecoMET-METPUSubtraction to V01-03-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8966 Update tag for RecoEgamma-EgammaPhotonProducers to V00-05-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8961 Update py-pillow to 10.2.0
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8969 SCRAMV2: back ported ignoreing site hooks support to SCRAMV2
  SCRAMV2.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8971 cms-git-tools: Fix for squashed commits with Co-authored
  cms-git-tools.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8972 TF: make tensorflow_mkldnn_contraction_kernel configurable
  etc/build_options.py
  tensorflow-sources.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8974 [CRAB] Remove deployment of crab/examples
  crab-build.file
  crab-dev.spec
  crab-pre.spec
  crab-prod.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8977 [ROOT628] Update ROOT to tip of branch v6-28-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending
