Repository cms-sw/cmsdist, pull requests merged in 2024-02, with the labels that each got.

#8982 Update tag for RecoTauTag-TrainingFiles to V00-09-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#8979 Build gbl for multivectorization release due to its eigen dependency
  cmssw-vectorization.file
  gbl.spec
  scram-tools.file/tools/eigen/eigen.xml
  scram-tools.file/tools/gbl/vectorized.tmpl
  vectorization/cmsdist_packages.py
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8984 ROOT: Use rootcling instead of genreflex for root dict generation
  scram-project-build.file
  scram-tools.file/tools/root/env.sh
  scram-tools.file/tools/root/root.xml
  scram-tools.file/tools/root/rootrflx.xml
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8988 pypi: Update cryptography 42.0.2
  pip/requirements.txt
Labels: externals-approved, fully-signed, tests-started, orp-pending

#8992 [14_0_X] Fix GBL compilation for non-x64 architectures
  gbl.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#8991 [14.0.X] Buildrule: Fix emdplugin cache for multiarch builds
  scram-project-build.file
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending, backport

#8990 BuildRule: Fix emdplugin cache for multiarch builds
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8994 Update tag for DataFormats-Scouting to V00-03-00
  data/cmsswdata.txt
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#8981 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-approved, orp-approved, fully-signed, requires-external

#8993 Updated root to tip of branch v6-26-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8997 [14.0.X] BuildRules: Fixes for multi-arch and PGO
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending, backport

#8996 BuildRules: Fixes for multi-arch and PGO
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9004 [dependabot] Update grpcio and grpcio-tools to 1.60.1
  pip/requirements.txt
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9003 [master] Updated root to tip of branch v6-30-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8957 Update Alpaka to version 1.1.0
  alpaka.spec
  scram-tools.file/tools/alpaka/alpaka-rocm.xml
  scram-tools.file/tools/alpaka/alpaka.xml
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external

#9011 [PPC64LE] Use system openssl for py3-grpcio
  pip/grpcio.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9010 Update Alpaka to version 1.1.0 [14.0.x]
  alpaka.spec
  scram-tools.file/tools/alpaka/alpaka-rocm.xml
  scram-tools.file/tools/alpaka/alpaka.xml
Labels: orp-approved, externals-pending, pending-signatures, tests-started, requires-external, backport-ok

#9015 grpcio: Changes backported from TF 2.15 branch
  grpcio-absl-path.patch
  pip/grpcio.file
  rpm-preamble.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9021 eigen: Don't crash on empty tensor contraction
  eigen.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8929 [10.6.X] Add Collier package and use ninja from gosamcontrib for madgraph
  collier.spec
  gosamcontrib.spec
  madgraph5amcatnlo-config.patch
  madgraph5amcatnlo.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#8930 [12.4.X] Add Collier package and use ninja from gosamcontrib for madgraph
  collier.spec
  gosamcontrib.spec
  madgraph5amcatnlo-config.patch
  madgraph5amcatnlo.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9007 [12_4_X] Cherry-pick ROOT fixes for forward compatibility
  root.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#9009 [12_6_X] Cherry-pick ROOT fixes for forward compatibility
  root.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#9012 [106X] Update EvtGenInterface to V02-09-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9013 [12_4_X] Update EvtGenInterface to V02-09-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9014 [13_0_X] Update EvtGenInterface to V02-09-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9017 [13_0_X] Fix ROOT backwards compatibility (cms-sw/root#201)
  root.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#9018 [13_1_X] Fix ROOT backwards compatibility (cms-sw/root#202)
  root.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#9019 [13_2_X] Fix ROOT backwards compatibility (cms-sw/root#203)
  root.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#9020 [13_3_X] Fix ROOT backwards compatibility (cms-sw/root#204)
  root.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#8999 [ROOTMaster] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending, requires-external

#9024 Update geant4 to version 11.2.1
  geant4.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9030 CepGen 1.2.0
  cepgen.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9027 Updated root to tip of branch v6-28-00-patches
  root.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending, requires-external

#9026 Updated root to tip of branch v6-30-00-patches
  root.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending, requires-external

#9029 Update UTM to 0.12.0
  utm.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9035 [ROOT630] Update ROOT to tip of branch v6-30-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9036 [ROOT628] Update ROOT to tip of branch v6-28-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9038 [14_0_X] Update UTM to 0.12.0
  utm.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9006 Rivet 3.1.10 and Yoda 1.9.10
  rivet-analysis.patch
  rivet-deprecated-warn.patch
  rivet.spec
  yoda-deprecated-warn.patch
  yoda.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external, tests-external-failure
