Repository cms-sw/cmsdist, pull requests merged in 2024-05, with the labels that each got.

#9170 Fix unittest link flags for extra micro-arch
  scram-project-build.file
  scram-tool-conf.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#8938 Pythia 8.311
  evtgen-2.0.0.patch
  pythia8.spec
  pythia8_309-289.patch
Labels: tests-approved, externals-approved, orp-approved, generators-approved, fully-signed, requires-external, tests-external-failure

#9172 [BuildRules] Check for private header included from release area
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#9171 [14.0.x] Fix unittest link flags for extra micro-arch; fix private header
  scram-project-build.file
  scram-tool-conf.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, backport-ok

#9175 Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9156 Update several py3 packages following dependabot alerts
  gosam.spec
  pip/Pygments.file
  pip/annotated-types.file
  pip/anyio.file
  pip/argon2-cffi.file
  pip/arrow.file
  pip/attrs.file
  pip/awkward.file
  pip/backports-tarfile.file
  pip/build.file
  pip/cachecontrol.file
  pip/cffi.file
  pip/contourpy.file
  pip/cramjam.file
  pip/cryptography.file
  pip/dask-awkward.file
  pip/dulwich.file
  pip/expandvars.file
  pip/frozenlist.file
  pip/fsspec.file
  pip/h11.file
  pip/httpcore.file
  pip/httpx.file
  pip/jaraco-context.file
  pip/jaraco-functools.file
  pip/json5.file
  pip/jsonschema-specifications.file
  pip/jsonschema.file
  pip/jupyter-events.file
  pip/jupyter-lsp.file
  pip/jupyterlab-server.file
  pip/jupyterlab.file
  pip/keyring.file
  pip/maturin.file
  pip/notebook.file
  pip/onnxmltools.file
  pip/packaging.file
  pip/pandas.file
  pip/poetry-cyclic-deps.patch
  pip/poetry.file
  pip/pydantic-core.file
  pip/pydantic.file
  pip/referencing.file
  pip/requirements.txt
  pip/rpds-py.file
  pip/scikit-build-core.file
  pip/scikit-build.file
  pip/setuptools-rust.file
  pip/uproot.file
  pip/urllib3.file
  pip/yarl.file
  py3-onnx.patch
  py3-pip.spec
  py3-setuptools.spec
  rust.spec
Labels: hold, externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#9166 simplify micro arch selection; set default micro arch to x86-64-v2
  OpenBLAS.spec
  cmssw-vectorization.file
  fastjet.spec
  gbl.spec
  lwtnn.spec
  microarch_flags.file
  opencv.spec
  pgo/cmsdist_packages.py
  pytorch.spec
  rivet.spec
  scram-project-build.file
  scram-tool-conf.file
  scram-tools.file/tool-env.file
  tensorflow-sources.file
  tensorflow-sources.spec
  tensorflow-xla-runtime.spec
  vecgeom.spec
  vectorization/cmsdist_packages.py
  zlib.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9178 cmssw-tool-conf: Added explicit dependency on tensorflow , fastjet,zlib, rivet
  cmssw-tool-conf.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9176 Followup after #9156
  json.spec
  pip/contourpy.file
  rapidjson.spec
  rust.spec
  xrootd.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9181 BuildRule: Read individual .d dependency files if .dep is missing due link error
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9185 Update valgrid to version 3.23.0
  valgrind.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9182 [14.0] Read individual .d dependency files if .dep is missing due link error
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, backport-ok

#9186 [14.0.x] valgrind version 3.23.0
  valgrind.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, backport-ok

#9187 Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9188 Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9190 Added mozearch clang-plugin to generate mozsearch indexing
  cmssw-tool-conf.spec
  mozsearch-gcc-toolchain.patch
  mozsearch.spec
  scram-project-build.file
  scram-tools.file/tools/mozsearch/mozsearch.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9191 cmssw-osenv: make sure to use scram v2 in el6 env
  cmssw-osenv.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9189 Updated root to tip of branch v6-30-00-patches
  root.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9193 [HLS] Apply constexpr patch
  hls-fix-constexpr.patch
  hls.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending, requires-external

#9195 bump crab-dev.spec
  crab-dev.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9177 Update L1Trigger-L1TMuon to V01-10-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#9197 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9198 [ROOT632] Root update v6 32 00 patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9196 updated pip pkg: requests, Jinja2, tqdm, Werkzeug
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9205 Change the default optimisation level to `-O3`
  scram-tools.file/tools/gcc/gcc-ccompiler.xml
  scram-tools.file/tools/gcc/gcc-cxxcompiler.xml
  scram-tools.file/tools/gcc/gcc-f77compiler.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9199 [Master] Updated root to tip of branch v6-30-00-patches in master
  root.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending

#9208 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9209 [ROOT632] Root update v6 32 00 patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9206 Add collier toolfile
  scram-tools.file/tools/collier/collier.xml
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9211 [ROOT632] Root update v6 32 00 patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9212 [14.0.X] Update tag for RecoMuon-TrackerSeedGenerator to V00-07-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, fully-signed, orp-pending, backport-ok, hlt-integration

#9216 Downgrade grpcio-tools to 1.60.1 to match grpcio
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending
