Repository cms-sw/cmsdist, pull requests merged in 2024-08, with the labels that each got.

#9336 Fix bazel recipe
  bazel.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9337 [BuildRule] set scram target to auto when multi-target is enabled
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9340 [BuildRule] Properly build test dependencies before running test command
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9338 [14.0.X] set scram target to auto when multi-target is enabled
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, backport

#9341 TF2.15: Apply abseil aarch64 patch
  abseil-cpp.spec
  tensorflow-sources.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9342 BUILDRULES: roll back to V09-04-15
  scram-project-build.file
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#9344 [BuildRules] Various fixes
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9345 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9346 [ROOT632] Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9350 Add ruff as external
  cmssw-tools.spec
  ruff.spec
  scram-tools.file/tools/ruff/ruff.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9352 [13_2_X] Update tag for RecoBTag-Combined to V01-22-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#9349 [14.0.x][BuildRules] Various fixes
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, backport-ok

#9351 do not create symlinks if system gcc is used
  scram-tools.file/tools/gcc/gcc-plugin.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9357 cleanup SCRAM_TARGETS if not multi-vector build
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9358 [BuildRules] Use config/Self.xml to check for multi-targets instead of .SCRAM/arch/MakeData/variables.mk
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9353 Update ROCm targets
  scram-tools.file/tools/rocm/rocm.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9356 Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9354 [ROOTMaster] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9355 [Master] Updated root to tip of branch v6-30-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9360 Add eigen/include in INCLUDE path
  scram-tools.file/tools/eigen/eigen.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9359 SCRAM to support extra config option and fix for multi-target release deployment
  SCRAMV1.spec
  SCRAMV2.spec
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9361 Updating cms-common: Use SCRAM V3 as default if system python3 is available
  cms-common.spec
  cmssw-osenv.spec
Labels: hold, externals-pending, pending-signatures, tests-started, orp-pending

#9362 reset SCRAM_TARGETS for non-vectorize builds
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9364 force use SCRAM V2 for cmssw-el6 containers
  cmssw-osenv.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9363 [14.0.X] Update SCRAM and sync back multi-arch changes from 14.1.X
  SCRAMV1.spec
  SCRAMV2.spec
  cmssw-vectorization.file
  scram-project-build.file
  scram-tool-conf.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9365 SCRAM: Updated documentation for multi-archs env setup
  SCRAMV1.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9366 [14.0.x] Added explicit tensorflow dependency
  cmssw-tool-conf.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9367 [rootmaster] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9369 [ROOT632] Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9371 SCRAM: fix scram list when search project with part of version string
  SCRAMV1.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9373 SCRAMV1: Updated scram version to V3_00_75
  SCRAMV1.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9374 [14.0.X][SCRAM] Backported latest scram version
  SCRAMV1.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, backport-ok

#9375 [cms-common] Always use SCRAM V2 for slc6
  cms-common.spec
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#9376 Backport alpaka#2295: Fix memcpy warning
  alpaka.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending, tests-ib-failure

#9379 [G4] Update Geant4 to version 11.2.ref07
  geant4.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9377 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9378 [ROOT632] Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending
