Repository cms-sw/cmsdist, pull requests merged in 2024-10, with the labels that each got.

#9442 Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9443 madgraph5amcatnlo: remove distutils deps needed for py312
  madgraph5amcatnlo-py312.patch
  madgraph5amcatnlo.spec
Labels: externals-approved, fully-signed, tests-started, orp-pending

#9445 Update py3-correctionlib to version 2.6.4
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9447 Fixes release sources usage information
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9441 [ROOTMaster] Updated root to tip of branch master
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#9446 [14_1_X] Update py3-correctionlib to version 2.6.4
  pip/requirements.txt
Labels: tests-approved, externals-approved, fully-signed, orp-pending, backport-ok

#9451 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#9453 update dwz, fix g4hepem and celeritas deps
  celeritas.spec
  dwz.spec
  g4hepem.spec
  geant4.spec
  scram-tools.file/tools/celeritas/celeritas.xml
  scram-tools.file/tools/geant4/env.sh
  scram-tools.file/tools/geant4/geant4_interface.xml
  scram/tool-conf.file
  scram/toolfile.file
  toolflags.file
  vecgeom-opt.file
  xxhash.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9455 g4hepem/dd4hep: Added xerces-c/expat dep
  dd4hep.spec
  g4hepem.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9452 Update geant4 to version 11.2.ref08, update datasets
  dd4hep.spec
  geant4-G4EMLOW.spec
  geant4-G4ENSDFSTATE.spec
  geant4-G4PhotonEvaporation.spec
  geant4-G4RadioactiveDecay.spec
  geant4.spec
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#9456 [ThePeg] build with cms default standard i.e. c++20
  herwig7.spec
  thepeg.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9407 [12.4.X] Update gosamcontrib version
  gosamcontrib-module-patch.patch
  gosamcontrib.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#9454 [ROOT6] Root update master 20241006
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#9459 [ROOTMaster] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9460 Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9466 [ROOT6] Root update master 20241015
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9463 [SCRAM] scram setup to create external symlinks
  SCRAMV1.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9464 Unify geat4 deps and vecgeom selection
  celeritas.spec
  dd4hep.spec
  g4hepem.spec
  geant4-deps.file
  geant4.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9469 add CMS_X_SANITIZER macros
  scram-tools.file/tools/gcc/sanitizer-flags-asan.xml
  scram-tools.file/tools/gcc/sanitizer-flags-ubsan.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9470 [vdt]Apply patch to avoid UBSan signed integer overflow error
  vdt-integer-overflow.patch
  vdt.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending, requires-external

#9473 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9474 Update crab-prod and crab-pre to the latest version
  crab-pre.spec
  crab-prod.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9475 xrootd: Update to version 5.7.1
  xrootd.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9476 Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9479 Updated root to tip of branch v6-30-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9480 [ROOT632] Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9482 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9483 [ROOTMaster] Updated root to tip of branch master
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9486 [106X] Update Configuration-Generator to V01-09-00
  data/cmsswdata.txt
Labels: tests-approved, orp-approved, externals-pending, pending-signatures, backport-ok

#9449 [10.6.X] Backport the electron & photon energy correction file updates for 10_6_X/gcc700
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external

#9487 [DEVEL] Fix symlinks for PATH and PYTHONPATH
  scram-project-build.file
  scram-tools.file/tools/cmssw/cmssw.xml
  scram-tools.file/tools/coral/coral.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9488 Fix symlinks for PATH and PYTHONPATH
  scram-project-build.file
  scram-tools.file/tools/OpenBLAS/vectorized.tmpl
  scram-tools.file/tools/lwtnn/vectorized.tmpl
  scram-tools.file/tools/opencv/vectorized.tmpl
  scram-tools.file/tools/rivet/rivet.xml
  scram-tools.file/tools/rivet/vectorized.tmpl
  scram-tools.file/tools/tensorflow/vectorized.tmpl
  scram/tool-conf-src.file
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending, backport-ok

#9489 Bump crab-dev to v3.241029
  crab-dev.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9481 Rivet 4.0.1 and YODA 2.0.1
  rivet-duplicate-libs.patch
  rivet.spec
  yoda.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending
