Repository cms-sw/cmsdist, pull requests merged in 2024-04, with the labels that each got.

#9107 tensorflow-xla-runtime: fix for TF 2.15
  tensorflow-xla-runtime.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9110 Update tag for PhysicsTools-NanoAOD to V01-04-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#9108 Update cms-tfaot and test models.
  pip/cms-tfaot.file
  pip/requirements.txt
  tfaot-model-test-multi.spec
  tfaot-model-test-simple.spec
Labels: tests-approved, orp-approved, externals-pending, pending-signatures, requires-external

#9114 Update crab-dev to v4.230404 (fix for external/objs-)
  crab-dev.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9113 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending

#9115 [BuildRules] Export cuda/rocm static libs from the base release
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9117 [14.0][BuildRules] Export cuda/rocm static libs from the base release
  scram-project-build.file
Labels: tests-approved, externals-approved, fully-signed, orp-pending, backport-ok

#9119 [13.2][BuildRules] Export cuda/rocm static libs from the base release
  scram-project-build.file
Labels: tests-approved, externals-approved, fully-signed, orp-pending, backport-ok

#9120 bump crabclient to v3.240404
  crab-pre.spec
  crab-prod.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9118 [13.3][BuildRules] Export cuda/rocm static libs from the base release
  scram-project-build.file
Labels: tests-approved, externals-approved, fully-signed, orp-pending, backport-ok

#9112 [ROOT]Updated root version to 6.30.06
  root.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending, tests-ib-failure

#9121 Build alpaka code in GPU-only mode
  scram-tools.file/tools/alpaka/alpaka-cuda.xml
  scram-tools.file/tools/alpaka/alpaka-rocm.xml
Labels: tests-rejected, externals-approved, fully-signed, orp-pending

#9125 Build alpaka code in GPU-only mode [14.0.x]
  scram-tools.file/tools/alpaka/alpaka-cuda.xml
  scram-tools.file/tools/alpaka/alpaka-rocm.xml
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external, backport-ok

#9127 Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9126 Update to CUDA 12.4.1
  cuda.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, tests-ib-failure

#9136 Update tag for RecoEgamma-PhotonIdentification to V01-08-00
  data/cmsswdata.txt
Labels: tests-approved, orp-approved, externals-pending, pending-signatures, backport-ok

#9137 Enable multi-arch build for unit tests
  SCRAMV1.spec
  scram-project-build.file
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9138 Update crab-dev to latest tag
  crab-dev.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9141 Rivet: use eigen flags; update rivet analysis path for multi-arch
  rivet.spec
  scram-project-build.file
  scram-tools.file/tools/cmssw/cmssw.xml
  scram-tools.file/tools/rivet/rivet.xml
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9134 Add NVML python bindings
  pip/requirements.txt
  python_tools.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9146 Add cmssw/external/lib to RIVET_ANALYSIS_PATH
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9140 [14.0.X] Update tag for RecoBTag-Combined to V01-21-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9147 Bump crab-prod to v3.240416 after validation in crab-dev
  crab-prod.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9142 [14.0.X] Backported fix for multiarch unit tests
  SCRAMV1.spec
  rivet.spec
  scram-project-build.file
  scram-tools.file/tools/cmssw/cmssw.xml
  scram-tools.file/tools/rivet/rivet.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, backport-ok

#9122 [14_1_X] Bumped CepGen version to 1.2.3
  cepgen.spec
Labels: tests-rejected, externals-approved, orp-approved, fully-signed, requires-external

#9149 cmssw-env: add --show-command option
  cmssw-osenv.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9143 Update ROCm to version 6.1.0
  rocm-rocrand.spec
  rocm.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external, tests-ib-failure

#9152 [ROOT632] Root update v6 32 00 patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9124 [13_0_X] Bumped CepGen version to 1.2.3
  cepgen.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external

#9123 [10_6_X] Bumped CepGen version to 1.2.3
  cepgen.spec
  cepgen_noroot.patch
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external

#9148 [14_0_X] Update tag for RecoBTag-Combined to V01-22-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9154 for multi-arch set SCRAM_TARGET to auto MULTIARCH/SKYLAKE otherwise to default
  SCRAMV1.spec
  cmssw-queue-override.file
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9145 Add NVML python bindings [14.0.x]
  pip/requirements.txt
  python_tools.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, urgent, backport-ok

#9155 Update Geant4 to 11.2.ref03
  geant4-G4PARTICLEXS.spec
  geant4.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9151 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending, requires-external

#9153 Revert "Update ROCm to version 6.1.0"
  rocm-rocrand.spec
  rocm.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#9158 [14.0.X] backport of multi-arch and scram os mismatch hook
  SCRAMV1.spec
  cms-common.spec
  cmssw-queue-override.file
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, backport-ok

#9161 scram-project-build: simple formating of config/Self.xml
  scram-project-build.file
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#9164 SCRAM: Only show non-empty error line at cmsenv time
  SCRAMV1.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9162 Updated root to tip of branch v6-30-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#9163 [14.0.X] config/Self.xml format update/fix
  SCRAMV1.spec
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, backport-ok

#9165 BuildRules: Fixes for PGO and biglib
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9167 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9168 [ROOT632] Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending
