Repository cms-sw/cmsdist, pull requests merged in 2024-07, with the labels that each got.

#9278 [ROOT632] Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9279 [G4] Update geant4 to 11.2.2
  geant4.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9276 [ROOTMaster] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9272 [14_0_X] Update AXOL1TL to v4.0.0
  AXOL1TL.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, urgent, backport-ok

#9111 Rivet 4.0.0 and YODA 2.0.0
  rivet-analysis.patch
  rivet-duplicate-libs.patch
  rivet.spec
  scram-tools.file/tools/hepmc3/hepmc3.xml
  scram-tools.file/tools/rivet/rivet.xml
  yoda.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending, requires-external

#9235 [14_0_X] Update L1Trigger-L1TMuon tag
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9231 Add CLUE external library.
  clue.spec
  cmssw-tools.spec
  scram-tools.file/tools/clue/clue.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9280 Add cms-cat.spec
  cms-cat.spec
  cmssw-tools.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending

#9283 Bump cepgen to 1.2.4
  cepgen.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9282 Drop crab nosort option; fizes for zsh
  cms-common.spec
  crab-build.file
  crab-dev.spec
  crab-pre.spec
  crab-prod.spec
  crab/crab-env.sh.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#9286 [ROOT632] Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9287 Update Intel tool to version 2024.1
  icx.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9277 Updated root to 6.30.08
  root.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending

#9290 Let icpx find the gcc installation
  scram-tools.file/tools/icx/env.sh
  scram-tools.file/tools/icx/icx-cxxcompiler.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9289 Certifi removes GLOBALTRUST root certificate
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9292 Update py3 zipp to 3.19.2
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9296 Adding missing deps for libunwind, libtiff and llvm
  libtiff.spec
  libunwind.spec
  llvm.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9295 [GCC13] Patch applied for c++20
  gcc.spec
Labels: tests-pending, externals-approved, fully-signed, orp-pending

#9288 Set c++20 as a default standard
  cpp-standard.file
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending, requires-external

#9299 [ROOT632] Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9302 BuildRule: export explicitly added alpaka backend deps
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9301 Add a tool to disable the `-Warray-bounds` flag
  scram-tools.file/tools/gcc/no-array-bounds-flag.xml
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9297 Update geant4 in master to 11.2.2
  geant4-G4PARTICLEXS.spec
  geant4.spec
Labels: tests-approved, externals-approved, simulation-approved, fully-signed, orp-pending

#9300 [Master] Updated root to tip of branch v6-30-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9298 [ROOTMaster] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9304 Fix for multi-arch: copy vectorized_packages.txt in to tool-conf
  scram/tool-conf.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9305 Bump cepgen version to 1.2.5
  cepgen.spec
Labels: tests-approved, externals-approved, generators-approved, fully-signed, orp-pending

#9309 [ROOT632] Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9310 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9306 [10_6_X + gcc700] Bump of cepgen version to 1.2.5
  cepgen.spec
  cepgen_noroot.patch
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#9311 hls: avoid arithmetic between different enumeration types
  hls-fix-constexpr.patch
  hls-fix-uninitialized.patch
  hls-fix.patch
  hls.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9320 [riscv] changes needed for using system-gcc and disabling pkgs
  cmssw-tools.spec
  form.spec
  gosamcontrib.spec
  herwig7.spec
  libzmq.spec
  llvm.spec
  professor2.spec
  python_tools.spec
  scram-tools.file/tools/gcc/gcc-ccompiler.xml
  scram-tools.file/tools/gcc/gcc-cxxcompiler.xml
  scram-tools.file/tools/gcc/gcc-f77compiler.xml
  scram-tools.file/tools/icx/icx-f77compiler.xml
  scram-tools.file/tools/llvm/llvm-ccompiler.xml
  scram-tools.file/tools/llvm/llvm-cxxcompiler.xml
  scram-tools.file/tools/llvm/llvm-f77compiler.xml
  scram-tools.file/tools/systemtools/root_cxxdefaults.xml
  scram/tool-conf-src.file
  sherpa.spec
  tfaot-models.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9313 [riscv]: update ucx, OpenBLAS, go
  OpenBLAS-disable-tests.patch
  OpenBLAS-fix-dynamic-arch.patch
  OpenBLAS.spec
  curl.spec
  go.spec
  ucx.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9293 [riscv] Update pytorch to version 2.4.0
  fmt.spec
  pytorch-cluster.spec
  pytorch-missing-braces.patch
  pytorch-scatter.spec
  pytorch-sparse.spec
  pytorch-system-fmt.patch
  pytorch.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#9322 [gcc13] drop pytorch-cuda-12_4 patch
  pytorch-cuda-12_4.patch
  pytorch.spec
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#9325 rpm-preamble: define cms_arch
  rpm-preamble.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9326 dasgoclient: Updated to version v02.05.52
  dasgoclient.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9323 [cepgen] Disable BoostWrapper addon
  cepgen.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9328 Fix cmsos for riscv64
  cms-common.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9319 Bazel: Use Java 17 for el8 and above
  bazel.spec
  java-env.spec
  tensorflow-sources.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9327 [llvm] add zstd deps to make sure it is not picked up from system
  llvm.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9318 Update xrootd to version 5.7.0
  isal.spec
  scram-tools.file/tools/isal/isal.xml
  xrootd.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9330 ofast-flag: -mrecip=none is only recognized for ppc64le and x86_64
  scram-tools.file/tools/gcc/ofast-flag.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9329 Fix xrootd for non-default arch
  isal.spec
  xrootd.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9332 gcc cxxflags: enable -fsigned-char -fsigned-bitfields for riscv64
  scram-tools.file/tools/gcc/env.sh
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9307 [13_0_X] Bump cepgen version to 1.2.5
  cepgen.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#9335 allow to drop tool for specific release e.g. drop ofast for NOFAST IB
  cmssw-queue-override.file
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9333 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9334 [ROOT632] Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending
