Repository cms-sw/cmsdist, pull requests merged in 2025-02, with the labels that each got.

#9657 [CMSSW_10_6_X] Update xrootd to version 5.7.2
  isal-toolfile.spec
  isal.spec
  xrootd.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#9655 [CMSSW_13_1_X] Update xrootd to version 5.7.2
  isal.spec
  scram-tools.file/tools/isal/isal.xml
  xrootd.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#9647 [CMSSW_13_2_X] Update xrootd to version 5.7.2
  isal.spec
  scram-tools.file/tools/isal/isal.xml
  xrootd.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#9646 [CMSSW_13_3_X] Update xrootd to version 5.7.2
  isal.spec
  scram-tools.file/tools/isal/isal.xml
  xrootd.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#9656 [CMSSW_12_4_X] Update xrootd to version 5.7.2
  isal.spec
  scram-tools.file/tools/isal/isal.xml
  xrootd.spec
  yoda.spec
Labels: tests-approved, orp-approved, externals-pending, pending-signatures

#9666 Added isal deps in to xrootd toolfile
  scram-tools.file/tools/xrootd/xrootd.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9665 [142x]Added isal deps in to xrootd toolfile
  scram-tools.file/tools/xrootd/xrootd.xml
Labels: tests-approved, externals-approved, fully-signed, orp-pending, backport

#9664 [141x]Added isal deps in to xrootd toolfile
  scram-tools.file/tools/xrootd/xrootd.xml
Labels: tests-approved, externals-approved, fully-signed, orp-pending, backport

#9663 [140x]Added isal deps in to xrootd toolfile
  scram-tools.file/tools/xrootd/xrootd.xml
Labels: tests-approved, externals-approved, fully-signed, orp-pending, backport

#9662 [133x]Added isal deps in to xrootd toolfile
  scram-tools.file/tools/xrootd/xrootd.xml
Labels: tests-approved, externals-approved, fully-signed, orp-pending, backport

#9661 [132x]Added isal deps in to xrootd toolfile
  scram-tools.file/tools/xrootd/xrootd.xml
Labels: tests-approved, externals-approved, fully-signed, orp-pending, backport

#9659 [124x]Fix xrootd toolfile touse isal instead of scitokens-cpp
  scram-tools.file/tools/xrootd/xrootd.xml
Labels: tests-approved, externals-approved, fully-signed, orp-pending, backport

#9658 [10.6.X] Explicitly added isal dependency
  cmssw-tool-conf.spec
  fwlite-tool-conf.spec
  xrootd-toolfile.spec
Labels: tests-approved, bug-fix, externals-approved, fully-signed, orp-pending

#9669 Update G4HepEm to latest tag
  g4hepem.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#8331 [10.6.X] backport PR7776 to 10_6_X gcc700
  lhapdf.spec
  lhapdf_makeLinks.file
  lhapdf_pdfsetsindex.file
Labels: tests-approved, externals-approved, orp-approved, generators-approved, fully-signed

#9668 [CMSSW_13_0_X] Update XRootD to version 5.7.2
  isal.spec
  scram-tools.file/tools/isal/isal.xml
  scram-tools.file/tools/xrootd/xrootd.xml
  xrootd.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#9639 libunwind master with fix for uninitialized access
  libunwind.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9676 cms-common: Fix for GREP_OPTION env
  cms-common.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#9670 [test] Update ROCm to version 6.3.2
  rocm.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#9673 [CMSSW_8_0_X] Update XRootD to version 4.12.9
  xrootd-toolfile.spec
  xrootd.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, tests-ib-failure

#9677 [GCC14] Patch CLUE to avoid using std::clamp
  clue-gcc14.patch
  clue.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9675 Update Vecgeom to v1.2.10
  vecgeom.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9680 Disable arry-bound errors for GCC 14
  scram-tools.file/tools/gcc/env.sh
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9684 [CUDART_X] Add libnvrtc-builtins to cuda-runtime
  cuda-runtime.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9682 Buildrules: alpaka: Do not add self dependency if package/src generates edm plugin
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9672 [CMSSW_9_4_X] Update XRootD to 4.12.9
  py2-pippkgs.spec
  py2-pippkgs_depscipy.spec
  tkonlinesw.spec
  xrootd-toolfile.spec
  xrootd.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending, tests-ib-failure

#9685 GCC13: Disable arry-bound errors for GCC 13
  scram-tools.file/tools/gcc/env.sh
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9689 Gperftools: compile without libunwind
  gperftools.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9690 fwlite: add FWCore/AbstractServices
  fwlite_build_set.file
Labels: tests-pending, externals-approved, fully-signed, orp-pending

#9691 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9686 [GCC14] Apply fix for https://gcc.gnu.org/bugzilla/show_bug.cgi?id=118817
  fakesystem.spec
  gcc.spec
  gcc14-fix118817.patch
  pip/pybind11.file
  pybind11-array-bound.patch
  scram-tools.file/tools/gcc/env.sh
  tbb.spec
  ucx.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9692 bump crab-dev to prod
  crab-pre.spec
  crab-prod.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9693 Update crab-dev.spec
  crab-dev.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9695 Bump conifer to 1.6
  conifer.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9683 Update hwloc to version 2.12.0
  hwloc.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9696 CPPUnit: Updated to latest 1.15.1 + changes
  cppunit.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9699 Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9698 Update Geant4 to 11.3.ref01
  geant4.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9702 [gcc14] Build meschach archive libs with -fPIC
  meschach-1.2b-fPIC.patch
  meschach.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9705 Updated cryptography to 44.0.1
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9703 Update zstd to version 1.5.7
  zstd.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9700 [15.0] Update root 6.32.11
  root.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending, tests-manual-override

#9697 Update hwloc to version 2.12.0 [15.0.x]
  hwloc.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending, backport-ok

#9704 Integrate latest fixes for G4HepEm
  g4hepem.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9706 TBB version v2022.0.0
  tbb.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9712 SCRAM: typo
  SCRAMV1.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9711 Coral: replace deprecated boost::filesystem::path::is_complete with is_absolute
  coral.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9714 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9713 boost:1.80: patch to avoid gcc14 usage of conversion operator warning
  boost.spec
  scram-tools.file/tools/boost/boost_header.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#9708 [DEVEL]Update boost to version 1.87.0
  boost.spec
Labels: tests-pending, externals-pending, pending-signatures, orp-pending, requires-external

#9717 ThePeg: fix warning for arithmetic between enumeration and float type
  thepeg-deprecated-warn.patch
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9719 vecgeom: Do not read destructed memory
  vecgeom.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9723 eigen: Fix enum arithmetic: changes from upstream
  eigen.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9724 [TF] patched tensorflow protobuf with non-virtual destructor
  tensorflow-sources.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending
