Repository cms-sw/cmsdist, pull requests merged in 2025-07, with the labels that each got.

#9960 Update/vec geom v2.0.0 rc6
  vecgeom-fix-vector.patch
  vecgeom.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9962 [ROOT636] Updated root to tip of branch v6-36-00-patches
  root.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9964 cms-common: Added cmsTraceFunction
  cms-common.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9959 [15.0.X] Update tag for DQM-Integration to V00-10-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9824 Update RDMA Core, OFI, UCX, and Open MPI, add MPICH [15.0.x]
  cmssw-drop-tools.file
  cmssw-tools.spec
  libfabric.spec
  mpi.spec
  mpich.spec
  openmpi.spec
  rdma-core-VERBS_CONFIG_DIR.patch
  rdma-core.spec
  scram-tools.file/tools/libfabric/libfabric.xml
  scram-tools.file/tools/mpi/mpi.xml
  scram-tools.file/tools/mpich/mpich.xml
  scram-tools.file/tools/rdma-core/rdma-core.xml
  ucx.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok, tests-ib-failure, ngt

#9967 [ROO6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9972 update ppypi packages to gets security updates
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9973 Build g4hepem, celeritas and vecgeom in static move only
  celeritas.spec
  etc/build_options.py
  g4hepem.spec
  scram-project-build.file
  scram-tools.file/tools/celeritas/celeritas.xml
  scram-tools.file/tools/g4hepem/g4hepem_interface.xml
  scram-tools.file/tools/g4hepem/g4hepemcore.xml
  scram-tools.file/tools/g4hepem/g4hepemstatic.xml
  vecgeom.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9975 [ROOT636] Root update v6 36 00 patches 20250721
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9976 added geant4core deps in g4hepem
  scram-tools.file/tools/g4hepem/g4hepem_interface.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9977 [PyTorch] Disable OpenMP multi-threading support for PyTorch
  pytorch.spec
Labels: tests-rejected, externals-approved, fully-signed, orp-pending
