Repository cms-sw/cmsdist, pull requests merged in 2025-05, with the labels that each got.

#9816 [RNTUPLE] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, tests-manual-override

#9820 libunwind: update to current head of master, enable per thread cache
  libunwind.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9822 [G4] Update Geant4 to version 11.3.ref04
  geant4.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9819 Update CUDA to 12.8.1
  cuda.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, tests-ib-failure

#9825 Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, tests-ib-failure

#9826 Updated root to tip of branch v6-36-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9831 Update crab-dev.spec
  crab-dev.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9796 [ROOT6][Do not merge]Build without cuda.pcm
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9835 Cleanup cuda tools to avoid creation of cuda/lib64 links under cmssw/external
  scram-tools.file/tools/cuda/cuda-interface.xml
  scram-tools.file/tools/cuda/cuda-stubs.xml
  scram-tools.file/tools/cuda/cuda.xml
  scram-tools.file/tools/cuda/cupti.xml
  scram-tools.file/tools/cuda/env.sh
  scram-tools.file/tools/cuda/nvperf.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9834 [ROOT6] Testing cuda.pcm generating within CMSSW
  scram-project-build.file
  scram-tools.file/tools/cuda/cuda.xml
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9837 [ROOT636] Updated root to tip of branch v6-36-00-patches
  root.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9838 [ROOT6] more fixes for local pcm for external tools
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9836 [GCC14] build gcc with frame-pointers; sync changes from el10/gcc14
  cmake.spec
  curl.spec
  gcc-prerequisites.spec
  gcc.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9839 [GCC14][Aarch64]Fix for tensorflow-gcc14-aarch64
  tensorflow-gcc14-aarch64.patch
  tensorflow-sources.file
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9818 Update RDMA Core, OFI, UCX, and Open MPI
  cmssw-tools.spec
  libfabric.spec
  openmpi.spec
  rdma-core-VERBS_CONFIG_DIR.patch
  rdma-core.spec
  rocm.spec
  scram-tools.file/tools/libfabric/libfabric.xml
  scram-tools.file/tools/rdma-core/rdma-core.xml
  ucx.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9840 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending, requires-external

#9841 Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9846 Set CLING_PREBUILT_MODULE_PATH so that rootcling can find cuda.pcm from full cmssw
  scram-tools.file/tools/cmssw/cmssw.xml
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#9847 SCRAMV1: fix typo in scramfatal message
  SCRAMV1.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9828 [CUDART] Improved cuda-runtime package
  cuda-runtime.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9850 [ROOT636] Updated root to tip of branch v6-36-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9851 [RNTUPLE] Moved to use root 6.36 patches changes instead of root master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, tests-manual-override

#9849 [ROOT6_X] Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9855 ittnotify: Avoid build errors for aarch64/gcc14
  ittnotify.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9848 [15.0] Update root to tip of root v6-32-00-patches
  root.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, tests-manual-override

#9830 [15_0_X] Update tag for RecoBTag-Combined to V01-30-00
  data/cmsswdata.txt
Labels: tests-pending, orp-approved, externals-pending, pending-signatures

#9857 ittnotify: Avoid build errors for aarch64/gcc14
  ittnotify.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9861 BuildRule: fix checkdeps for alpaka backends
  scram-project-build.file
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9843 ROCm: various updates
  cmssw-tools.spec
  fwlite-tools.spec
  rocm-flags.file
  rocm-rocrand.spec
  rocm.spec
  scram-tools.file/tool-env.file
  scram-tools.file/tools/rocm-rocrand/rocm-rocrand.xml
  scram-tools.file/tools/rocm/rocm-rccl.xml
  scram-tools.file/tools/rocm/rocm-rocrand.xml
  scram-tools.file/tools/rocm/rocm.xml
  toolflags.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, tests-ib-failure

#9863 ONNX Runtime: depend explicitly on Eigen
  onnxruntime.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9860 PyTorch: fix configuration of CUDA and cuDNN
  pytorch-cluster.spec
  pytorch-scatter.spec
  pytorch-sparse.spec
  pytorch.spec
Labels: tests-approved, orp-approved, externals-pending, pending-signatures

#9867 HLS: use patched version of hls from cms-externals
  hls-fix.patch
  hls.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9868 Add scram project hook for setting up local cuda
  cms-common.spec
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9869 Fix for scram build checkdeps
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9870 Force update cms-common revision
  cms-common.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9871 rdma-core: Rename Patch to Patch0
  rdma-core.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#9874 [ROOT636_X] Updated root to tip of branch v6-36-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9873 [ROOT6_X] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9879 cuda-runtime: Updates needed for cuda 12.9
  cuda-runtime.spec
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#9877 Updated root to tip of branch v6-32-00-patches for 15.1.X default IBs
  root.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9883 Disabled alpaka-cuda backend if nvcc is not accessible
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9884 cms-common: Update scram project hook to look for system cuda too
  cms-common.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9886 Update crab-dev.spec to latest tag
  crab-dev.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9885 [RNTUPLE_X] Updated root to tip of branch v6-36-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9891 Added tool to link resolv system lib
  scram-tools.file/tools/systemtools/resolv.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9890 [ROOT6][DD4Hep]Update to latest version 1.32.1
  dd4hep.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9892 Update python packages
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9888 [ROOT636] Updated root to tip of branch v6-36-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9893 ROCM: set HIP_PATH and created clang++.cfg to provide gcc-toolchain and target
  rocm.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9897 [CLANG] Created clang.cfg file and cleanup of toolfiles
  llvm.spec
  scram-tools.file/tools/llvm/llvm-ccompiler.xml
  scram-tools.file/tools/llvm/llvm-cxxcompiler.xml
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9894 BuildRules: add libresolv in LD_PRELOAD for unit tests
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9896 created clang++.cfg and clang.cfg files and dropped --gcc-toolchain from toolfile
  llvm.spec
  scram-tools.file/tools/llvm/llvm-ccompiler.xml
  scram-tools.file/tools/llvm/llvm-cxxcompiler.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9898 Bump conifer to 1.7
  conifer.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9900 BuildRules: Explicitly add gcc-toolchain in compile_commands.json
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending
