Repository cms-sw/cmsdist, pull requests merged in 2025-06, with the labels that each got.

#9901 [GCC13] Enable frame-pointer; sync latest changes from GCC14 branch
  autotools.spec
  bazel-gcc14.patch
  bazel.spec
  bootstrap-driver.spec
  celeritas.spec
  clue-gcc14.patch
  clue.spec
  cmake.spec
  correctionlib-gcc14.patch
  curl.spec
  davix.spec
  dcap.spec
  fakesystem.spec
  file-bootstrap.spec
  flatbuffers.spec
  flex.spec
  gcc-prerequisites.spec
  gcc.spec
  glimpse.spec
  heaptrack.spec
  libarchive-bootstrap.spec
  libffi.spec
  libxslt.spec
  lua-bootstrap.spec
  meschach-1.2b-fPIC.patch
  openldap.spec
  pacparser-gcc14.patch
  pacparser.spec
  pip/awkward-cpp.file
  pip/correctionlib.file
  pip/pybind11.file
  pip/requirements.txt
  pip/scikit-learn.file
  pybind11-array-bound.patch
  pythia6-gcc14.patch
  pythia6.spec
  rpm-set_runpath.file
  sqlite-bootstrap.spec
  sqlite.spec
  tbb.spec
  tensorflow-gcc14-aarch64.patch
  tensorflow-sources.file
  ucx.spec
  xz-bootstrap.spec
  xz.spec
  zstd-bootstrap.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9906 [ROOT636] Updated root to tip of branch v6-36-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9859 PyTorch: fix configuration of CUDA and cuDNN [15.0.x]
  pytorch-cluster.spec
  pytorch-scatter.spec
  pytorch-sparse.spec
  pytorch.spec
Labels: tests-approved, bug-fix, externals-approved, orp-approved, fully-signed, backport-ok

#9911 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9909 [15.0.X] Build cuda.pcm as part of root build
  hls-fix.patch
  hls.spec
  root.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#9880 [15_0_X] Rivet: disable ONNX dependency
  rivet.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9913 [ROOT636] Updated root to tip of branch v6-36-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, tests-ib-failure

#9903 GCC14: Update to version 14.3.1
  gcc.spec
  scram-tools.file/tools/gcc/env.sh
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9919 Update tag for L1Trigger-VertexFinder to V00-02-00
  data/cmsswdata.txt
Labels: externals-pending, pending-signatures, orp-pending

#9921 Update tag for L1Trigger-L1TTrackMatch to V00-03-00
  data/cmsswdata.txt
Labels: externals-pending, pending-signatures, orp-pending

#9917 [ROOT] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending, requires-external, tests-ib-failure

#9933 [ROOT636] Updated root to tip of branch v6-36-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9929 Update of python packages
  hdf5.spec
  pip/Bottleneck.file
  pip/absl-py.file
  pip/beautifulsoup4.file
  pip/blosc2.file
  pip/boost-histogram.file
  pip/correctionlib.file
  pip/findpython.file
  pip/hatch-vcs.file
  pip/hatchling.file
  pip/hepdata-validator.file
  pip/histoprint.file
  pip/iminuit.file
  pip/ipython.file
  pip/jax.file
  pip/jaxlib.file
  pip/jupyterlab-widgets.file
  pip/lizard.file
  pip/mistune.file
  pip/multidict.file
  pip/numpy.file
  pip/opt-einsum.file
  pip/partd.file
  pip/pbs-installer.file
  pip/pdm-backend.file
  pip/poetry-cyclic-deps.patch
  pip/poetry.file
  pip/propcache.file
  pip/pydantic.file
  pip/python-daemon.file
  pip/python-json-logger.file
  pip/pytools.file
  pip/pyzmq.file
  pip/rapidfuzz.file
  pip/requirements.txt
  pip/scikit-build.file
  pip/setuptools-scm.file
  pip/skl2onnx.file
  pip/typing-inspection.file
  pip/uproot.file
  pip/urllib3.file
  pip/yarl.file
  pip/zipp.file
  py3-pip.spec
  py3-setuptools.spec
  python_tools.spec
  rust.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9934 make sure to download unique wheel for each arch
  pip/jaxlib.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#9928 [15.0.X] Update tag for RecoTracker-MkFit to V00-17-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9939 [ROOT] Root update master 20250623
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9942 update urllib3 to version 2.5.0 which contains security fixes
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9948 Update cms-cat.spec target commit
  cms-cat.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9950 Updated Celeritas->v0.6.0, VecGeom->v1.2.11 & updated the patches fro…
  celeritas.spec
  vecgeom-fix-vector.patch
  vecgeom.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9949 Update geant4 to version 11.3.ref06
  geant4.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9954 [ROOT636] Updated root to tip of branch v6-36-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9956 [ROOT6] Root update master 20250630
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending
