Repository cms-sw/cmsdist, pull requests merged in 2025-09, with the labels that each got.

#10039 Fix mpich configuration and update to 4.3.1
  mpich.spec
Labels: tests-approved, orp-approved, externals-pending, pending-signatures

#10034 Update NVIDIA gdrcopy to v2.5.1
  gdrcopy.spec
Labels: tests-approved, orp-approved, externals-pending, pending-signatures

#10049 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#10053 xrootd: update to version 5.8.4
  xrootd.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#10029 [14_2] Update tag for GeneratorInterface-EvtGenInterface to V02-12-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#10031 Update CUDA to version 12.9.1
  cuda.spec
Labels: tests-approved, orp-approved, externals-pending, pending-signatures

#10055 xrootd: update to version 5.8.4
  xrootd.spec
Labels: tests-approved, orp-approved, externals-pending, pending-signatures

#10061 [ROOT6] Root update master 20250908
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#10062 [ROOT636] Root update v6 36 00 patches 20250908
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#10060 Update tag for RecoBTag-Combined to V01-31-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, requires-external

#10030 [15_0] Update tag for GeneratorInterface-EvtGenInterface to V02-12-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#10069 expose additional libraries needed for celeritas geant4 interface compilation
  scram-tools.file/tools/celeritas/celeritas.xml
  scram-tools.file/tools/geant4/geant4core.xml
Labels: tests-approved, orp-approved, externals-pending, pending-signatures

#10082 [hls] Cleanup of C headers e.g. stdlib.h, stdio.h, assert.h
  hls.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#10081 Fix for various relocation issues
  c-blosc2.spec
  celeritas.spec
  libunwind.spec
  madgraph5amcatnlo.spec
  openmpi.spec
  pip/pyzmq.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#10080 [RFC] Add tool to automatically update most of ROCm subpackages' versions
  utils/update_rocm.py
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#10083 clhep: replace stdlib.h with cstdlib
  clhep.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#10073 [Sherpa]Apply the upstream patch to avoid setting env
  sherpa-setenv.patch
  sherpa.spec
Labels: tests-approved, externals-approved, orp-approved, generators-approved, fully-signed

#10094 cms-common: Print stack trace and exit with non-zero code if the traced application crashes
  cms-common.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending
