Repository cms-sw/cmsdist, pull requests merged in 2025-01, with the labels that each got.

#9589 Update hydjet2: version 2.4.4 with bugfix on mc code 10333
  hydjet2.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9594 Update monit tools version
  cmsmon-tools.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9596 Update crab-dev.spec to latest
  crab-dev.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9598 [ROOT634]Updated root to tip of branch v6-34-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9597 [ROOT6]Updated root to tip of branch master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9602 [12.4]Update tag for GeneratorInterface-EvtGenInterface to V02-10-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9603 [10.6]Update tag for GeneratorInterface-EvtGenInterface to V02-10-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9601 [13.0] Update tag for GeneratorInterface-EvtGenInterface to V02-10-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9600 [14.0] Update tag for GeneratorInterface-EvtGenInterface to V02-10-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9595 [14.1.X]Update hydjet2: version 2.4.4 with bugfix on mc code 10333
  hydjet2.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9593 [14_0_X] Update tag for Configuration-Generator to V01-10-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9591 [12_4_X] Update tag for Configuration-Generator to V01-10-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9592 [13_0_X] Update tag for Configuration-Generator to V01-10-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9605 Update valgrind to 3.24
  valgrind.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9607 Update py3 packages luigi and jinja2
  pip/requirements.txt
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9608 [ROOT6]Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9606 update `hls4mlEmulatorExtras` to v1.1.4
  hls4mlEmulatorExtras.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9610 [DEVEL]Build rules non default min microarch
  scram-project-build.file
  scram-tools.file/tools/cuda/cuda.xml
  scram-tools.file/tools/rocm/rocm.xml
  toolflags.file
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#9611 refresh edm plugin cache for extra micro-archs too
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9615 Rivet 4.0.2 and YODA 2.0.2
  rivet.spec
  yoda.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9617 Buildrule: fixes when extra micro-arch is subset of default microarch
  scram-project-build.file
  scram-tools.file/tools/cuda/cuda.xml
  scram-tools.file/tools/rocm/rocm.xml
  toolflags.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9624 BuildRules: Fixes for python/Pkg/__init__.py and force linking libs
  scram-project-build.file
  scram-tools.file/tools/pytorch/pytorch.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9626 Bug fix: Only create poison edm cache if the multi-arch dir exists
  scram-project-build.file
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9613 compile HepMC3 interface in the package photospp
  photospp.spec
  scram-tools.file/tools/photospp/photospp.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9625 ONNXRuntime: Update to version 1.20.1
  onnxruntime.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9628 Updated root to tip of branch v6-34-00-patches
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9630 Update ROCm to 6.2.4 and GPU targets
  rocm-rocrand.spec
  rocm.spec
  scram-tools.file/tools/rocm/rocm.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, backport-ok, tests-ib-failure

#9629 buildrulles: fix for linking cuda libs
  scram-project-build.file
  scram-tools.file/tools/gcc/env.sh
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, tests-ib-failure

#9620 Update CUDA to 12.6.3 and cuDNN to 9.6.0
  cuda.spec
  cudnn.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, tests-ib-failure

#9492 [14.1.X] Update xrootd to latest version 5.7.2
  xrootd.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9551 [14.2] XRootd: version 5.7.2
  xrootd.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok, tests-ib-failure

#9477 [14.0.X]Backport xrootd 5.7.2
  isal.spec
  scram-tools.file/tools/isal/isal.xml
  xrootd.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9632 Build ROCm rocprofiler-register from sources
  rocm.spec
  scram-tools.file/tools/rocm/rocm.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9581 Update NVIDIA gdrcopy to v2.4.4
  gdrcopy.spec
Labels: tests-approved, bug-fix, externals-approved, orp-approved, fully-signed

#9635 Update libunwind version disable per thread cache
  libunwind.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9633 Added FORCE_LINK to pytorch custom ops libraries
  scram-project-build.file
  scram-tools.file/tools/pytorch-cluster/pytorch-cluster.xml
  scram-tools.file/tools/pytorch-scatter/pytorch-scatter.xml
  scram-tools.file/tools/pytorch-sparse/pytorch-sparse.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9637 Build rules: set default micro arch for all builds
  scram-project-build.file
  toolflags.file
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9582 Update NVIDIA gdrcopy to v2.4.4 [14.2.x]
  gdrcopy.spec
Labels: tests-approved, bug-fix, externals-approved, orp-approved, fully-signed, backport-ok

#9638 Update virtualenv 20.29.1
  pip/requirements.txt
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9634 [GCC13] Update to latest changes from gcc 13 branch
  gcc.spec
  onnxruntime-gcc13.patch
  onnxruntime.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9585 [CLANG]Update llvm to tag 19.1.6
  clang-uml.spec
  llvm.spec
  py3-dxr.spec
  rivet-clang19.patch
  rivet.spec
  rocm.spec
  vecgeom-clang19.patch
  vecgeom.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9641 cleanup gcc13 branch: updated bootstrap driver
  bootstrap-driver.spec
  grpc-gcc11.patch
  pip/cryptography.file
  protobuf-std_iterator-8741.patch
  tbb-gcc13.patch
  tensorflow-requires.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9636 Update CUDA to 12.8.0
  cuda.spec
  onnxruntime.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9640 backport changes from gcc13 branch to master
  giflib.spec
  igprof.spec
  onnxruntime-gcc13.patch
  onnxruntime.spec
  pip/cryptography.file
  professor2.spec
  protobuf.spec
  tbb.spec
  triton-inference-client-uint8.patch
  triton-inference-client.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9650 [CMSSW_14_0_X] Update tag for GeneratorInterface-EvtGenInterface to V02-11-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9648 [CMSSW_12_4_X] Update tag for GeneratorInterface-EvtGenInterface to V02-11-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9649 [CMSSW_13_0_X] Update tag for GeneratorInterface-EvtGenInterface to V02-11-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9651 TF: apply upstream patch to fix gcc13/aarch64 build errors
  tensorflow-sources.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9653 onnxruntime: Use single thread to compile with nvcc
  onnxruntime.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9652 build rule: fixes clang-tidy, use relative path for cmssw headers
  scram-project-build.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending, requires-external

#9654 Update pybind11 and apply array out of bound patch
  pip/pybind11.file
  pip/requirements.txt
  pybind11-array-bound.patch
Labels: tests-approved, externals-pending, pending-signatures, orp-pending
