Repository cms-sw/cmsdist, pull requests merged in 2025-08, with the labels that each got.

#9988 [ROOT636] Root update v6 36 00 patches 20250804
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9993 [G4ADEPT_X] Update G4EMLOW to version 8.7
  geant4-G4EMLOW.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9989 [G4] Update geant4 to 11.3.ref07
  geant4.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending, requires-external

#9996 cms-git-tools: Added subpackage-aware cherry-pick
  cms-git-tools.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9998 SCRAMV1: unset PYTHONHOME via scram wrapper script
  SCRAMV1.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9999 [G4AdePT] update AdePT to v0.1.2-alpha
  adept.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending, requires-external

#10002 G4Adept: Update geant4 to 11.3.ref07
  geant4.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#10004 GDB: build using relocatable python libdir
  gdb.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#10008 [G4AdePT] add AdePT host library
  scram-tools.file/tools/adept/adept.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#10012 [141X][v630][RF] Fix implementation of HS3 importers
  root.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#10016 [G4AdePT] Bump AdePT version to v0.1.3-alpha
  adept.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#10005 [ROOT6] Root update master 20250811
  dqmgui-gcc12.patch
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#10017 cleanup for py3 blosc/blosc2 and tables packages
  c-blosc.spec
  c-blosc2.spec
  pip/blosc.file
  pip/blosc2.file
  pip/requirements.txt
  pip/tables.file
  scram-tools.file/bin/get_tools
  scram-tools.file/tools/c-blosc/c-blosc.xml
  scram-tools.file/tools/c-blosc2/c-blosc2.xml
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#10022 [12_4] Update tag for GeneratorInterface-EvtGenInterface to V02-12-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#10035 Update crab-dev.spec to latest
  crab-dev.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed

#10042 Update hwloc to v2.12.2
  hwloc.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#10036 [PY312] Add blosc to requirement.txt
  pip/requirements.txt
  pip/tables.file
Labels: tests-approved, externals-approved, fully-signed, orp-pending, tests-ib-failure
