Repository cms-sw/cmsdist, pull requests merged in 2025-04, with the labels that each got.

#9768 [ROOTMaster] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9767 [G4] Update Geant4 to 11.3.ref03
  geant4.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9763 Rivet 4.1.0 and Yoda 2.1.0
  rivet-pyextfjcontrib.patch
  rivet.spec
  yoda.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending

#9728 [13_2_X] Update tag for RecoBTag-Combined to V01-27-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9729 [14_1_X] Update tag for RecoBTag-Combined to V01-27-00
  data/cmsswdata.txt
Labels: tests-approved, externals-approved, fully-signed, orp-pending, backport-ok

#9776 Update cmssw-wm-tools.spec
  cmssw-wm-tools.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9774 [ROOT6] Updated root to tip of branch master
  dd4hep.spec
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending, requires-external

#9759 Build Tensorflow 2.12.0 with ZenDNN enabled.
  tensorflow-sources.file
Labels: tests-pending, hold, externals-pending, pending-signatures, orp-pending

#9781 [ROOT6]Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9779 ROOT 6.32.12: Updated root to tip of branch v6-32-00-patches
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9783 Bump crab-dev
  crab-dev.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9750 [14.1.X] Fix jupyter-server deps: added overrides
  pip/jupyter-server.file
  pip/requirements.txt
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9784 port fix for crab submit --dryrun to prod
  crab-prod.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9785 [ROOT6] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9787 Updated root to tip of branch v6-34-00-patches
  root.spec
Labels: tests-pending, externals-pending, pending-signatures, orp-pending

#9793 added frame_pointer build option
  etc/build_options.py
  frame_pointer-opt.file
  scram-tools.file/tools/gcc/gcc-cxxcompiler.xml
  toolflags.file
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9802 cmssw-wm-tools: Fix the execution permission of cmssw_enable_custom_timeout.py
  cmssw-wm-tools.spec
Labels: externals-pending, pending-signatures, tests-started, orp-pending

#9805 Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, tests-ib-failure

#9803 [RNTUPLE] Update root to tip of master branch
  dd4hep.spec
  root.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, tests-manual-override

#9808 Update tag for RecoBTag-Combined to V01-29-00
  data/cmsswdata.txt
Labels: orp-approved, externals-pending, pending-signatures, tests-started

#9798 [15_0_X] Backport: Update tag for L1Trigger-L1TCalorimeter to V01-03-00
  data/cmsswdata.txt
Labels: tests-approved, orp-approved, externals-pending, pending-signatures

#9809 Update AXOL1TL.spec to v5.0.1 for timing issue fix
  AXOL1TL.spec
Labels: tests-approved, externals-pending, pending-signatures, orp-pending

#9813 [el10] various fixes/cleanup to avoid el10 errors/warnings
  git.spec
  java-env.spec
  meschach.spec
  pip/cms-tfaot.file
  rivet.spec
  rpm-preamble.file
  tensorflow-xla-runtime.spec
  tinyxml2.spec
  xrdcl-record.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9815 [ROOT634_X] Updated root to tip of branch v6-34-00-patches
  root.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending, tests-ib-failure

#9811 [ROOT6_X] Updated root to tip of branch master
  root.spec
Labels: tests-approved, externals-approved, fully-signed, orp-pending, tests-ib-failure

#9810 [15.0.X] Update AXOL1TL.spec to v5.0.1 for timing issue fix (backport)
  AXOL1TL.spec
Labels: tests-approved, externals-approved, orp-approved, fully-signed, backport-ok

#9817 [ROOT6] Update root master
  root.spec
Labels: tests-rejected, externals-pending, pending-signatures, orp-pending

#9807 fastjet-contrib 1.101
  fastjet-contrib.spec
Labels: tests-approved, orp-approved, externals-pending, pending-signatures

#9778 Add L1TSC4NGJetModel
  L1TSC4NGJetModel.spec
  cmssw-tools.spec
  scram-tools.file/tools/L1TSC4NGJetModel/l1tsc4ngjetmodel.xml
Labels: tests-approved, externals-approved, orp-approved, fully-signed
